### ISSUE TITLE
User should have the option to display time and battery levels while browsing

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#1108]
## Hardware

All
## Steps to Reproduce

1. Launch FxR

## Current Behavior

User has know idea what time or current battery levels (head set and controllers) with out exiting FxR.
## Expected Behavior

User should be able to see the time and battery levels.
## Possible Solution

Add UI to display this information to the user if they choose.
## Context

These items are visible in the tray on the Oculus browser.

**Comment by philip-lamb** [comment]
@thenadj Please add to list of items for design consideration.

P5 without milestone until/unless Design accepts for uptake and work.

**Comment by thenadj** [comment]
@philip-lamb Added.

**Comment by feiss** [comment]
Quick explorations:


**Option A: Mimicking Oculus Home layout**. Nothing happens when clicking or hovering on icons.

<img width="969" alt="Screenshot 2020-07-10 at 02 01 04" src="https://user-images.githubusercontent.com/359872/87102269-b1d6b800-c251-11ea-8511-bcac2122e67c.png">

* Pros: Familiarity, easy and fast reading of information. Also, easy to use (there's nothing to do!)
* Cons: Cluttered tray. Adds too much noise with non relevant information.

.
.


**Option B: More minimalist**, showing summary icons that reflect actual state, and displaying more information via tooltips on hover or click.

<img width="1587" alt="Screenshot 2020-07-10 at 02 01 23" src="https://user-images.githubusercontent.com/359872/87102357-f3fff980-c251-11ea-92b5-d327bc9006ff.png">

* Pros: Simple, elegant. Easy to the eye. Shows enough information without much visual noise. Leaves space on the left for future additions (Firefox Sync info maybe?).
* Cons: Maybe a bit hard to find how it works? But it should be quite easy, the tooltips would appear just by pointing the controller to the icons, and that's something that the user would do if he wants to know more about those icons.

.
.

I can make more alternatives. From these two I kinda prefer the second one, more friendly and uncluttered. 

(Please noticed that this designs are not final, but quick mockups)

**Comment by feiss** [comment]
Proposed by @MortimerGoro , here's another take, trying to show individual battery information with icons and tooltips.

<img width="923" alt="Screenshot 2020-07-10 at 16 55 31" src="https://user-images.githubusercontent.com/359872/87168248-7c23e480-c2ce-11ea-9bce-dec93e23d8a0.png">

And with all icons to the left:

<img width="931" alt="Screenshot 2020-07-10 at 17 01 52" src="https://user-images.githubusercontent.com/359872/87168638-184deb80-c2cf-11ea-9c7a-f839d3cc02ec.png">

**Comment by feiss** [comment]
more battery-like progress bars

<img width="959" alt="Screenshot 2020-07-10 at 19 46 48" src="https://user-images.githubusercontent.com/359872/87183275-23f8dc80-c2e6-11ea-807c-f74b2c5bc1f0.png">

**Comment by joshmarinacci** [comment]
ooh. very nice

**Comment by feiss** [comment]
I've been exploring many variants:

1. As @MortimerGoro suggested, grouping the icons to the left and the right feels more balanced and pleasing. Also, it is coherent to the Oculus Home layout. My concern was that we may want to add additional stuff in this bar on the left in the future. But that may be foreseeing too much, and we can always change this layout and move the clock+wifi to the left, it's not such a critical change.
2. Showing the icons that resemble actual controllers improves readability and clarity. I added 3 colored dots as Oculus Home does now, which is quite readable too (actual label+battery levels will show on hover tooltip).
3. This simpler icons fit better with the whole FxR UI. The previous ones were too 'complex' or detailed.

<img width="994" alt="Screenshot 2020-07-14 at 02 55 05" src="https://user-images.githubusercontent.com/359872/87368262-7d2e6d80-c57d-11ea-9fc7-f7ced97111ee.png">

**Comment by feiss** [comment]
I went forward with the design, defining different states and situations.

<img width="923" alt="Screenshot 2020-07-14 at 20 14 49" src="https://user-images.githubusercontent.com/359872/87461401-b236d080-c60e-11ea-84de-cc1dcde280ac.png">

**Comment by feiss** [comment]
Saved these files to Drive:

icon-statusbar-wifi100.svg
icon-statusbar-wifi75.svg
icon-statusbar-wifi50.svg
icon-statusbar-wifi25.svg
icon-statusbar-wifi0.svg

icon-statusbar-battery0.svg
icon-statusbar-battery100.svg
icon-statusbar-battery50.svg
icon-statusbar-battery25.svg

icon-statusbar-leftcontroller.svg
icon-statusbar-rightcontroller.svg
icon-statusbar-headset-normal.svg
icon-statusbar-headset-charging.svg

<img width="1280" alt="Screenshot 2020-07-16 at 00 08 17" src="https://user-images.githubusercontent.com/359872/87604060-8859d880-c6f8-11ea-86fd-2655e33716ab.png">
