### ISSUE TITLE
Controller beam changes hand after invocation of quick menu

### ISSUE THREAD

**Issue by philip-lamb** [MozillaReality/FirefoxReality#1262]
## Hardware
HTC Vive Focus Plus
FxR v1.2

## Steps to Reproduce
From partner testing: " Controller beam will change to the other one after invoke quick menu."

## Current Behavior
Controller beam changes hands.

## Expected Behavior
Controller beam remains in same hand being used prior to menu invocation

## Error Logs and Stack Traces

**Comment by daoshengmu** [comment]
#1266 fixes this issue. However, if we try to detect the focused hand change in the mini menu, we have no way to do. In the API level, we can't get the newest button state, and `WVR_GetDefaultControllerRole()` is also not useful for 6 DOF controllers.

**Comment by kaipinglee** [comment]
Relative with #1081 [P0] Controller beam will change to the other one after invoking the quick menu. (Not totally fixed in v1.2.1)
Please compare below 2 videos.
1. controller behavior on launcher: [https://drive.google.com/open?id=1lxZysXLekgcdCINSTgVeMeoYee5158oo](url)
2. controller behavior on FxR: [https://drive.google.com/open?id=1UQjc-YxBEHfGOQUVkeyI85odCl2toajM](url)

**Comment by bluemarvin** [comment]
There does not appear to be an API to detect what controller currently has focus. When it is changed in the mini-menu, it is switch it at the system level so FxR has no way to detect it. Additionally at start up, since there is no API to detect which controller has focus, we just default to the right hand controller.

**Comment by daoshengmu** [comment]
> #1266 fixes this issue. However, if we try to detect the focused hand change in the mini menu, we have no way to do. In the API level, we also can't get the newest button state, and `WVR_GetDefaultControllerRole()` is also not useful for 6 DOF controllers.

As I said, we would look forward API support for achieving this. @kaipinglee if you know any API that will help, please make us know.

**Comment by bluemarvin** [comment]
@daoshengmu I thought about it, but would have to guess the values at this point. If they want the beam direction to be uniform, there really needs to be an API to get offset and orientation. Also an API to get access to the controller model would also be nice. Since it seems each device contains a model for its unique controller, there just doesn't seem to be a native API to get a path to it.
