### ISSUE TITLE
Use DeepSpeech instead of Google for VoiceFill

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#1296]
Investigate (and likely implement) using DeepSpeech STT instead of Google's STT for voice fill.

First priority if Mandarin, offline.
Next is English. TBD whether online or offline.

**Comment by philip-lamb** [comment]
Noting for future reference: needs a separate issue to consider the delivery mechanism for the language model files.

**Comment by keianhzo** [comment]
@jvonitter @philip-lamb  I've been talking to @lissyx today as he just made a PR to the experimental `deepspeech` branch to use local DeepSpeech instead of Google's STT. 

It seems that the experimental `deepspeech` branch has been there for a while with little or not testing and he wanted us to test and report. I've rebased the branch to keep it up to date and added the minimal logic for downloading the DeepSpeech model. I leave an APK here so you can evaluate the current status: 

https://send.firefox.com/download/fbf4702f09b0e285/#jw_drGjbsa2rlvMNZvH40Q

Upon the first voice search you will get prompts when the model download finishes and when the model is unzipped, then you can start using DeepSpeech otherwise you will see a prompt saying that the model is not ready. The model is quite big so it might take a while, you can remove the headset while it finishes if you want.
