### ISSUE TITLE
Custom skyboxes not loading on Oculus Quest

### ISSUE THREAD

**Issue by elliotttate** [MozillaReality/FirefoxReality#1493]
## Hardware
Oculus Quest, Firefox Reality 1.3

## Steps to Reproduce
Follow the exact steps in https://github.com/MozillaReality/FirefoxReality/wiki/Environments

## Current Behavior
Skybox / Cubemap does not load (skybox is black)

## Expected Behavior
Expected one of the demo skybox's to load

```
```

</details>

**Comment by delaneyj** [comment]
I'm running into the exact same issue, 

```
./adb shell "ls /sdcard/Android/data/org.mozilla.vrbrowser/files/skybox/"
negx.jpg
negy.jpg
negz.jpg
posx.jpg
posy.jpg
posz.jpg
```

Shows the files are place [per the wiki](https://github.com/MozillaReality/FirefoxReality/wiki/Environments).

**Comment by elliotttate** [comment]
@delaneyj I found a workaround for it and made a guide. You need to compress the JPG file using the RGB8_ETC2 compression format first https://www.notion.so/beastsaber/Creating-or-Installing-Skyboxes-For-Firefox-Reality-a74bb56037d741bab7d1777bd38f3391

**Comment by elliotttate** [comment]
(If this is a requirement now, then the github tutorial showing you can put JPG's in should be updated)

**Comment by delaneyj** [comment]
Unfortunately, at least on Linux, they are using archaic libpng/tiff that aren't supported or available for modern distros.  This is a definite issue if this is the only way to create the proper files.

**Comment by philip-lamb** [comment]
There are a variety of etc2 compression tools. You could try https://github.com/google/etc2comp (although I haven't personally used it). @elliotttate It'd be great if we could borrow your instructions for an update of the wiki page :-)

**Comment by delaneyj** [comment]
@philip-lamb actually I did try that repo.  Was able to clone and build no problems.  Used `./EtcTool/EtcTool -format RGB8 ../../cubemap/negx.png -output ./negx.ktv` to match @elliotttate's guide as close as possible with no luck.  Is there specific args that are known to work with e2cTool @philip-lamb ?

**Comment by elliotttate** [comment]
@philip-lamb Yes, please feel free to use anything from the guide I made on the wiki.

**Comment by elliotttate** [comment]
@delaneyj If you look in the "Tools" folder of this master repo, open the "Gulpfile.js" and search for "compress." You'll see the specific args ran for using the Etc2Tool

**Comment by bluemarvin** [comment]
Both jpg and png should work. If it broke it's a bug.

**Comment by elliotttate** [comment]
Just a cool FYI, easy skybox browsing, uploading and downloading for Firefox Reality has been added to https://sidequestvr.com/

**Comment by MortimerGoro** [comment]
Skybox improvements in #1513:
- Fixes the JPG issue with custom skyboxes.
- Also makes it possible to switch between stock and custom environments without a restart, even if they have different formats.
- I updated the paths in the wiki: https://github.com/MozillaReality/FirefoxReality/wiki/Environments

**Comment by elliotttate** [comment]
@MortimerGoro You are awesome! Would it be hard to also add support for more than one custom environment at a time? (aka, you can add folders of different ones. In the environment picker, it uses the folder name for environment and you can toggle between multiple custom environments without hooking your VR HMD back up to a PC each time)

**Comment by MortimerGoro** [comment]
@elliotttate wow, you read my mind I just wrote this here before seeing this message: https://github.com/MozillaReality/FirefoxReality/pull/1513#issuecomment-518667878

I definitively want to do that

**Comment by mikemonett** [comment]
It's been over two years since anyone added new comments here. 

This thread helped me successfully make a custom skybox today in the new situation, where now Quest 2 is the latest Oculus, and 12.2 is the latest Firefox Reality. Thanks, especially to you, @delaneyj.

Here is my detailed summary of exactly how I achieved my nice skybox background in Firefox Reality:

------------------
Nov. 19, 2021

Using my laptop with Windows 10, I successfully made a skybox in Quest 2 Firefox Reality (latest version, 12.2, 12-15-2020) this way:

1. I made sure Developer mode was on for the Quest 2, by checking in the Oculus app on my smartphone.

2. I downloaded a Street View 360 from Street View Download 360 with these settings:

	a. Panorama download

	b. Single Panorama

	c. 6656 x 3328 resolution

3. I made six .png cubemap faces from the Street View 360 with Qbit with these settings:

	a. Output Naming: [face].[ext] -e.g. front.png

	b. Output Size: 1024 x 1024

	c. Output Encoding: png

	d. Supersampling: Off (draft quality, faster)

	e. Swap Left/Right: Off (Unreal)

4. I copied these six into a folder called "originals" as backups in case I messed anything up.

5. In Irfanview, I mirrored all six .png files by Horizontal Flip in the Image menu, and resaved them

	with the same names.

6. I renamed the .png files thus:

	front became posz
	right became negx
	back became negz
	left became posx
	
	(These are listed above in the order that the pictures appeared from left to right in the 360.
		In Firefox Reality, front or posz appeared behind me, back or negz was directly before me,
		left or posx was on my right, and right or negx was on my left.)
	And,

	up became posy
	down became negy

7. I converted the six .pngs to .ktx with the same names in Mali with these settings:

	a. Compress selected images (File menu)

	b. ETC1/ETC2 tab

	c. Select KTX, Fast, ETC2, Perceptual.

	d. ETC2 Compression Format: RGB8_ETC2

8. I copied the six .ktx files with SideQuest into a new folder on the Quest 2, 
		sdcard > Android > data > org.mozilla.vrbrowser > files > skybox .

9. I verified the result in Firefox Reality after doing Settings -> Environments
	-> Enable Environment Override: On .

**Comment by jeromewtf** [comment]
follow mikemonett description.

7. Mali tool from ARM ist not available anymore. 
Use etc2comp (https://github.com/google/etc2comp) instead. You have to install VS Studio and cmake and compile it yourself.

ETC2 Compression via command line.
cmd: etctool.exe input.png -output output.ktx -format RGBA8 -effort 100 -v
bat: for /r %%i in (\sky\*) do .\EtcTool.exe %%i -output %%i.ktx -format RGBA8 -effort 100 -v

Rename files properly and copy to: Android > data > org.mozilla.vrbrowser > files > skybox 

It is working on Pico G2 4K
