### ISSUE TITLE
Address bar does not resize when exiting priavte browsing

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#1562]
## Hardware

All
## Steps to Reproduce

1. Enter private browsing
2. Resize window to 2x
3. Exit private browsing.

## Current Behavior

The address bar retains its 2x size:
![image](https://user-images.githubusercontent.com/3066/62894421-84138700-bd01-11e9-827a-8ba94c9b51d2.png)

## Expected Behavior

The address bar should properly resize upon exiting private browsing.

**Comment by keianhzo** [comment]
@bluemarvin I don't seem to be able to reproduce this one with the current master. I think it was fixed by: 
https://github.com/MozillaReality/FirefoxReality/blob/5b3c961d6ed53ab4e1eede3f9c331620e484cbaa/app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java#L399
and:
https://github.com/MozillaReality/FirefoxReality/blob/5b3c961d6ed53ab4e1eede3f9c331620e484cbaa/app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java#L382

in the private session recreation PR:
https://github.com/MozillaReality/FirefoxReality/pull/1554

**Comment by bluemarvin** [comment]
Works for me now.
