### ISSUE TITLE
Seeking on an HLS stream using hls.js can freeze (affects Hubs)

### ISSUE THREAD

**Issue by gfodor** [MozillaReality/FirefoxReality#1602]
## Configuration

Firefox Reality version: 1.3
Firefox Reality build ID: 9000adc

Hardware: Oculus Quest

## Steps to Reproduce
1. Go to https://players.akamai.com/hls/
2. Click "Load" in top right to get big buck bunny to play
3. Seek excessively. Click on the playback bar several times, skipping some seconds each time, pausing periodically to let the video continue playback. After a few attempts, the video will freeze 2-3 seconds after resuming and the player will be broken and unable to play any points further.

## Current Behavior
Excessive seeking in HLS streams can fail, causing playback to freeze completely. This is exasperated with live streams when trying to seek to the end.

## Expected Behavior
Seeking should be robust and never break the player.

## Context
This seems to be a proximate cause leading to frozen videos in Hubs.

## Error Logs and Stack Traces

```
```

</details>

**Comment by philip-lamb** [comment]
Can you reproduce it in Firefox Preview for Android?

**Comment by bluemarvin** [comment]
I was able to reproduce the issue in 1.3 but was not able to reproduce in the latest 1.4 builds. It may have been an issue that was fixed in Gecko since 1.3 or is just harder to reproduce in 1.4.

https://queue.taskcluster.net/v1/task/A7Vb1yiySAOJTopgkF-Dgw/runs/0/artifacts/public/FirefoxReality-1.4-32321428-oculusvr-arm64-staging-signed-aligned.apk

**Comment by gfodor** [comment]
yup, this looks fixed -- I'll make sure to test master build before submitting bugs :)
