### ISSUE TITLE
The inactive control buttons are briefly getting a white effect when the active ones are clicked

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#1722]
**[Affected Versions]:**
- Firefox Reality 1.4-32420004 (RC1) build.

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- Have the latest Firefox Reality 1.4-32420004 (RC1) build installed.
- The headset is turned on and the app is opened.

**[Steps to reproduce]:**
1. Click the "+" button to open a new window.
2. Click on one of the active control buttons "<" or ">" displayed on top of the windows. 
3. Observe the inactive control button "<" displayed above the left window.

**[Expected results]:**
- The control button's UI is not changed.

**[Actual results]:**
- The control button briefly gains a white effect.

**[Notes]:**
- Attached are a screen recording of the issue: [link](https://drive.google.com/open?id=1KN4_k_jRDN6UkJC534jd9aKEp6pdiN5A)

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 5-32762123 (93b664b9) installed on the Oculus Go, Quest, HTC Vive Focus, Focus Plus and Lenovo Mirage Solo headsets.
Now, the inactive control buttons are not getting a white effect when the active ones are clicked.
