### ISSUE TITLE
Support haptic feedback in immersive mode of HTC Vive Focus

### ISSUE THREAD

**Issue by kearwood** [MozillaReality/FirefoxReality#173]
This will be dependent on Bugzilla Bug 1473397 - Add Haptic Feedback support to gfxVRExternal and VRSessionOpenVR

**Comment by philip-lamb** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1473397 is resolved fixed.

**Comment by philip-lamb** [comment]
https://github.com/MozillaReality/FirefoxReality/issues/676#issuecomment-434777409

**Comment by philip-lamb** [comment]
Pushing to 1.3.

**Comment by daoshengmu** [comment]
I am going to work on it next week.

WaveVR: WVR_TriggerVibration  (https://hub.vive.com/storage/docs/en-us/WVR_TriggerVibration.html)

Oculus: vrapi_SetHapticVibrationBuffer
vrapi_SetHapticVibrationBuffer
(https://developer.oculus.com/reference/mobile/1.25/vr_api_input_8h)

**Comment by daoshengmu** [comment]
In WaveVR, the current code flow doesn't enter [VRManager::VibrateHaptic](https://dxr.mozilla.org/mozilla-central/source/gfx/vr/VRManager.cpp#653), so External VR state of `browser.hapticState` is always zero.

I guess it is because `GamepadHapticActuator` length is zero when using standalone headsets. I will revisit and figure out it at FxR **v1.6.**

**Comment by daoshengmu** [comment]
I saw there is a bug from the Gecko side when re-entering WebVR page. It can be reproduced by Firefox Desktop. We will address this issue there, https://bugzilla.mozilla.org/show_bug.cgi?id=1605788.
