### ISSUE TITLE
The language for displaying websites is not automatically changed to the language selected for the app if it's changed after the language settings are reset

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#1748]
**[Affected Versions]:**
- Firefox Reality 1.4-32450938 (RC2)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The 1.4-32450938 (RC2) build is installed on the device
- The headset is turned on and the app is opened.
- Have another language set for the "Display Language for App:" preference than the default "English (United States)".

**[Steps to reproduce]:**
1. Click the "Settings" menu and open the "Language" card.
2. Click the "Reset" button and click the "Restart Now" button from the prompt displayed.
3. Reopen the "Language" card and click the "Edit" button for the "Display Language for App:" preference. 
4. Select a different language than the default "English (United States)" and click the "Restart Now" button.
5. Reopen the "Language" card and observe the "Preferred Language for Displaying Websites:" preference.

**[Expected results]:**
- The selected language for the App preference is also applied for Displaying Websites preference.

**[Actual results]:**
- The default language "English (United States)", remains applied for the "Preferred Language for Displaying Websites:" preference.

**[Notes]:**
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1jVEaI-FksKi10ERh4mDBPqBMhfbXfw-b)

**Comment by keianhzo** [comment]
The PR above changes the behavior to make it more aligned with the Desktop one. Now upon a fresh start or update as there are not persisted content languages we show the current display language as content language. From that moment on we always show whatever the user has saved, so now the user could clear the list and we will show no language for content in the main language panel. I think it makes more sense to keep this aligned with what Desktop does instead of always keeping a non removable default language that always is the display language although the app will always use that one in case the user has removed all the content languages.

Make sure you update the tests accordingly for the future.
