### ISSUE TITLE
Add an option to hide 3D model of a 'plate'

### ISSUE THREAD

**Issue by ziomio** [MozillaReality/FirefoxReality#180]
FirefoxReality has a 3D model of a black 'plate' which I am 'standing' in - I want an option to hide it completely. I need to hide it because when I resize browser window to the max size - bottom part of browser window is not visible because plate intersects with it...

**Comment by nancyhang** [comment]
@thenadj

**Comment by avrignaud** [comment]
Nadja, issue is that window sizing to max can occlude the floor plate in space - and concern is that this might happen with meadow environment, especially if keyboard or other items are below window.

**Comment by thenadj** [comment]
It is not intersecting with the 'floor' in the meadow environment. Not sure if this already got fixed since this issue was filed or if changing from the space theme to the meadow fixed it. 

However, there are some rocks on the left that are a bit too close to the fully expanded window in focus mode. I contacted our 3D artist and asked her to make changes to the environment to make more room for the window. 

The keyboard will never show in focus mode, so there should not be an interaction issue there.

**Comment by bluemarvin** [comment]
What happens when a user clicks on a text box in the browser window when in focus mode?

**Comment by thenadj** [comment]
[Bug-15 Focus Mode URL Preview_001.pdf](https://github.com/MozillaReality/FirefoxReality/files/2215707/Bug-15.Focus.Mode.URL.Preview_001.pdf)
I am attaching the UI BUG document that answers this question. When a user clicks on the URL bar in focus mode, focus mode will close and take the user back to default browser mode.

**Comment by thenadj** [comment]
Entering text in a text box in Focus mode will bring up the keyboard so they can enter text and navigate without leaving focus mode.

**Comment by avrignaud** [comment]
Closing for now since keyboard/window layout (and interaction with environment) is being completely revamped. Will revisit if issue continues.
