### ISSUE TITLE
History page uses Today label for history items older than a week.

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#1824]
## Configuration

Firefox Reality version: 1.4

Hardware: All

## Steps to Reproduce

1. Have history over a week old
2. View history page.

## Current Behavior

Items older than a week are labeled `Today` instead of `Older`
## Expected Behavior

Items should be under label `Older`

## Possible Solution

This line is wrong: https://github.com/MozillaReality/FirefoxReality/blob/72654418ad5a19cc98ab5126154b0b4fb6055c37/app/src/common/shared/org/mozilla/vrbrowser/ui/views/HistoryView.java#L161
It should use `R.string.history_section_older` instead of  `R.string.history_section_today`

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality 1.5-32691850 (49ffa844) installed on the HTC Vive Focus, Focus Plus and Lenovo Mirage Solo headsets.
Now, the label for the history items older than a week is correct.
I was not able to test this issue on the Oculus Quest and Go because the history feeds were empty. (they were used in other testing and had no history items)
