### ISSUE TITLE
Add ability to request desktop version of a site

### ISSUE THREAD

**Issue by larsbergstrom** [MozillaReality/FirefoxReality#19]
From: https://twitter.com/moocow1452/status/985525427555962888
Suggestion: I'm trying to get Prime Video on my Daydream using Firefox Reality, but it will only stream in Desktop mode. Could requesting a desktop version be an option in the final version?

**Comment by TrevorFSmith** [comment]
I hear you that it is frustrating that there's no great WebXR browser for phones that clip into Daydream! My daily driver is a Pixel XL and I feel the burn.

That said, the UI that we're building for Firefox Reality is focused entirely on in-headset use, and over time will become increasingly less usable for flat (what Joey called "desktop") mode. The UI widgets of Firefox Reality are bigger than flat widgets so that they work as targets for laser pointing or gaze pointing. The 3D tray ([described here](https://blog.mozvr.com/the-design-of-firefox-reality/)) will have all of the main app controls and won't be visible in flat mode. The dialogs that open won't appear in flat mode. So, Firefox Reality (as we're making it today) will simply not work in both modes. We'd have to do all of the hard work for a flat UI like [Focus](https://www.mozilla.org/en-US/firefox/mobile/) in addition to the main work of the in-headset UI.

For now, I'd rather we focused (har har har) on just the in-headset UI.

Funny story, it was actually a mistake that a flat mode exists in the APKs that we put out. We were using it for developer testing of the web renderer and initial UI setup and we forgot to turn it off. We fixed that with [this commit](https://github.com/MozillaReality/FirefoxReality/commit/c0c0b83a4a92478571092a8b0617ecb2aee529a1).

**Comment by TrevorFSmith** [comment]
A good idea. I'll add it to the list of possible future features.

**Comment by cvan** [comment]
to get many sites to work, I have had to manually toggle the UA from the Developer Options. given that the other VR browsers expose a Request Desktop Site option in obvious spots in the browser chrome UI, could we get a design spec for this and ideally prioritise as a P1 for v1.1?

**Comment by philip-lamb** [comment]
> to get many sites to work, I have had to manually toggle the UA from the Developer Options. given that the other VR browsers expose a Request Desktop Site option in obvious spots in the browser chrome UI, could we get a design spec for this and ideally prioritise as a P1 for v1.1?

Moved to new issue #962
