### ISSUE TITLE
The History view is dismissed when the background website finishes loading

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#1955]
**[Affected Versions]:**
- Firefox Reality version 5-32821846 RC1 (58b59br3)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Navigate to any website that takes longer to load. (e.g. amazon.com, yahoo.com, huffpost.com/)
2. Click the History button from the menu tray while the website is loading.
3. Observe the History view.

**[Expected results]:**
- The History view remains displayed.

**[Actual results]:**
- The History view is dismissed after the webpage from the background is loaded.

**[Additional Notes]:**
- This issue is not reproducible with the “Bookmarks” page.
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1aLGU6ZdGrofC0lMaNmW93YwaTmK86Ddp/view?usp=sharing).

**Comment by keianhzo** [comment]
We use navigation callbacks to dismiss the library panels when the user initiates a navigation event to avoid to explicitly add callbacks from all the possible navigation buttons (reload, home, back, forward, etc).

We have updated the navigation callback to use the faster `PageStart` instead of `onLocationChange` so this should be harder to reproduce now. In case it's not or we think we need faster feedback we can always add explicit callbacks from all the buttons.

**Comment by keianhzo** [comment]
I've added a PR for explicit panel dismiss. That should help speed up the panel dismiss after clicking on an item and also fix this issue.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 7 RC3 (7b66fb14) installed on the Oculus Go, Quest, HTC Vive Focus and Focus Plus headsets.
Now, the History view is not dismissed when the background website finishes loading.
