### ISSUE TITLE
show language names in their native language

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#1964]
make keyboards show their language name in their native language

**Comment by keianhzo** [comment]
@jvonitter The keyboard spacebar language string is displayed in the native language. If you choose the Polish keyboard it's displayed as "Polski" no matter what display language is the app using. Is not still happening in this PR as we don't have the translations for those strings yet (so it falls back to the English string) but will happen when they are translated. Let me know if this refers to some other thing otherwise I think is safe to close this.

**Comment by jvonitter** [comment]
nope, that's it. thank you!
