### ISSUE TITLE
[Intermittent] Youtube videos are not fully loaded after they are opened

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2016]
**[Affected Versions]:**
- Firefox Reality version 6-32902155 (93816a5a)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2
- Oculus Go - Android 7.1.2
- HTC Vive Focus - Android 7.1.2
- Lenovo Mirage Solo - Android 8.0.0

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Navigate on Youtube website.
2. Open a few suggested videos and observe the behavior.

**[Expected results]:**
- All videos are successfully opened and loaded.

**[Actual results]:**
- The videos are opened but not all are loaded and a black screen is displayed instead of the video and the video controls.

**[Notes]:**
- The video is successfully loaded if the page is refreshed. 
- Attached are a screen recording along with the logcat of the issue: 
	- Screen recording: [link](https://drive.google.com/open?id=1ggC9Gy-C23CbAIovlGv9KvUG48wBCBwy)
	- Logcat: [link](https://drive.google.com/open?id=1SNJ7TzkQHx4vov0DDGl8O4dtrHi9hOvG)

**Comment by heres-maria** [comment]
This issue is still reproducible on the Firefox Reality version 7 RC3 (7b66fb14) build, tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2).

Some videos still don't load and instead display a black screen. Clicking on the black screen will result in an error message being displayed inside its bounds. Attached are a [logcat file](https://drive.google.com/file/d/1cDtp7DpDPpypR02wy3CM3s5uLP03V6Rx/view?usp=sharing) of the issue and a [screenshot ](https://drive.google.com/file/d/1hMELhDdUwh693jbw31DnGEn4sxecKM8Y/view?usp=sharing)of the error message displayed.

**Comment by MortimerGoro** [comment]
I can't reproduce this issue. Could it be a intermittent Youtube server error? I've seen that error on Desktop too (rarely)

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with the latest Firefox Reality version 8-40030225 (e6f4ddab) from master.
Tested on the Oculus Quest (Android 7.1.1), Oculus Go (Android 7.1.2), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2).
