### ISSUE TITLE
move telemetry computation off client

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#2030]
We have too much telemetry computation at the client side. Ideally, we would upload raw data to the data server and do the computation there.

- [x] examine current telemetry and determine what need to be broken out
- [x] make those changes client-side
- [ ] update server-side logic so all the queries don't break
- [ ] update wiki and data review as needed

related to #1420

**Comment by daoshengmu** [comment]
Per https://github.com/MozillaReality/FirefoxReality/issues/1329#issue-455898315

When doing query data, I feel there are a few issues from our data collection.

> How many too-many-window dialogs happen / what percentage

It's weird `maxWindowsDialogEvent` isn't called currently. For the percentage, I guess we need to know if users can create a new window successfully or not (exceed the maximum number of windows). So far, we only have `maxWindowsDialogEvent` pings, therefore, we only can know how many `maxWindowsDialogEvent` are happened a day instead of the percentage.

> Frequency of window moves

It is not clear what unit we want to use for calculating the freq. Currently, we are using seconds to get the frequency. Is this what we want?

> Frequency of window resizes (and most common size if we can)

Same here, we are using seconds to get the frequency. Is this what we want?

> When a session is multi-window, what percentage of time is each position the active window
Average of how many windows are open at a time, per session

Regarding to `How many windows are open at a time?` I notice in `Open Window Mean` chart, the general window amount is 1.1. However, `How many windows open in time pct` tells us using two windows percentage is 91% They seem to be dismatch.

@keianhzo Can you take a look at this?

**Comment by daoshengmu** [comment]
Per #1477  Telemetry enable/disable.

This approach seems like can't make us know how many users enable/disable their telemetry in a day. Because the event only be sent when the change happens or the first time recognize users have disabled the telemetry. The possible solution we should send this event ping at the application launched instead of doing this only when changing the setting. @keianhzo

**Comment by daoshengmu** [comment]
> related to #1420

There is no connection with #1420. We are going to fix the telemetry that are made by #1443.

**Comment by daoshengmu** [comment]
- [ ] Remove curved mode

- [ ] Remove max windows reached

- [ ] Remove long press context

- [ ] Remove tray new window

- [ ] Frequency of window moves by sessions

- [ ] Frequency of window resizes by sessions

- [ ] Move `WINDOW_ACTIVE_TIME_PCT` percentage computation to the server side

- [ ] Move `OPEN_WINDOWS_TIME_PCT` percentage computation to the server side

**Comment by daoshengmu** [comment]
@keianhzo It looks like we have bugs here [1] [2]. We should use index[0,1,2] instead of `WindowPlacement[Left, Front, Right]`. The data are disorder now.

[1]
https://github.com/MozillaReality/FirefoxReality/blob/64da0a2d5c471c1766d5b538530337f5efcf9495/app/src/common/shared/org/mozilla/vrbrowser/telemetry/TelemetryWrapper.java#L681-L690
[2]
https://github.com/MozillaReality/FirefoxReality/blob/64da0a2d5c471c1766d5b538530337f5efcf9495/app/src/common/shared/org/mozilla/vrbrowser/telemetry/TelemetryWrapper.java#L486-L515
