### ISSUE TITLE
Ask for Data Review for the components use Glean for data collection.

### ISSUE THREAD

**Issue by daoshengmu** [MozillaReality/FirefoxReality#2115]
**Is your feature request related to a problem? Please describe.**
After Glean is enabled, there are a few components we are using will start to use Glean to send data. We need to ask for data reviews for these components.

**Describe the solution you'd like**
Following components are using the Glean SDK:

- [lib-crash](https://github.com/mozilla-mobile/android-components/tree/master/components/lib/crash#sending-crash-reports-to-glean)

- [engine-gecko](https://github.com/mozilla-mobile/android-components/tree/master/components/browser/engine-gecko-nightly#integration-with-the-glean-sdk), [storage sync](url)

- [Sync Storage](https://github.com/mozilla-mobile/android-components/tree/83ffd01184d22ec3ca9308bfba43ed6316018b4c/components/browser/storage-sync#before-using-this-component)

- [Firefox accounts](https://github.com/mozilla-mobile/android-components/tree/83ffd01184d22ec3ca9308bfba43ed6316018b4c/components/service/firefox-accounts#before-using-this-component)

After checked [versions.gradle](https://github.com/MozillaReality/FirefoxReality/blob/master/versions.gradle#L54). We are using *Sync Storage* and *Firefox Accounts*, so we need to ask data review for them.

**Additional context**
Once we done the data review, we also need to add the review results to our [Wiki](https://github.com/MozillaReality/FirefoxReality/wiki/Telemetry).

**Comment by daoshengmu** [comment]
# Request for data collection review form
 **All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.**
 
 1. **What questions will you answer with this data?**
 
 * Measure pings sent for `bookmark sync` and `history sync` in [Sync Storage](https://github.com/mozilla-mobile/android-components/tree/83ffd01184d22ec3ca9308bfba43ed6316018b4c/components/browser/storage-sync#before-using-this-component).
 
 2. **Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements?**
 
 * To measure how many times we sync bookmark and history.
  
 3. **What alternative methods did you consider to answer these questions? Why were they not sufficient?**
 
 * N/A
 
 4. **Can current instrumentation answer these questions?**
 
 * Currently no, as these are some of the first metrics we're recording
 
 5. **List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox [data c](https://wiki.mozilla.org/Firefox/Data_Collection)[ollection ](https://wiki.mozilla.org/Firefox/Data_Collection)[categories](https://wiki.mozilla.org/Firefox/Data_Collection) on the found on the Mozilla wiki.**
 
 * All data is Category 2.
 
 6. **How long will this data be collected?**
 
 Until we stop using Sync Storage component.
 
 7. **What populations will you measure?**

 * All release, beta, and nightly users with telemetry enabled.
 
 8. **Please provide a general description of how you will analyze this data.**
 
 * Glean
 
 9. **Where do you intend to share the results of your analysis?**
 
 * Only on Glean and with Firefox Reality team..

**Comment by daoshengmu** [comment]
# Request for data collection review form
 **All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.**
 
 1. **What questions will you answer with this data?**
 
 * Measure pings sent for `bookmark sync` and `history sync` in [Firefox accounts](https://github.com/mozilla-mobile/android-components/tree/83ffd01184d22ec3ca9308bfba43ed6316018b4c/components/service/firefox-accounts#before-using-this-component).
 
 2. **Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements?**
 
 * Firefox Account's telemetry system is based on [sync-telemetry](https://github.com/mozilla-mobile/android-components/blob/master/components/support/sync-telemetry/docs/metrics.md) to measure how many times we sync bookmark and history.
  
 3. **What alternative methods did you consider to answer these questions? Why were they not sufficient?**
 
 * N/A
 
 4. **Can current instrumentation answer these questions?**
 
 * Currently no, as these are some of the first metrics we're recording
 
 5. **List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox [data c](https://wiki.mozilla.org/Firefox/Data_Collection)[ollection ](https://wiki.mozilla.org/Firefox/Data_Collection)[categories](https://wiki.mozilla.org/Firefox/Data_Collection) on the found on the Mozilla wiki.**
 
 * All data is Category 2.
 
 6. **How long will this data be collected?**
 
 Until we stop using Firefox Accounts component.
 
 7. **What populations will you measure?**

 * All release, beta, and nightly users with telemetry enabled.
 
 8. **Please provide a general description of how you will analyze this data.**
 
 * Glean
 
 9. **Where do you intend to share the results of your analysis?**
 
 * Only on Glean and with Firefox Reality team..

**Comment by daoshengmu** [comment]
Per #1854, we start to enable Glean, so we need additional data reviews for other components.

**Comment by daoshengmu** [comment]
@harraton Please help do the data reviews of  [Sync Storage.](https://github.com/MozillaReality/FirefoxReality/issues/2115#issuecomment-548611485)
and [Firefox accounts](https://github.com/MozillaReality/FirefoxReality/issues/2115#issuecomment-548613039).

**Comment by daoshengmu** [comment]
Wiki page is updated, https://github.com/MozillaReality/FirefoxReality/wiki/Telemetry#new-telemetry-system---glean.

**Comment by harraton** [comment]
> # Request for data collection review form
> 
> **All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.**
> 
>     1. **What questions will you answer with this data?**
> 
> 
>     * Measure pings are sent for `bookmark sync` and `history sync` in [Sync Storage](https://github.com/mozilla-mobile/android-components/tree/83ffd01184d22ec3ca9308bfba43ed6316018b4c/components/browser/storage-sync#before-using-this-component).
> 
> 
>     1. **Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements?**
> 
> 
>     * Sync Storage's telemetry system is based on [sync-telemetry](https://github.com/mozilla-mobile/android-components/blob/master/components/support/sync-telemetry/docs/metrics.md) to measure how many times we sync bookmark and history.
> 
> 
>     1. **What alternative methods did you consider to answer these questions? Why were they not sufficient?**
> 
> 
>     * N/A
> 
> 
>     1. **Can current instrumentation answer these questions?**
> 
> 
>     * Currently no, as these are some of the first metrics we're recording
> 
> 
>     1. **List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox [data c](https://wiki.mozilla.org/Firefox/Data_Collection)[ollection ](https://wiki.mozilla.org/Firefox/Data_Collection)[categories](https://wiki.mozilla.org/Firefox/Data_Collection) on the found on the Mozilla wiki.**
> 
> 
>     * All data is Category 2.
> 
> 
>     1. **How long will this data be collected?**
> 
> 
> Until we stop using Sync Storage component.
> 
>     1. **What populations will you measure?**
> 
> 
>     * All release, beta, and nightly users with telemetry enabled.
> 
> 
>     1. **Please provide a general description of how you will analyze this data.**
> 
> 
>     * Glean
> 
> 
>     1. **Where do you intend to share the results of your analysis?**
> 
> 
>     * Only on Glean and with Firefox Reality team..


Data Review Form (to be filled by Data Stewards)

- Is there or will there be documentation that describes the schema for the ultimate data set in a public, complete, and accurate way? 

Documentation is available here: [https://github.com/MozillaReality/FirefoxReality/wiki/Telemetry#new-telemetry-system---glean](https://github.com/MozillaReality/FirefoxReality/wiki/Telemetry#new-telemetry-system---glean)

- Is there a control mechanism that allows the user to turn the data collection on and off?
Yes, people will be able to opt-out in the Firefox Reality settings. 

- If the request is for permanent data collection, is there someone who will monitor the data over time?
Yes. @daoshengmu and @jvonitter . 


- Using the category system of data types on the Mozilla wiki, what collection type of data do the requested measurements fall under?
Category 2

- Is the data collection request for default-on or default-off?
Default-on.

- Does the instrumentation include the addition of any new identifiers (whether anonymous or otherwise; e.g., username, random IDs, etc. See the appendix for more details)?
No

- Is the data collection covered by the existing Firefox privacy notice? 
Covered by Firefox Reality privacy statement. 


- Does there need to be a check-in in the future to determine whether to renew the data? (Yes/No) (If yes, set a todo reminder or file a bug if appropriate)**
No

- Does the data collection use a third-party collection tool? If yes, escalate to legal.
No.

**Comment by harraton** [comment]
> # Request for data collection review form
> 
> **All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.**
> 
>     1. **What questions will you answer with this data?**
> 
> 
>     * Measure pings are sent for `bookmark sync` and `history sync` in [Firefox accounts](https://github.com/mozilla-mobile/android-components/tree/83ffd01184d22ec3ca9308bfba43ed6316018b4c/components/service/firefox-accounts#before-using-this-component).
> 
> 
>     1. **Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements?**
> 
> 
>     * Firefox Account's telemetry system is based on [sync-telemetry](https://github.com/mozilla-mobile/android-components/blob/master/components/support/sync-telemetry/docs/metrics.md) to measure how many times we sync bookmark and history.
> 
> 
>     1. **What alternative methods did you consider to answer these questions? Why were they not sufficient?**
> 
> 
>     * N/A
> 
> 
>     1. **Can current instrumentation answer these questions?**
> 
> 
>     * Currently no, as these are some of the first metrics we're recording
> 
> 
>     1. **List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox [data c](https://wiki.mozilla.org/Firefox/Data_Collection)[ollection ](https://wiki.mozilla.org/Firefox/Data_Collection)[categories](https://wiki.mozilla.org/Firefox/Data_Collection) on the found on the Mozilla wiki.**
> 
> 
>     * All data is Category 2.
> 
> 
>     1. **How long will this data be collected?**
> 
> 
> Until we stop using Firefox Accounts component.
> 
>     1. **What populations will you measure?**
> 
> 
>     * All release, beta, and nightly users with telemetry enabled.
> 
> 
>     1. **Please provide a general description of how you will analyze this data.**
> 
> 
>     * Glean
> 
> 
>     1. **Where do you intend to share the results of your analysis?**
> 
> 
>     * Only on Glean and with Firefox Reality team..

Data Review Form (to be filled by Data Stewards)

- Is there or will there be documentation that describes the schema for the ultimate data set in a public, complete, and accurate way? 

Documentation is available here: [https://github.com/MozillaReality/FirefoxReality/wiki/Telemetry#new-telemetry-system---glean](https://github.com/MozillaReality/FirefoxReality/wiki/Telemetry#new-telemetry-system---glean)

- Is there a control mechanism that allows the user to turn the data collection on and off?
Yes, people will be able to opt-out in the Firefox Reality settings. 

- If the request is for permanent data collection, is there someone who will monitor the data over time?
Yes. @daoshengmu and @jvonitter . 


- Using the category system of data types on the Mozilla wiki, what collection type of data do the requested measurements fall under?
Category 2

- Is the data collection request for default-on or default-off?
Default-on.

- Does the instrumentation include the addition of any new identifiers (whether anonymous or otherwise; e.g., username, random IDs, etc. See the appendix for more details)?
No

- Is the data collection covered by the existing Firefox privacy notice? 
Covered by Firefox Reality privacy statement. 


- Does there need to be a check-in in the future to determine whether to renew the data? (Yes/No) (If yes, set a todo reminder or file a bug if appropriate)**
No

- Does the data collection use a third-party collection tool? If yes, escalate to legal.
No.

**Comment by harraton** [comment]
> @harraton Please help do the data reviews of [Sync Storage](https://github.com/MozillaReality/FirefoxReality/issues/2115#issuecomment-548611485)
> and [Firefox accounts](https://github.com/MozillaReality/FirefoxReality/issues/2115#issuecomment-548613039).

Data collection approved.
