### ISSUE TITLE
Transparent background on window top UI

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#2116]
## Configuration

Firefox Reality version: 6
Firefox Reality build ID: b84dffb3efea7a730e1af497e9d2fe563231d688

Hardware: Quest

## Steps to Reproduce

1. Open three windows.
2. Swap middle and left window.

## Current Behavior

![org mozilla vrbrowser-20191031-114839](https://user-images.githubusercontent.com/3066/67982624-4b889880-fbe0-11e9-9fea-6dfd3ddd9afa.jpg)

## Expected Behavior

Left arrow background should not be transparent.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue with the latest Firefox Reality version 6 RC2 (67257542) installed on the Oculus Go, Quest, HTC Vive Focus and Focus Plus headsets.
Now, the multiwindow controls have a solid color background in normal browsing mode.
The issue is still reproducible in Private Browsing mode.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 6 RC3 (1e9e4a85) installed on the Oculus Go, Quest, HTC Vive Focus and Focus Plus headsets.
Now, the multiwindow controls have a solid color background in normal browsing mode and in Private Browsing mode.
