### ISSUE TITLE
The “Sign Into Account To Sync”, “Sync” or “Sync Settings” buttons are not displayed on an empty History view

### ISSUE THREAD

**Issue by heres-maria** [MozillaReality/FirefoxReality#2141]
**[Affected Versions]:**
- Firefox Reality version 6 RC2 (67257542)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.
 
**[Steps to reproduce]:**
1. Click the "History" button from the tray.
2. Click the “Clear History” button and select the “Everything” option.
4. Click “Clear Now” button and observe the “Sign Into Account To Sync” button.

**[Expected results]:**
- The button remains displayed.

**[Actual results]:**
- The button is no longer displayed.

**[Notes]:**
- This issue is also reproducible if the user is logged in an FxA account as the “Sync” or “Sync Settings” buttons, depending on the settings that are set for the account, are also not displayed.
- The “Last synced...” text is also not displayed. 
- Attached is a screenshot of the issue.
![Mon11-04-2019_18-20-23 74](https://user-images.githubusercontent.com/53752296/68140127-f330fe00-ff33-11e9-9898-0bb38d9a105a.png)

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with the Firefox Reality 6-33100022 RC3 (1e9e4a85) build. Now the “Sign Into Account To Sync”, “Sync” or “Sync Settings” buttons are displayed on the empty History page.
However, a new behavior occurs when resizing the window to a "0.5x" size, where the empty History page is not responsive. This issue is documented in bug: #2174.
Tested on the Oculus Quest (Android 7.1.1), Oculus Go (Android 7.1.2), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2) devices.
