### ISSUE TITLE
The history feeds are NOT synced with an FxA account

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#2150]
**[Affected Versions]:**
- Firefox Reality version 6 RC2 (67257542)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.
- Make sure an FxA account with a history feed is logged in.

**[Steps to reproduce]:**
1. Click the History button from the menu tray.
2. Click the “Sync” button and wait for syncing to be done.
3. Observe the displayed history feeds.

**[Expected results]:**
- All the history feed of the FxA account is displayed.

**[Actual results]:**
- Only the history feed of the device is displayed.

**[Notes]:**
- The history feed from the device is NOT synced with the FxA account.

**Comment by keianhzo** [comment]
@Softvision-GeluHaiduc I think this is might be the expected behavior for FxA. 

A couple of things to keep in mind while testing FxA:
1) If you have never synced (first launch) it just gets it all, so you should see all the remote history/bookmarks after it finishes syncing.
2) New history items from other devices will be synced when those devices sync, so the fact that you add something to bookmarks or update your history record in another device, doesn't mean that you'll see it in FxR even if you force a sync in FxR. If you want to see the remote records in FxR you need to either wait until the device syncs or force a explicit sync on that device.
3) If you clear your local history, FxA won't deliver the deleted history records anymore, it considers that you don’t want to see the them in this device so you will only get future records. The only way of getting those records again is reinstalling.
4) If you logout from your FxA account you'll still have the remote bookmarks and history items unless you clear history (you can currently clear bookmarks in FxR)

**Comment by Softvision-GeluHaiduc** [comment]
I managed to reproduce the issue following these steps:
1. Log into an FxA account.
2. Clear the history.
3. On another device with the same FxA account logged in navigate on a few websites and then sync the account.
4. On the VR device go to settings and sync the FxA account.
5. Dismiss the settings and go to the history view.
6. Observe the history feeds.

None of the NEW history feeds are synced with the VR device.
Attached the logcat file of the issue [here](https://drive.google.com/open?id=1anJeQwUWGjd_sLghKXtks0zFR0qr2gDX) and the screen recording [here](https://drive.google.com/open?id=1syH8jX8PKgYaG_0GjCP4GN2Huil1pvsF).
As can be seen in the screen recording the issue is intermittent now.

**Comment by Softvision-GeluHaiduc** [comment]
I tried to reproduce this issue with the latest Firefox Reality version 7 RC6 (b01367aa) installed on the Oculus Quest headset, but I didn’t manage to reproduce it with any scenario.
