### ISSUE TITLE
aframe.io shows differently between Oculus Go and Vive Focus

### ISSUE THREAD

**Issue by daoshengmu** [MozillaReality/FirefoxReality#218]
Hardware: Oculus Go and Vive Focus

Steps to Reproduce:
1. Go to https://aframe.io.
2. We will be redirected to https://aframe.io/examples

Actual Behavior:
In Oculus Go, we have <- and -> buttons on the bottom of the page to let us choose other examples. But in Vive Focus, it doesn't show the <- and -> buttons. It looks like a CSS issue.

Expected Behavior:
In aframe.io, we should show the same result on both of them.

Recommendation:
I prefer it should have the <- and -> buttons to make users choose examples.

**Comment by bluemarvin** [comment]
This is not a CSS issue but due to the fact that the Focus reports a smaller DPI than the the Go so less content fits in the window for the Focus. We have a plan to create a virtual device DPI so content looks more consistent between the various platforms. This will require a GeckoView update before we can make the fix in FxR

**Comment by avrignaud** [comment]
Shouldn't we leave this open so we can track issue and fix when GV has updated?

**Comment by bluemarvin** [comment]
Sure.

**Comment by cpeterso** [comment]
I filed a GeckoView bug to track the proposed virtual device DPI units:

https://bugzilla.mozilla.org/show_bug.cgi?id=1477837

**Comment by philip-lamb** [comment]
Implemented in https://github.com/MozillaReality/FirefoxReality/commit/ce93750.
