### ISSUE TITLE
Consider better intro and CTA in the accounts flow

### ISSUE THREAD

**Issue by larsbergstrom** [MozillaReality/FirefoxReality#2218]
At the new login screen where you are modally prompted to sign up for FxA, can we talk about the benefits? e.g., "Tired of entering URLs by hand in your headset? Sign up for FxA and send a URL from any mobile or desktop device with Firefox straight to a new tab in your headset!"

Also at the end after you've finished logging in it leaves you at a kind of BLAH screen that just says "done, sign up on your phones now!" It would be nice to have a CTA and some instructions (is there a page in SUMO?) that tells people how to use Send to Device from their phone/desktop device.

**Comment by jvonitter** [comment]
I've updated the text on the modal since it was actually not true (said you can sync a lot more than you can). See #2239 for the new text.

Going to keep this open for the second point, however. We don't control that page (FxA team does) but we do want to work with them on getting all their pages to be better in VR.
