### ISSUE TITLE
Close icon ( x ) above browser window in Private Browsing Moee is too small

### ISSUE THREAD

**Issue by thenadj** [MozillaReality/FirefoxReality#222]
Hardware:
[Bug-6 Incorrect Exit Icon in PB Mode_001.pdf](https://github.com/MozillaReality/FirefoxReality/files/2214748/Bug-6.Incorrect.Exit.Icon.in.PB.Mode_001.pdf)

REPRODUCE: Home >> Private Browsing Mode
CURRENT BEHAVIOR: The wrong X icon is used, must be larger
EXPECT: The icon to be proportionally the same size as the other icons on the bottom of the UI
RECOMMENDATION: Follow icon design from UIS-11 and use icon-exit-window

**Comment by cvan** [comment]
First of all, I have to say: very impressive work on the designs, and these reports, and the personas. Fantastic work!

For this issue, can the × be removed? The modality is confusing, to me at least. Can the _Private Browsing_ icon in the Tray be more pronounced so that you can toggle the icon to go in and out of _Private Browsing_?

I'm likely missing the user flow here. So apologies if I'm missing something.

**Comment by thenadj** [comment]
We are usability testing the difference between the ( x ) button and the toggle in the tray and will make design adjustments based on the feedback we get.

**Comment by cvan** [comment]
gotcha – thanks, @MortimerGoro and @thenadj. can we add text to whatever icon that triggers exiting/closing/ending Private Browsing? can we add a label (near whichever icon is used) with the text `End Session`/`Exit Private Browsing`/etc.?

**Comment by thenadj** [comment]
@cvan Adding text label is something we thought of but we are also trying to keep the UI as clean and simple as possible. After more usability feedback we'll revisit this and see what makes most sense to be as clear and yet clean as possible.
