### ISSUE TITLE
The Context menu is not displayed when clicking the “Select all” option while not on the first view of the page

### ISSUE THREAD

**Issue by heres-maria-sv-inactive** [MozillaReality/FirefoxReality#2229]
**[Affected Versions]:**

- Firefox Reality Firefox Reality 6 RC5 (33a031c7) build.

**[Affected Platforms]:**

- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**

- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Navigate to a website with scrollable content (e.g. "https://en.wikipedia.org/wiki/Main_Page").
2. Scroll down the page until the first view is no longer visible.
3. Long press on a static text.
4. Click "Select All".
5. Observe the Context menu.

**[Expected results]:**
- The Context menu is displayed on the visible view.

**[Actual results]:**
- The Context menu is not displayed on the visible view.

**[Notes]:**
- The Context menu is displayed above the active window if the user scrolls up to the first view.
- Attached is a screen recording of the issue: 
![context menu select all](https://user-images.githubusercontent.com/53752296/68608566-ee33f780-04bb-11ea-8aac-e2693bf13cfe.gif)

**Comment by daoshengmu** [comment]
I can't reproduce it with the current master  Firefox Reality 6 (510b1b50) build.

**Comment by heres-maria** [comment]
I looked further into this issue using Firefox Reality version 6 RC5 (33a031c7) on Oculus Go and found the following:

1. The issue is not reproducible on most web pages and is highly intermittent depending on the user agent or other factors:
- I was only able to reproduce it on Wikipedia Foundation websites: Wikipedia, [Wikiversity](https://en.m.wikiversity.org/wiki/Wikiversity:Main_Page), [Wiktionary](https://fr.m.wiktionary.org/wiki/Wiktionnaire:Page_d’accueil), etc.
- Most of the main pages of these websites (e.g. [this](https://en.m.wikipedia.org/wiki/Main_Page)), regardless of language, seem to display this issue if the user agent is set to “Mobile” or “VR”, and some other subpages do as well, but not all - [this one](https://it.m.wikipedia.org/wiki/Aiuto:Come_registrarsi) does, for example. 
- The main pages also seem to display this issue intermittently if the user agent is set to “Desktop”. It took me between 2 and 49 tries to be able to reproduce it.

2. There is a bug filed in [Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1466839) for Firefox for Android for this issue as well.

3. Trying to reproduce this on [YouTube](https://www.youtube.com/) while using “VR” and “Mobile” user agent modes resulted in the Context menu being displayed much higher than the upper limit of the window (see the attached screenshot).

![Tue11-12-2019_10-35-20 55](https://user-images.githubusercontent.com/53752296/68671139-49ff8e80-0557-11ea-9cf9-338ffecf3631.png)

**Comment by MortimerGoro** [comment]
I did some research and it seems related to a GV bug. I created this issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1595898

@jvonitter I'm changing the milestone to v7 because I don't think we are on time to wait for and land a new GV

**Comment by jvonitter** [comment]
@MortimerGoro thank you!
