### ISSUE TITLE
Hide Tray and enlarge icon in Focus Mode

### ISSUE THREAD

**Issue by thenadj** [MozillaReality/FirefoxReality#226]
Hardware: Oculus Go
REPRODUCE: Home > Click on Focus Mode Button
CURRENT BEHAVIOR: Tray is still visible, Resize Mode Icon is not large enough, Exit focus mode button is the incorrect icon
EXPECTATION: Tray should disappear, Resize Mode icon should be consistent sizing as the other UI in regular mode, Exit focus mode button should have updated icon icon-focus-etc
RECOMMENDATION: Hide the tray while in focus mode, Make resize mode icon 25% larger, Update exit focus mode button icon with SVG attached
[Bug-13 Focus Mode Hide Tray Enlarge Icon_001.pdf](https://github.com/MozillaReality/FirefoxReality/files/2214776/Bug-13.Focus.Mode.Hide.Tray.Enlarge.Icon_001.pdf)

**Comment by bluemarvin** [comment]
@keianhzo The tray hiding issue is from the error:

07-20 12:41:09.176 3899-3899/org.mozilla.vrbrowser E/VRB: Function: 'SetTrayVisible' not called on render thread.

We discussed.

**Comment by keianhzo** [comment]
@thenadj @bluemarvin 

- Tray is still visible
This shouldn't be a problem anymore now that we have the UI tray. I actually verified this case when implementing. Should we close this one?

- Resize Mode Icon is not large enough
Will fix this.

- Exit focus mode button is the incorrect icon
Fixed by #250 (closes #225)
