### ISSUE TITLE
The "Pop-Ups Permissions" entries do not have a hover or click state

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#2296]
**[Affected Versions]:**
- Firefox Reality version 7 RC1 (b772e6d7)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The Firefox Reality browser is opened.
- Make sure the "Block Pop-Up Windows" option is enabled.
- Make sure the "Pop-Ups Permissions" list has at least 2 entries.

**[Steps to reproduce]:**
1. Go to Settings -> Privacy & Security.
2. Click the “Advanced” button for the “Block Pop-Up Windows” option.
3. Using the controller hover the pointer over one of the sites from the list.
4. Observe the behaviour.
5. Using the controller click and hold one of the sites from the list.
6. Observe the behaviour

**[Expected results]:**
Step 4. The "Pop-Ups Permissions" entries container are highlighted with an iron color.
Step 6. The "Pop-Ups Permissions" entries container are highlighted with a void color.

**[Actual results]:**
Step 4. The "Pop-Ups Permissions" entries do not have a hover effect.
Step 6. The "Pop-Ups Permissions" entries do not have a click effect and the dismiss button disappears.

**[Notes]:**
- Attached a screen recording of the issue [here](https://drive.google.com/open?id=1OF66kuxt9AZGVfnUqYttvCuT8CxKW86S).

**Comment by jvonitter** [comment]
related to #2297 
align the button style to the rest of the UI.

**Comment by keianhzo** [comment]
@jvonitter I think the current UI spec implementation is more consistent than the one in the spec. We are only using row hover/pressed style states when the row is actionable (history/bookmarks) and we don't use them in case it is not (ie. Preferred/available Display Languages lists UIS-80_Set_Preferred_Website_Language_006) because there is a button that triggers the action (add/delete). I believe this list should behave the same as the preferred languages one.

If we want to add row state styles to this dialog we probably should add it to that one too and also think if we need the add/delete icon hover zoom effect as it gives the impression that is the button who triggers the action or we just want to show it on hover so the user knows that clicking on the row will trigger that action.

**Comment by jvonitter** [comment]
I think this one - https://trello.com/c/fyOLDneE/442-de-70-dialog-menu-item-interaction - is the correct one to follow. It unified both places where we have row interactions.

**Comment by keianhzo** [comment]
@jvonitter So the default action for popups when clicking on the row would be delete? what would be the default action for a preferred language row when clicking on the row? I guess also delete? In case there is no action, isn't it confusing that you have a pressed state for something that doesn't trigger any action?

**Comment by keianhzo** [comment]
@jvonitter For what I see in SL-7_Components_Dialogs_012.pdf this is stayed as it is right now so I'll tag it to be closed by https://github.com/MozillaReality/FirefoxReality/pull/2468
