### ISSUE TITLE
The up and down arrows for the Preferred Website Language are overlapping

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2421]
**[Notes]:**
- If the arrows are clicked the language is only be moved up

**[Affected Versions]:**
-  Firefox Reality version 7 RC6 (b01367aa)

**[Affected Platforms]:**
- HTC Vive Focus Plus - Android 7.1.2
- Oculus Quest - Android 7.1.1

**[Prerequisites]:**
- The Firefox Reality browser is opened.

**[Steps to reproduce]:**
1. Open the "Language" card from Settings.
2. Click the "Edit" button for the "Display Website Language" option.
3. Hover over the languages displayed on the right side.
4. Click the "+" button for 2 languages to add them to the list on the left.
5. Hover over the languages on the middle from the list on the left.
6. Observe the right side of the language.

**[Expected results]:**
- The Up and Down arrows are correctly displayed.

**[Actual results]:**
- The Up and Down arrows are overlapping.

**[Additional Notes]:**
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1w8DIz84VisZAiKS1LcRfy4s5INik-r8Q).

**Comment by heres-maria** [comment]
I have verified this issue is no longer reproducible with the latest Firefox Reality version 8-33570852 (d3f0a6a1) build. The arrows no longer overlap each other, but they do overlap the language names and have different colors. Issue #2526 has been logged to address this.
Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2).
