### ISSUE TITLE
Opened prompts are dismissed or others are opened in the background while logging into the FxA account

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2449]
**[Affected Versions]:**
- Firefox Reality version 7 RC6 (b01367aa)
- Have a valid FxA account.

**[Affected Platforms]:**
- HTC Vive Focus Plus - Android 7.1.2
- Oculus Quest - Android 7.1.1

**[Prerequisites]:**
- The Firefox Reality browser is opened.

**[Steps to reproduce]:**
1. Click the Settings button from the tray.
2. Click the "Sign Into Account" card.
3. Login into your account.
4. While the login is performed click the Settings button from the tray.
5. Observe the behavior.

**[Expected results]:**
- The Settings prompt remains displayed.
OR
- The Settings prompt is dismissed and the Manage Account prompt is displayed instead.

**[Actual results]:**
- The Settings prompt is dismissed and the Manage Account prompt is NOT displayed.

**[Notes]:**
- If the "Tabs View" prompt is triggered while logging into a FxA account, the Manage account is briefly displayed over the "Tabs View" prompt. If the Tabs View prompt is dismissed the Settings prompt is displayed.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=12_VL7LfddpUe6Tq9oPZDIOxLBE_Qk_5C)

**Comment by heres-maria** [comment]
This issue is partially fixed in the latest Firefox Reality version 8-33580833 (777a0ae00) build. 
While the "Settings" view is dismissed and the "Manage Account" prompt is displayed at login, the behavior described in the first note is still reproducible, though slightly differently:

If the "Tabs View" prompt is triggered while logging into an FxA account, "Tabs View" remains displayed, with "Manage Account" not being displayed at all. If the user clicks anywhere inside the "Tabs View" window, the "Settings" menu is displayed.

Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2).

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 8-40100049 (1500ba50) installed on the Oculus Go, Quest, HTC Vive Focus and Focus Plus headsets.
Now, the opened prompts are dismissed while logging into the FxA account.
