### ISSUE TITLE
The video projection menu doesn’t dismiss when clicking inside the video in theater mode

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#2452]
**[Affected Versions]:**
- Firefox Reality version 8-33431308 (aee8a16e)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The Firefox Reality browser is opened.

**[Steps to reproduce]:**
1. Navigate to any 2d video and enter theater mode.
2. Click the “Video Projection” button in the theater mode controls.
3. Using the controller click inside the video. (but not inside the video projection menu)
4. Observe the behavior.

**[Expected results]:**
- The “Video Projection” menu is dismissed.

**[Actual results]:**
- The “Video Projection” menu is not dismissed.

**[Notes]:**
- The issue is not reproducible by clicking outside the video.
- Tracked by #1760.
- Attached a screen recording of the issue [here](https://drive.google.com/open?id=1VDzA_ZzZCH2yqvUTTBvh2UkfNsPLni6g).

**Comment by heres-maria** [comment]
After the implementation of the new YouTube layout, this issue is also reproducible for the rest of the YouTube page displayed in theater mode. 
Clicking on any part of the page (e.g. comment section) will not dismiss the "Video Projection" menu. Changing the video while in theater mode will also keep the menu displayed.
Tested on the 8-33611921 (67403bf2) build of Firefox Reality using HTC Vive Focus Plus (Android 7.1.2) and Oculus Quest (Android 7.1.1).

**Comment by MortimerGoro** [comment]
This is already fixed in master

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 9-40240151 (7e03c944) installed on the Oculus Go, Quest, HTC Vive Focus and Focus Plus headsets.
Now, the video projection menu is dismissed when clicking inside the video in theater mode.
