### ISSUE TITLE
youtube videos are defaulting to low-res

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#2457]
From @larsbergstrom 12/11/19 : YouTube videos are playing at 1440p don't adapt even when higher resolutions are available. 

Expected: We should be defaulting to the highest available quality via our custom YouTube extension.

@bluemarvin suggested we check the labels we're using for quality (`prefs.qualityLabels`)

needed by #1760

**Comment by philip-lamb** [comment]
The webext currently defaults to 1440p. See https://github.com/MozillaReality/FirefoxReality/blob/master/app/src/main/assets/web_extensions/webcompat_youtube/main.js#L31  The original develop intended to allow for auto quality (see https://github.com/MozillaReality/FirefoxReality/blob/master/app/src/main/assets/web_extensions/webcompat_youtube/main.js#L213) but this may not have been fully implemented.

**Comment by larsbergstrom** [comment]
Would it potentially be possible to try to default higher on higher-end devices like the quest? Some of the newer awesome content that has been featured has resolutions up to ~4k and it looks *amazing* if you get it!

Further, due to our auto-set/enter/mode-set flow, it's actually quite tricky to exit the play and pop up the quality change dialog to change to a higher resolution (clicking on anything in the display region can easily dismiss all dialogs and pop you into the correct 180/360 mode).

**Comment by MortimerGoro** [comment]
@larsbergstrom yes, that's something I wanted to do too :) I'm going to refactor Youtube WebExtension to add that behavior and other fixes
