### ISSUE TITLE
[Intermittent] Videos on YouTube are not loaded and the video controls do not appear

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#2460]
**[Affected Versions]:**
- Firefox Reality version 8-33452219 (bfee54ee)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The Firefox Reality browser is opened.

**[Steps to reproduce]:**
1. Navigate to any page with a video on youtube. (e.g. [Raw Run](https://www.youtube.com/watch?v=H5Q-GtGIp44) or [Found iPad Underwater](https://www.youtube.com/watch?v=F11XRuHml-I) )
2. Observe the behavior.

**[Expected results]:**
- The page is loaded, the video thumbnail is displayed and the video controls appear.

**[Actual results]:**
- The page is loaded, the video thumbnail is blank and the video controls do not appear.

**[Notes]:**
- If the page is refreshed the video is loaded and the controls appear.
- Needed by #1760.
- Attached a screen recording of the issue on the HTC device [here](https://drive.google.com/open?id=1Cl9GswcwAXWNm4SkFdFQVqwPvCobkXyf).
- Attached a screen recording of the issue on the Oculus device [here](https://drive.google.com/open?id=1wyhZwUwfyecAVXxs-JXIvUn9vNmckgqJ).

**Comment by jvonitter** [comment]
@MortimerGoro same with this one as the other intermittent one. probably not enough information to go on for this bug, but keep it in mind as you're working on all the other.

**Comment by MortimerGoro** [comment]
This should be already fixed

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and is no longer reproducible with the latest Firefox Reality version 8-40081245 (34c12f5) build. I was not able to reproduce this issue after opening multiple videos.
Given the fact that this issue is intermittent I think that is safe to mark it as verified fixed and just log a new one if the issue is encountered in the future.
Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2).
