### ISSUE TITLE
Immersive video transport controls widget is cut at the bottom

### ISSUE THREAD

**Issue by keianhzo** [MozillaReality/FirefoxReality#2497]
## Configuration

Firefox Reality version: 33512130
Firefox Reality build ID: 8dd6bff

Hardware: All

## Steps to Reproduce

1. Open an immersive video
2. Enter full screen mode
3. See the transport controls

## Current Behavior

The transport controls are cut at the bottom

## Expected Behavior

They should be completely displayed

## Context

![org mozilla vrbrowser dev-20191218-144051](https://user-images.githubusercontent.com/837184/71093211-0d076700-21a9-11ea-9b40-cde6d3a48d1c.jpg)

**Comment by heres-maria** [comment]
I have verified this issue is no longer reproducible with the latest Firefox Reality version 8-40061107 (afa52ff0) build. The media controls widget is no longer cut at the bottom.
Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2).
