### ISSUE TITLE
Youtube video controls are not hidden in fullscreen mode

### ISSUE THREAD

**Issue by keianhzo** [MozillaReality/FirefoxReality#2502]
## Configuration

Firefox Reality version: 33452219
Firefox Reality build ID: bfee54e

Hardware: All

## Steps to Reproduce

1. Open Youtube
2. Click on a video and play it
3. Enter full screen
4. Move the pointer outside the video

## Current Behavior

The video controls are displayed even if the video is not focused

## Expected Behavior

The video controls should dissappear when the pointer is outside the video area same as in non-fullscreen mode.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by heres-maria** [comment]
I have verified this issue is no longer reproducible with the latest Firefox Reality version 8-40061107 (afa52ff0) build. The video controls are not displayed in theater mode when the pointer is outside the video area - as long as the video is not paused.
Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2).
