### ISSUE TITLE
[L10n] The strings from the "Display" menu are overlapping or not displayed

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2536]
**[Affected Versions]:**
- Firefox Reality version 8-33550026 (933fcd51)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.
- The app's language is set in "Polish".

**[Steps to reproduce]:**
1. Click the Settings button.
2. Click the "Display" card.
3. Observe the "Homepage" and "Foveation Level" options.

**[Expected results]:**
- The UI is correctly rendered.

**[Actual results]:**
- The "Firefox Reality Home (Default) string is not entirely displayed.
AND
- The "Foveation Level (App)" string overlaps with the first radio button.

**[Additional Notes]:**
- I was only able to reproduce this issue with the "ES", "PL" and "RU" locales.
- Related to #2344.
- Attached is a screenshot of the issue:
![DisplayMenu](https://user-images.githubusercontent.com/40061643/71370033-467b1080-25b5-11ea-8aae-2ab324dfe940.png)

**Comment by heres-maria** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 9-40240151 (7e03c94) build. The Home option now displays an ellipsis at the end and the Foveation option no longer overlaps the first button.
Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2).
