### ISSUE TITLE
[L10n] The name of the "Privacy & Security" card from "Settings" has no padding

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2539]
**[Affected Versions]:**
- Firefox Reality version 8-33550026 (933fcd51)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.
- The app's language is set in "Russian".

**[Steps to reproduce]:**
1. Click the Settings button.
2. Observe the name of the "Privacy & Security" card.

**[Expected results]:**
- The name is correctly displayed inside the card.

**[Actual results]:**
- The name has no padding.

**[Additional Notes]:**
- I was only able to encounter this issue on Oculus Quest with the "FI" and "SE" locales.
- I was only able to encounter this issue on HTC Vive Focus Plus with the "NO" and "RU" locales.
- Attached is a screenshot of the issue:
![Untitled](https://user-images.githubusercontent.com/40061643/71372364-ce184d80-25bc-11ea-9106-69014aa77de3.png)

**Comment by jvonitter** [comment]
related to #2537 and #2538

**Comment by heres-maria** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 9-40240151 (7e03c944) build. All of the four now have enough padding.
Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2).
