### ISSUE TITLE
The play/pause button is not displayed for videos on certain websites

### ISSUE THREAD

**Issue by heres-maria** [MozillaReality/FirefoxReality#2548]
**[Affected Versions]:**
- Firefox Reality version 8-33580833 (777a0ae00)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is open.

**[Steps to reproduce]:**                                        
1. Go to [W3Schools’ HTML5 video page](https://www.w3schools.com/html/html5_video.asp) and play the video.
2. Open a new window from the tray.
3. Observe the initial window.

**[Expected results]:**
-  The play/pause button is displayed.

**[Actual results]:**
- The play/pause button is not displayed.

**[Notes]:**
- This issue is also reproducible for: [videos on BBC](https://www.bbc.com/news/video_and_audio/headlines/50922774/kazakhstan-plane-crash-bek-air-plane-comes-down-near-almaty-airport), [videos on Dailymotion](https://dai.ly/x7pjs52
), [videos on Gizmodo](https://gizmodo.com/hand-tracking-on-the-oculus-quest-feels-pretty-magical-1838496621) and its sister websites, etc.
- This issue is not reproducible on videos from websites like: YouTube, Twitch, Veoh, etc.
- Attached is a recording of the [issue](https://drive.google.com/file/d/16USHKJQNwyeNXHUk3InhxbcTOKA5-S3J/view?usp=sharing).

**Comment by keianhzo** [comment]
@heres-maria This should be already fixed.

**Comment by Softvision-GeluHaiduc** [comment]
@keianhzo I have verified that this issue is no longer reproducible with the latest Firefox Reality version 10 RC5 (e84d3c92) installed on the Oculus Go, HTC Vive Focus Plus, Pico Neo2 and Pico G2 4K headsets.
Now, the play/pause button is displayed on websites that contain videos, verified on W3Schools’ HTML5 video page, videos on BBC, videos on Dailymotion, videos on Gizmodo.
As it is no longer reproducible I will close the issue.
