### ISSUE TITLE
Crash when pressing Alt + Space on Bluetooth keyboard.

### ISSUE THREAD

**Issue by gaegaelab** [MozillaReality/FirefoxReality#2580]
## Configuration

Firefox Reality version: 7(Release)
Firefox Reality build ID: Unknown

Hardware: Oculus Quest

## Steps to Reproduce

1.Press the address bar to display the cursor and virtual keyboard.
2.Press Alt + Space on Bluetooth keyboard.
3.

## Current Behavior

App crashes.

## Expected Behavior

Since I am in Japanese, keyboard switches to Japanese input mode.

## Context

I want to input Japanese on a Bluetooth keyboard.
 For Android apps that support Japanese, use "Shift + Space" or "Alt + Space" to switch to Japanese input.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by bluemarvin** [comment]
This is caused by a system bug on Oculus where alt+space creates a key event with key code `KeyEvent.KEYCODE_SEARCH`. FxR does not handle this keycode and returns it to the system which crashes with the following stack trace: https://crash-stats.mozilla.com/report/index/5aca224c-d05d-496a-850f-097e10200106
