### ISSUE TITLE
Broken stereo VR projections

### ISSUE THREAD

**Issue by MortimerGoro** [MozillaReality/FirefoxReality#2625]
## Steps to Reproduce

1. Open https://www.youtube.com/watch?v=vxNriWfhRRA
2. Select 360 stereo projection and watch video

## Current Behavior

1. The video UVs are wrongly displayed on each eye

## Expected Behavior

1. Correct 360 stereo video

180 TB and LR seem to be broken too

**Comment by jvonitter** [comment]
@Softvision-RemusDranca @Softvision-GeluHaiduc do we have test cases that cover this? If not, we probably should.

**Comment by MortimerGoro** [comment]
I found this is related to a Youtube video layout issue. It only happens with 360 stereo videos. The playback is broken in Oculus Browser too. I have a workaround to fix it.

**Comment by Softvision-RemusDranca** [comment]
@jvonitter We do verify this scenario while running our test cases. It seems that it's intermittent since it's not reproducible on all videos, for example: https://vimeo.com/214224792. Maybe there is an issue with the video from Youtube?

Anyway, I think that this could be mitigated by testing multiple videos from different sources. If you have a list with videos for each projection option would be very helpful since some of the video titles from Youtube website for example, are misleading.

On a different matter, our test cases are outdated and in need of major updates. Hopefully the time will permit us to do so going forward and have this scenario fully covered as well.

**Comment by heres-maria** [comment]
I have verified this issue and it is no longer reproducible with the latest Firefox Reality version 8 RC1 build (7a444d0c). 
The videos are displayed correctly for "360 Stereo", "Stereo 180 Left to Right" and "Stereo 180 Top to Bottom", including:
    https://www.youtube.com/watch?v=vxNriWfhRRA
    https://www.youtube.com/watch?v=VZK02CW7oy4

Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2).
