### ISSUE TITLE
Immersive Mode Appears to Crash Upon Entry when viewing WebVR Content

### ISSUE THREAD

**Issue by avrignaud** [MozillaReality/FirefoxReality#263]
Hardware: Oculus Go
Steps to Reproduce:

Here are the WebVR experiences that I tried and that didn’t work. It’s Task Definition Z8XVVBuASjevbCz3V77siQ and was pulled down and onto the Go at around 10:30 am this morning. All of these apps loaded their browser version and then when immersive mode is selected the device freezes and is unresponsive until it’s restarted.Song Exploder Presents: Inside Music (Audio works but nothing else)
Virtual Art Sessions in VR
Sketchfab Virtual Reality
WebVR LabI checked out “Check out My Moves on aframe.io/a-saturday-night” and it entered 360º and worked (tracking my head) but there was no interactivity and it seems as thought the text is mis-aligned in the game engine. 

Actual Behavior: All of these apps loaded their browser version and then when immersive mode is selected the device freezes and is unresponsive until it’s restarted.
Expected Behavior: Does not crash.
Recommendation: investigate and Fix. :)

**Comment by MortimerGoro** [comment]
I'm going to investigate this. I also got a freeze with PlayCanvas based demos (After fixing a WebGL crash) https://github.com/MozillaReality/FirefoxReality/issues/260

Probably is the same issue in both.

**Comment by fernandojsg** [comment]
A-Saturday-night is using a quite old A-Frame version (0.6.1) so it has many issues as positioning you incorrectly on the roof.
Sadly the demo is also not adapted for 3dof, so you could just watch dances from other people.
I believe there's no plan to upgrade the demo to a newer version of A-Frame.

**Comment by MortimerGoro** [comment]
More info about the each:

### Virtual Art Sessions

That VR experience is only compatible with room scale capable devices. I found that they use device names to check that capability so in Oculus go browser and FxR (in Oculus) thinks that the device is the Oculus Rift and allows to enter vr. In the Mireage it doesn't let the user to EnterVR because they name check fails.

Because of this the website never submits a frame when entering WebVR. On the Oculus Go you can see that it shows a infinite loading spinner but the user can exit when clicking back. On FxR we have the same problem but we still need to implement https://github.com/MozillaReality/FirefoxReality/issues/306 to allow exit from a WebVR experience that never sends frames.

### Sketchfab Virtual Reality

I pushed some PRs to fix the problem: https://github.com/MozillaReality/FirefoxReality/pull/307 and https://bugzilla.mozilla.org/show_bug.cgi?id=1479424

There is still one issue https://github.com/MozillaReality/FirefoxReality/issues/305  I expect to push the fix soon.

### A-Saturday-night

This was a demo problem so nothing to be fixed from the FxR/Gecko WebVR side.

I like the demo though, hope that we can upgrade it someday.

**Comment by MortimerGoro** [comment]
Closed via #328
