### ISSUE TITLE
Crash when opening link in new tab from fullscreen mode.

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#2703]
## Configuration

Firefox Reality version: v9
Firefox Reality build ID: badff03260edb12037a156081619c61f5cd76af4

Hardware: Quest

## Steps to Reproduce

1. Go to https://youtu.be/_T8cn2J13-4
2. Go fullscreen
3. Scroll the window until a link is visible
4. Long press link
5. Select `Open in new tab`

## Current Behavior

Crash: https://crash-stats.mozilla.com/report/index/d03e9e3b-1ce8-46da-8faa-d24400200123
## Expected Behavior

Link should be opened in new tab.

**Comment by bluemarvin** [comment]
The happens when ever the context menu is used. Caused by https://github.com/MozillaReality/FirefoxReality/pull/2696

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 9-40290101 (854287c0) installed on the Oculus Go, Quest, HTC Vive Focus and Focus Plus headsets.
Now, the app doesn’t crash when opening a link in a new tab from fullscreen mode.
There was a different behavior on the oculus devices witch I logged in #2710.
