### ISSUE TITLE
The Private Browsing description page can wrongly be sent as a tab from "Tabs View" to other devices

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2725]
**[Affected Versions]:**
- Firefox Reality version 9-40290101 (854287c)

**[Affected Platforms]:**
- HTC Vive Focus Plus - Android 7.1.2
- Oculus Quest - Android 7.1.1

**[Prerequisites]:**
- The Firefox Reality browser is opened.
- An valid FxA account is connected.

**[Steps to reproduce]:**
1. Click the Private Browsing button from the tray menu.
2. Click the "Tabs View" button from the tray menu.
3. Hover over the PB description tab and click the "Send Tab to Device" button.
4. Observe the behavior

**[Expected results]:**
- Nothing happens, the option is grayed out.

**[Actual results]:**
- The "Send Tab to Device" prompt is displayed.

**[Additional]:**
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1sCiit0epCmH-vXzHuTn7I1FHSAK4oA3R).

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 9-40371914 (083b65c0) installed on the Oculus Go, Quest, HTC Vive Focus and Focus Plus headsets.
Now, the PB description page can not be sent as a tab from "Tabs View".
However, a different behavior was observed using an edge case scenario and issue #2756 was logged for it.
