### ISSUE TITLE
The thumbnail's buttons and title wrongly remain displayed after clicking the "Send to Device" button

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2726]
**[Affected Versions]:**
- Firefox Reality version 9-40290101 (854287c)

**[Affected Platforms]:**
- HTC Vive Focus Plus - Android 7.1.2
- Oculus Quest - Android 7.1.1

**[Prerequisites]:**
- The Firefox Reality browser is opened.
- An valid FxA account is connected.

**[Steps to reproduce]:**
1. Click the "Tabs View" button from the tray menu.
2. Hover over a thumbnail and click the "Send Tab to Device" button.
3. Click the "Send" button from the prompt displayed.
4. Observe the thumbnail's UI for the sent tab from "Tabs View" prompt.

**[Expected results]:**
- Only the tab's preview is displayed.

**[Actual results]:**
- The "Send Tab to Device", "x" close button and tab's title are also displayed.

**[Notes]:**
- This issue is also reproducible if the "Send Tab To Device" prompt is dismissed.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1LOito8mL_iAQjlwuNKTNj4_SWgoi1skL).

**Comment by Softvision-RemusDranca** [comment]
I'm currently blocked by #2839 in verifying this issue.

**Comment by heres-maria** [comment]
I have verified that this issue is no longer reproducible in the latest Firefox Reality version 9 RC4 (c64365e3) build.  
The buttons and the title of the thumbnails are no longer displayed after dismissing the "Send tab to Device" prompt.
Tested on Pico Neo 2 (Android 8.1.0), Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2).
