### ISSUE TITLE
The PB description page and Homepage can wrongly be bookmarked

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2733]
**[Affected Versions]:**
- Firefox Reality version 9-40311840 (85032800)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned.

**[Steps to reproduce]:**                                        
1. Open the app.
2. Observe if the bookmark button is displayed in the Awesomebar.
3. Click the PB button from the tray.
4. Observe if the bookmark button is displayed in the Awesomebar.

**[Expected results]:**
- Step 2 and 4: The bookmark button is NOT displayed.

**[Actual results]:**
- Step 2 and 4: The bookmark button is displayed.

**[Notes]:**
- The Homepage has no title in Bookmarks view.
- The PB description page does not render anything when opened from bookmarks view.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=16_H_Xmq8EK4xDa381uReMO7tEwJDZFz3).

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 9-40412247 (3949e4c1) installed on the Oculus Go, Quest, HTC Vive Focus and Focus Plus headsets.
Now, the PB description page and the Homepage can no longer be bookmarked, the bookmark icon is no longer displayed when on these pages.
