### ISSUE TITLE
Can’t launch Firefox Reality again after force close the App

### ISSUE THREAD

**Issue by kaipinglee** [MozillaReality/FirefoxReality#2739]
## Configuration

Firefox Reality version: 7.1
Firefox Reality build ID: 

Hardware: Vive Focus plus

## Steps to Reproduce

1. Launch Firefox Reality App.
2. Long press HOME button 10 sec to force close the Firefox Reality App.
3. Users can't launch Firefox Reality App again unless reboot the HMD.

## Current Behavior

Users can’t launch Firefox Reality again after force close the App. 
Please refer to the attached video:
https://drive.google.com/open?id=1OYf824kHAR8seKQ3mtRU587X_s30QwRV

## Expected Behavior

Users can launch Firefox Reality after force close the App.

## Error Logs and Stack Traces

https://drive.google.com/open?id=181hIcT4K_a7y33Tt00rO8HhEi7JrpMO_

<details open>

```
```

</details>

**Comment by Softvision-GeluHaiduc** [comment]
I managed to reproduce the issue on the production version as well (FxR V8 RC5). It is also reproducible in the latest master build of Firefox Reality version 9-40341450 (ade4895e).
If the app is force killed using the adb command (adb shell am force-stop org.mozilla.vrbrowser) the issue is not reproducible. The issue is also not reproducible with other apps on the device.

**Comment by Softvision-GeluHaiduc** [comment]
We have verified that this issue is no longer reproducible with the latest Firefox Reality version 8.1 (a0fcc8a3) installed on the HTC Vive Focus and HTC Vive Focus Plus headsets.
Now, the users can launch the Firefox Reality app after force closing it by pressing the Vive button for more than 10 seconds.
