### ISSUE TITLE
Firefox Reality broke playing VR panoramas in Oculus Quest

### ISSUE THREAD

**Issue by Spartacus1** [MozillaReality/FirefoxReality#2780]
Firefox Reality was a nice experience in Oculus Quest for playing VR panoramas until last month. The recent 2 version broke lots of things. It's no longer possible to play VR sites based on Panoramas from KRPano or Panotour for instance. They still work good in Oculus Quest build in Browser but they were playing even better 2 FReality versions ago. In case this issue is not solved, Is it possible to revert?

## Configuration

Firefox Reality version: Latest Firefox Reality version for Oculus Quest
Firefox Reality build ID: 

Hardware: Oculus Quest

## Steps to Reproduce

1.
2.
3.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by Spartacus1** [comment]
Firefox Reality was a nice experience in Oculus Quest for playing VR panoramas until last month. The recent 2 version broke lots of things. It's no longer possible to play VR sites based on Panoramas from KRPano or Panotour for instance. They still work good in Oculus Quest build in Browser but they were playing even better 2 FReality versions ago. In case this issue is not solved, Is it possible to revert?

**Comment by bluemarvin** [comment]
Can you provide examples. I just tested every example on this page: https://krpano.com/examples/?webvr and did not find any issues.

**Comment by Spartacus1** [comment]
Test the one I'm working now. It's working great in the Oculus built in browser and It was working great in Reality 2 versions ago. I liked much more Firefox because Images (such as the geological map accessible from the left small top image, has a lot more quality in FF.

http://www.geosite.pt/viana_proj/GeoparkViana/GeoparkViana.html?s=pano882

**Comment by bluemarvin** [comment]
I think the problem is you are not serving it over https. I think there was a policy change that requires https for webvr in Firefox.

**Comment by Spartacus1** [comment]
I guess so. However, It should be optional. I understand reasons to bloc some features that have implications with security for users but I see no reason to bloc VR from no https sites. The built in browser still supports it.

**Comment by bluemarvin** [comment]
I don't disagree, unfortunately there are certain decisions beyond our control. I will look into it a little more to see if there is some way to work around it.

**Comment by Spartacus1** [comment]
That would be awesome. I really miss using Firefox for exploration and development of this kind of websites.

**Comment by bluemarvin** [comment]
I've spoken with the WebVR module owner and unfortunately there is no way to bypass the requirement. There are a few things you can do either locally for development or with hosting. For local development you can generate your own certificate and FxR can now accept certificates from unknown signers. You can use adb to port-forward an http server so that it looks like localhost. Localhost does not have the https requirement. Finally, I was told cloudflare can do server side proxy that will allow the content to work. I wish I had a better solution to offer but unfortunately these are the best I could come up with. When WebXR replaces WebVR, https will be required as part of the spec so the oculus browser will also probably have to require it.

**Comment by Spartacus1** [comment]
Thank you so much Randall. I'll try to use some of the solutions you suggest. Meanwhile I'll try to solve the issues "server side" by going https. 
Best Regards
