### ISSUE TITLE
A page that was bookmarked in PB appears as a visited page in the awesomebar suggestions

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#2834]
**[Affected Versions]:**
- Firefox Reality version 9 RC2 (37ac4cbd)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is opened.

**[Steps to reproduce]:**
1. Click the Private Browsing button in the menu tray.
2. Navigate to a webpage and bookmark it. (e.g. puma.com)
3. Exit PB and click inside the awesomebar.
4. Type inside the awesomebar “puma”.
5. Observe the suggestions.

**[Expected results]:**
- The webpage (from step 2) appears as a suggested bookmark.

**[Actual results]:**
- The webpage (from step 2) appears as a suggested previously visited webpage and as a suggested bookmark.

**[Notes]:**
- The issue is also reproducible in production, FxR V8.
- Attached a screen recording of the issue [here](https://drive.google.com/open?id=1-HixOF0V5BefMSAZ-ju8Ng6gWYLZTxso).

**Comment by keianhzo** [comment]
Same behavior for Fenix, it seems to be something AS related. I've pinged the Rust components team on slack.

**Comment by keianhzo** [comment]
AS team reported:

> it’s intentional that we suggest bookmarks as well—we give bookmarks a boost in the results because bookmarking is a user action, so we think they might want to visit the page again

We don't show (don't even receive) time stamp information about history suggestions so I think it's safe to show it given that they will show in the bookmarks anyway as there is no such thing as Private Mode Bookmarks.

@emstanley @bluemarvin We can push this is anybody feels that it shouldn't show up, the AS team wasn't also very sure about what is the expected behavior here.

What do you think @bluemarvin ?
