### ISSUE TITLE
The close and share buttons in the tab view no longer work

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#2839]
## Configuration

Firefox Reality version: v9
Firefox Reality build ID: 18aba8bec1b758144b3246bb582fb2b0003fd264

Hardware: Go, G2

## Steps to Reproduce

1. Open multiple tabs.
2. Open tab view
3. Click the close button for one of the tabs.

## Current Behavior

Tab view is closed and tab is not closed.

## Expected Behavior
The tab is closed.

## Notes
The share button has the same behavior. The tab view is closed and there is no attempt to share the tab.

**Comment by Softvision-GeluHaiduc** [comment]
Using the latest RC build, Firefox Reality version 9 RC3 (18aba8be), I managed to reproduce this issue on all of the devices we have, Oculus Go, Quest, HTC Vive Focus, Focus Plus and Pico Neo2, both in closing the tab or sending the tab from the tab view. This bug will also block us on verifying some issues.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 9 RC4 (c64365e3) installed on the Oculus Go, Quest, HTC Vive Focus, Focus Plus and Pico Neo2 headsets.
Now, the close and share buttons that appear on tabs while hovering them in the Tab View work as expected.
