### ISSUE TITLE
[Pico][Intermittent] The "Send tab to Device" button gains an orange color when clicking the other buttons from the Hamburger menu

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2848]
**[Affected Versions]:**
- Firefox Reality 9 RC3 (18aba8b).

**[Affected Platforms]:**
- Pico Neo 2 - Android - 8.1.0

**[Prerequisites]:**
- The headset is turned on.

**[Steps to reproduce]:**										
1. Open the app.
2. Click the Hamburger button.
3. Click the "Resize Window" button from the menu displayed.
4. Observe the "Send tab to Device" button's UI.

**[Expected results]:**
- No UI changes are displayed.

**[Actual results]:**
- The button briefly gains an orange color.

**[Notes]:**
- Please download the linked video to view it. It seems that the video played in Drive does not render the issue.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1OcJ1418Fc5gGr7zKtKdPh7Mea-ks1X0N).

**Comment by Softvision-GeluHaiduc** [comment]
This issue is also present in the latest RC build, Firefox Reality version 10 RC2 (17a313b4) installed on the Pico G2 4K headset.
Also because the order of the buttons was changed now the “Window Resize” button is the one gaining an orange color when one of the other buttons from the hamburger menu is clicked.

**Comment by bluemarvin** [comment]
@daron-walters Will you have a PR ready for code freeze next week or should we move this to v12?

**Comment by daron-walters** [comment]
move to v12
