### ISSUE TITLE
The menu tray and Awesomebar are briefly displayed when entering/exiting PB with multiple windows

### ISSUE THREAD

**Issue by heres-maria** [MozillaReality/FirefoxReality#2855]
**[Affected Versions]:**
- Firefox Reality 9 RC 3 (18aba8be)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2
- Pico Neo 2 - Android - 8.1.0

**[Prerequisites]:**
- The headset is turned on, the browser is installed and open.

**[Steps to reproduce]:**                                        
1. Click the “+” button in the menu tray.
2. Click the PB button from the menu tray.
3. Observe the behavior.

**[Expected results]:**
- The transition is correctly performed.

**[Actual results]:**
- The menu tray and Awesomebar from normal browsing are briefly displayed.

**[Notes]:**
- Related to issue #2683.
- This issue is also reproducible when exiting PB.
- Attached is a [recording](https://drive.google.com/file/d/1UGanzsNX2uIOCozM88D5KWkFb4iyPSu5/view?usp=sharing) of the issue.

**Comment by keianhzo** [comment]
@heres-maria This should be already fixed.

**Comment by Softvision-GeluHaiduc** [comment]
@keianhzo I have verified that this issue is no longer reproducible with the latest Firefox Reality version 10 RC5 (e84d3c92) installed on the Oculus Go, HTC Vive Focus Plus, Pico Neo2 and Pico G2 4K headsets.
Now, the menu tray and awesomebar are not briefly displayed when entering/exiting PB with multiple windows.
As it is no longer reproducible I will close the issue.
