### ISSUE TITLE
Volume UI appears as a distorted black rectangle in Oculus Go (in Immersive Mode)

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#287]
## Hardware
VR Browser: Firefox Reality
VR Device: Oculus Go
Build ID: OTBk7afrRu2nW81w0kOyBA
Build Date: 2018-07-31

## Steps to Reproduce
1. Load a WebVR-capable site, such as **https://kuula.co/post/7PP6r** ([_Evening at Kvalvika Beach_](https://kuula.co/post/7PP6r) from https://mzl.la/2NVWRyE) or **https://tonite.dance/**.
2. **Enter VR** mode (typically by clicking a VR-goggles icon or "Enter VR" button).
3. Once Immersive Mode (WebVR) is entered, press the **Volume-Up/Volume-Down Controls** on the top of the Oculus Go headset.
4. Notice a **distorted, black rectangle appears** where the **in-headset volume controls** usually appear in (native) VR apps.

## Actual Behavior
The in-headset volume controls appear as a distorted, black rectangle.

![image](https://user-images.githubusercontent.com/203725/43493790-a3a97c64-94e4-11e8-8958-6a85f6b63a3c.png)
![image](https://user-images.githubusercontent.com/203725/43493792-a59352d4-94e4-11e8-8cb0-a1d89c2a7511.png)

## Expected Behavior
The in-headset volume controls appear normally.

![image](https://user-images.githubusercontent.com/203725/43493784-9c17db3a-94e4-11e8-8d43-6523706d02d0.png)

## Recommendation
I tested the behaviour in Oculus Browser, and the in-headset volume controls actually **do not** appear while presenting WebVR content. Pressing the Volume-Up/Volume-Down buttons on the headset do in fact change the volume though.

I'd recommend that we actually show the in-headset volume controls, as they work on 2D pages in Firefox Reality.

**Comment by thenadj** [comment]
@cvan Is there a standard volume control UI that we'll get from Oculus or do we have to draw our own?

**Comment by thenadj** [comment]
Ok, let's use that. No need to design a custom control then.

**Comment by avrignaud** [comment]
@cvan There's something very strange going on here. With the build of FxR I grabbed this morning (7/31) I could not enter immersive mode. And best I could do was go to a larger window which had a strange vertical image mismatch in the pano. Imagine if I took the pano, copied a section to the right, and then moved it left a significant amount so it no longer matched the picture. We should investigate a bit more - @larsbergstrom had similar results to me (couldn't get into immersive in FxR), while you seem to be able to on Oculus Go.

**Comment by bluemarvin** [comment]
@avrignaud The immersive mode issue is probably because there was a mismatch between gecko and FxR for a short time. Gecko and FxR have to share a data structure to pass data between them for immersive mode. The structure was updated yesterday on Gecko. We have code that detects mismatches between the structs and won't go into immersive mode when that happens. I updated the FxR side today so new builds should be working again. We are trying to figure out how to make the shared header a build artifact for GeckoView so we don't have to manually keep the headers synchronized but there isn't a simple mechanism to do that with Android AARs (which is what GeckoView is).

The volume overlay is drawn by the Oculus OS. We don't have any control over it (we might be able to disable, but I'm not even sure about that). The rendering problems in immersive are probably caused by OpenGL errors on the Oculus side. We can investigate that but the actual UI is render by the system so we will probably not have very many options.
