### ISSUE TITLE
The website's URL is not displayed after clicking the History or Bookmarks buttons if the app was closed while the library menus where open

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2871]
**[Affected Versions]:**
- Firefox Reality 9 RC3 (18aba8b)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- Pico Neo 2 - Android - 8.1.0

**[Prerequisites]:**
- The headset is turned on and the app is opened.

**[Steps to reproduce]:**
1. Navigate to a website.										
2. Click the History button from the menu tray.
3. Restart the device and reopen the FxR app.
4. Click the History button to dismiss the library.
5. Observe the Awesomebar.

**[Expected results]:**
- The URL's website is displayed.

**[Actual results]:**
- The URL's website is NOT displayed.

**[Notes]:**
- This issue is also reproducible with the Bookmarks library.
- In some attempts the libraries were not dismissed when clicking the History or Bookmarks buttons.
- If the Youtube website is in the background, the "https://www.youtube.com/?app=desktop" URL is displayed, and as a side effect after reopening the app with this URL, Youtube messages are displayed informing that the website is in an old version [video](https://drive.google.com/open?id=1QLgKJ0IsjyB49_QbAp5ZM0e6eDZ9n--y).
- I am currently blocked on verifying this issue on the HTC devices, because of issue #2854.
- Attached are screen recording with both behaviors described: 
	- Library not dismissed: [link](https://drive.google.com/open?id=1YEU_YLmIqEsF33qen6eqaiBNbpgxSvCF).
	- URL not displayed: [link](https://drive.google.com/open?id=1eauA3DmTM2Ht_K9ZNQel65LOIbvu4fuc).

**Comment by heres-maria** [comment]
This issue is still reproducible in the Firefox Reality version 9 RC4 ( c64365e) build.
In the cases of both History and Bookmarks, restarting/closing (+adb command) and reopening the app while one of them is open causes the URL to not be displayed for that window after.
Tested on Pico Neo 2 (Android 8.1.0), Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2).

**Comment by MortimerGoro** [comment]
@heres-maria can you share the latest STR and the adb commands you use to reproduce this?

**Comment by heres-maria** [comment]
@MortimerGoro The STR I used are:
1. Navigate to a website.
2. Click the History button from the menu tray.
3. Restart the device and reopen the FxR app.
4. Click the History button to dismiss the library.
5. Observe the Awesomebar.

In step 3 I used 2 variants:
a. Restart the app using the "Restart Now" button after changing a setting that triggers the restart prompt.
b. Close the app, use the **"adb shell am force-stop org.mozilla.vrbrowser**" for Oculus or "**adb shell am force-stop org.mozilla.vrbrowser.wavevr**" for HTC and then open the app from the app icon. We use these commands to simulate the app completely closing after a while.

(on Pico, instead of an adb command, I closed it by double pressing the Pico home button (after closing FxR) and clicking "Close all" from above the "Usage Record" app list)

I'm attaching a [recording ](https://drive.google.com/file/d/13eFhLzXgsdV1Y6m5vJRRWrM3c-sZzpEx/view?usp=sharing)of this issue.

**Comment by keianhzo** [comment]
@Softvision-RemusDranca I can't reproduce this anymore using the latest master. We have pushed some updates that might have fixed this, could you please verify?

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with the latest Firefox Reality version 10-141111916 (d9a7eec). The URL or placeholder are correctly displayed after dismissing the libraries.
Tested on HTC Vive Focus (Android 7.1.2), Oculus Quest (Android 7.1.1) and Pico Neo 2 (Android - 8.1.0) devices.

Considering this I will close this issue as verified fixed.
