### ISSUE TITLE
Load local IP URLs instead of doing a google search

### ISSUE THREAD

**Issue by MortimerGoro** [MozillaReality/FirefoxReality#2914]
e.g. If you type 192.168.0.1 or localhost in the URL bar it does a Google search instead of trying to load the IP address. This is really annoying for devs, who are used to not to type the whole protocol when loading a local url.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 10-40720037 (dbb8ed3a) installed on the Oculus Go, Quest, HTC Vive Focus, HTC Vive Focus Plus and Pico Neo2 headsets.
Now, when introducing an IP address in the URL bar it accesses that IP and doesn’t perform a google search.
