### ISSUE TITLE
Youtube video controls are not displayed correctly after resize to 1X or 0,5X in theater mode

### ISSUE THREAD

**Issue by SoftVision-LorandJanos** [MozillaReality/FirefoxReality#2919]
**[Affected Versions]:**
- Firefox Reality version 9 rc7 (b68f946)

**[Affected Platforms]:**
- HTC Vive Focus Plus - Android 7.1.2
- Oculus Quest - Android 7.1.1
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is opened.

**[Steps to reproduce]:**
1. Navigate to a normal video on YouTube and enter theater/full screen mode.
2. Resize the screen to 1x.
3. Observe the video controls.
4. Resize the screen to 0,5x.
5. Observe the video controls.

**[Expected results]:**
- The video controls are displayed correctly on the bottom of the screen.

**[Actual results]:**
- The video controls are displayed partially after resizing to 1x
- The video controls are not displayed after resizing to 0,5x.

**[Notes]:**
- This issue is not reproducible with sizes greater than 1x.
- If the video screen is scrolled down, the controls appear.
- Attached is a video of this [issue](https://drive.google.com/file/d/1Vfc_fhT_xunNUGpC7aqQkI7gjIoBelJR/view)

**Comment by daoshengmu** [comment]
It looks like we need to take the aspect of Youtube video and multiple it with the resize ratio as well.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 11-141492311 (a9b58ee6) installed on the Oculus Go, Pico Neo2 and Pico G2 4K headsets.
Now, the YouTube video controls are displayed correctly after a resize to 1x or 0.5x in theater mode. There is a new behavior on videos longer than 1 hour where the controls are moved down on the 0.5x size window.
