### ISSUE TITLE
The keyboard keys have no hover effect while the Close/Move buttons are hovered with the other controller

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2997]
**[Affected Versions]:**
- Firefox Reality version 10-140780019 (93eff89)

**[Affected Platforms]:**
- HTC Vive Focus Plus - Android 7.1.2
- Oculus Quest - Android 7.1.1
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is opened.
- Both controllers are active.

**[Steps to reproduce]:**
1. Click the Awesomebar do display the keyboard.
2. Hover with a controller over the Close or Move storyboard buttons.
3. With the other controller hover over the keyboard keys.
4. Observe the behavior.

**[Expected results]:**
- The keys have a hover effect.

**[Actual results]:**
- No hover effect is applied to the keys.

**[Notes]:**
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1Yc2O22zTDRVkX9Itiwfxqy5QDwQLrVvy).

**Comment by keianhzo** [comment]
@Softvision-RemusDranca This is the expected behavior. Doe to Android limitations the hover only works for the keyboard keys, every other widget (move/close, languages, domains, completion) only get the hover of the first controller in and the hovers from the other controllers are discarded.

Typing should work for both controllers.
