### ISSUE TITLE
Update Pop-up Blocking Override UI

### ISSUE THREAD

**Issue by emstanley** [MozillaReality/FirefoxReality#3075]
UX Trello Card: https://trello.com/c/LserbZRw/428-uis-86-pop-up-blocking-override

[UIS-86_Pop_Up_Blocking_Override_008.pdf](https://github.com/MozillaReality/FirefoxReality/files/4405054/UIS-86_Pop_Up_Blocking_Override_008.pdf)

**Comment by emstanley** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UIS-86 Pop-up Blocking Override](https://trello.com/c/LserbZRw/428-uis-86-pop-up-blocking-override)

**Comment by emstanley** [comment]
This may need more discussion at design review.

**Comment by keianhzo** [comment]
@thenadj We need a crossed out version of the "Popups blocked" icon to unify this with the rest of the permissions where the icons in the URL bar are crossed out when the site is blacklisted.

**Comment by keianhzo** [comment]
Also we are already making the icon inside the popup icon fog. Maybe you are referring to the fact that the icon is blue when it is showing a notification? This is because we defined a style by which any button's icon is tinted in blue if a notification is showing on that button. Happens the same with the Tray buttons when they have notifications (ie. a New tab is opened).

**Comment by cjyjae35** [comment]
@keianhzo I readdressed the color since the previous version of the document (_UIS-86_007_) said the click state's icon color should be Rhino (#8c898a). I wanted to prevent any confusion in the future.

I've attached the icon to the [Trello card](https://trello.com/c/LserbZRw/428-uis-86-pop-up-blocking-override).
