### ISSUE TITLE
The crash prompt is displayed after quitting and resuming the app while in immersive mode

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3092]
**[Affected Versions]:**
- Firefox Reality version 10-140922050 (de88941).

**[Affected Platforms]:**
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Plus - Android 7.1.2
- Oculus Quest - Android 7.1.1
- Oculus Go - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the app is opened.

**[Steps to reproduce]:**                                        
1. Play a 360 video in immersive mode.
2. Quit the app and reopen it.
3. Observe the behavior.

**[Expected results]:**
- The app is correctly resumed.

**[Actual results]:**
- The crash prompt is displayed.

**[Additional Notes]:**
- On the HTC devices the issue is reproducible only after the app was force stopped.
- I was not able to reproduce this issue on the Pico devices in 5 attempts.
- Attached are the screen recording, logcat and crash report of the issue: 
	- Screen recording: [link](https://drive.google.com/open?id=1usMHLLqwGObyDXHHDgSNcv6KvZEBv2CV).
	- Crash Report: [link](https://crash-stats.mozilla.com/report/index/ec656c1c-d63a-4027-8838-32aed0200402).
	- Logcat: [link](https://drive.google.com/open?id=1M4DHaQ95ohpOovgrxx9WeYediuBO-wyz).

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 10-140982354 (bce60f9d) installed on the Oculus Go, Oculus Quest, HTC Vive Focus Plus and HTC Vive Focus headsets.
Now, the crash prompt is not displayed after quitting and resuming the app while in immersive mode.
When testing this issue I encountered issue #3131 on the oculus devices.
