### ISSUE TITLE
Add label=browser-firefox-reality param to issue reporter URL

### ISSUE THREAD

**Issue by miketaylr** [MozillaReality/FirefoxReality#312]
Currently we send `?src=browser-fxr` when a site is reported via browser Settings -- we would like to be able to also add a label to issues, so it's a bit easier to consume that data.

https://github.com/webcompat/webcompat.com/pull/2562 adds `browser-firefox-reality` to the list of GET param'able labels for new issues, so we should send something like: `?src=browser-fxr&label=browser-firefox-reality`.

**Comment by cvan** [comment]
Great, thanks!

1. I opened https://github.com/MozillaReality/FirefoxReality/pull/326 to change the URL
1. I updated the logic at https://mixedreality.mozilla.org/fxr/report?src=browser-fxr to add `label=browser-firefox-reality` if `label` is missing
1. I emailed Liz about updating mzl.la/fxr tiny URL to add the `label` too (and asked about namespaced URLs for headsets)

<hr>

@miketaylr I have a larger question about referring folks to https://mzl.la/fxr, because the `os` and `browser` form values cannot be overridden by query-string parameters. Because webcompat.com parses on the server the `User-Agent` request header sent by the browser, when a user loads https://mzl.la/fxr on their desktop computer, the form then looks something like this:

![image](https://user-images.githubusercontent.com/203725/43760470-225b5478-99f0-11e8-82a8-3a57cafa5c29.png)

(But of course they'd be using Firefox 😉.)

1. As a stopgap for today, can the form code for WebCompat.com allow `os` and `browser` to be overridden if provided via query-string param?
2. Can we get Firefox Reality to send an HTTP request header `XR-Capabilities` (or `XR-Platform`), à la `Accept-Language`, that could be used instead of the `User-Agent` for our VR/AR/XR browser?

(I do realise I'm asking way too many questions here, but for posterity's sake, what the hey…)

<hr>

@miketaylr Would it be possible to do `&label=browser-firefox-reality,headset-oculus-go`? does it make sense to allow labels to be grouped by headset?

Once we get traffic, I think it might be helpful to have that information.

The headset is not parseable from the UA and [WebVR v1.1's](https://immersive-web.github.io/webvr/spec/1.1/) JavaScript API, `navigator.getVRDisplays(…)`, has deprecated the [`<VRDisplay>#displayName`](https://immersive-web.github.io/webvr/spec/1.1/#dom-vrdisplay-displayname) for [fingerprinting reasons](https://immersive-web.github.io/webxr/#fingerprinting-security) in the successor API spec, [WebXR's `navigator.xr.requestDevice(…)`](https://immersive-web.github.io/webxr/#xr-interface).

We do know the build flavour of the browser APKs:

- `oculusvr` (Oculus Go, Samsung Gear VR)
- `svr` (Snapdragon VR by Qualcomm, ODG glasses)
- `googlevr` (Google Daydream)
- `noapi` (runs on standard Android phone without headset)
- `wavevr` (VIVE Focus)

Does this make sense to have FxR pass this information in the `label` query-string parameter in the "Report an issue" URL (for WebCompat's bot to then associate it the issues with the correct label)?

<hr>

And maybe I'm overloading this issue with too many feature requests, but thoughts about prepending the `[FLAVOR]` for links when filing GitHub issues directly in this repo? Example: https://github.com/MozillaReality/FirefoxReality/issues/new?title=[Daydream]
