### ISSUE TITLE
Lighting isn't restored when exiting Fullscreen mode

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#3213]
## Configuration

Firefox Reality version: 10
Firefox Reality build ID: 1f805d74dc8221740835703985012f771115e3f8

Hardware: All

## Steps to Reproduce

1. Play a non-VR youtube video
2. Go fullscreen
3. Exit fullscreen with the youtube native UI (not back button or FxR fullscreen UI)

## Current Behavior

Environment remains dimmed.

## Expected Behavior

Environmental lighting should be restored.

**Comment by bluemarvin** [comment]
Navigation bar is not restored either when multiple windows are present:

![org mozilla vrbrowser-20200422-123912](https://user-images.githubusercontent.com/3066/80026087-699bcb00-8496-11ea-8b2b-515df30f25cc.jpg)

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 10 RC1 (6db2f60a) installed on the Oculus Go, HTC Vive Focus Plus, Pico Neo2 and Pico G2 4K headsets.
Now, lighting is restored when exiting fullscreen mode using the YouTube button, the navigation bar is also restored.
