### ISSUE TITLE
Pop up blocking nav bar icon is reversed.

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#3335]
## Configuration

Firefox Reality version: 10
Firefox Reality build ID: 37a3f8b1aa19f0aa2f0ac2cd2b9cbb4437b8c484

Hardware: All

## Steps to Reproduce

1. Visit http://popuptest.com/popuptest1.html
2. Look at pop up icon in nav bar

## Current Behavior

The pop ups are blocked but the icon for allowing pop ups is shown:
![org mozilla vrbrowser-20200505-133314](https://user-images.githubusercontent.com/3066/81113469-23525d00-8ed5-11ea-9160-066a2c9643cb.jpg)

Additionally, the tool tip always says `Pop-Up Blocked` even if they were not:
![org mozilla vrbrowser-20200505-133334](https://user-images.githubusercontent.com/3066/81113565-4e3cb100-8ed5-11ea-9373-09de05daada5.jpg)

## Expected Behavior

The correct icon and tooltip is displayed.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 10 RC5 (e84d3c92) installed on the Oculus Go, HTC Vive Focus Plus, Pico Neo2 and Pico G2 4K headsets.
Now, the correct icons are shown in the awesomebar, also the correct tooltips are displayed as well.
