### ISSUE TITLE
Properly select the Video the render mode, display the 180/360 videos and implement the external video control UI

### ISSUE THREAD

**Issue by nancyhang** [MozillaReality/FirefoxReality#344]
## Hardware

All
## Steps to Reproduce

Try to use video sites

## Current Behavior

Laggy controls, missed clicks, confusing interaction, no support for 180/360 videos
## Expected Behavior

Site offered controls work intuitively for user, whether from Desktop or Mobile pages
## Possible Solution

Test video controls on following sites, select to serve Desktop or Mobile page as appropriate for best experience. Open site specific bug as needed, link to list below.

Steps:
1. Add external video control API is the GV part. 
2. Implement the external video control UI is the FxR part. 
3. Properly selecting the render mode and displaying the 180/360 video is also FxR

Video Sites:

    Within - https://www.with.in/
    YouTube - https://www.youtube.com/
    YouTube VR (180/360) - https://www.youtube.com/channel/UCzuqhhs6NWbgTzMuM09WKDQ
    Vimeo - https://vimeo.com/channels/staffpicks
    Vimeo VR (180/360) - https://vimeo.com/channels/360vr
    360cities - https://www.360cities.net/
    NYT 360 Video - https://www.nytimes.com/video/360-video
    CNN VR - https://www.cnn.com/vr

## Error Logs and Stack Traces

<details open>
  
</details>

**Comment by avrignaud** [comment]
@nancyhang This is related to making videos just work as served from these websites - not us implementing media controls of our own. So this is P0.

**Comment by MortimerGoro** [comment]
@thenadj I've been researching some corner cases that need to be addressed in the spec:

- A video can have no audio track, so we need also an icon for that case. A icon that represents that the video has not audio so it can't be changed
- We can't get the preview when seeking, so we need to show the seek time in a different way, without the preview screenshot
- We need to allow the 3D/180/360 projections on any full-screen mode, not only video. In that case I think the easiest thing to do is use the same UI but with the video controls disabled, so if you agree we'd need the icons/colors to show that disabled UI. It won't be a common scenario, because most fullscreens are for videos.

**Comment by cvan** [comment]
> A video can have no audio track, so we need also an icon for that case. A icon that represents that the video has not audio so it can't be changed

speaking of which, what if there's an `<audio>` tag in the background (`<body>`) but the video is being played?

> We can't get the preview when seeking, so we need to show the seek time in a different way, without the preview screenshot

correct. we can in some cases, but not consistently. many CDNs are probably serving videos correctly with the appropriate HTTP response headers (i.e., `Content-Length`, `Content-Range`).

[here's a useful doc on MDN about seekable media.](https://developer.mozilla.org/en-US/docs/Web/Apps/Fundamentals/Audio_and_video_delivery/buffering_seeking_time_ranges#TimeRanges_Object)

> We need to allow the 3D/180/360 projections on any full-screen mode, not only video. In that case I think the easiest thing to do is use the same UI but with the video controls disabled, so if you agree we'd need the icons/colors to show that disabled UI. It won't be a common scenario, because most fullscreens are for videos.

what's the use case here? I can think of only [CSS-VR (Cardboard style)](https://keithclark.co.uk/articles/css-vr/) and perhaps a 2D canvas that's not using the WebVR.

> Some videos may not be seekable, specially in some streaming situations

yep, see above.

<hr>

@thenadj: UIS-43.002 is great!

can we add an option to allow the user to easily mute by clicking the Volume control? the Volume controls would likely need to be exposed then upon on hover instead (and have the bar closer or horizontal) and mute on click?

**Comment by thenadj** [comment]
@cvan RE: can we add an option to allow the user to easily mute by clicking the Volume control? the Volume controls would likely need to be exposed then upon on hover instead (and have the bar closer or horizontal) and mute on click?

Adding it as a work item to Trello: https://trello.com/c/kZ2lZ1D6/159-uis-43-immersive-movie-mode

**Comment by thenadj** [comment]
@cvan Mute is already in the spec - scroll half way down. It's titled Volume Mute. Check out UIS-43 for details.

**Comment by MortimerGoro** [comment]
@thenadj @jenniferhoang should we use this same resize preset menu style for the normal resize mode? It's using separate buttons now, I'd like to have consistency between both.
<img width="309" alt="captura de pantalla 2018-10-19 a las 13 32 46" src="https://user-images.githubusercontent.com/1070794/47216030-d7e46680-d3a3-11e8-9658-986f240bba32.png">
<img width="266" alt="captura de pantalla 2018-10-19 a las 13 30 27" src="https://user-images.githubusercontent.com/1070794/47216021-d024c200-d3a3-11e8-89fa-8f15cd55fa25.png">

Another thing, there is some inconsistency between the "instances for no video" UI and the Video mode UI:
<img width="309" alt="captura de pantalla 2018-10-19 a las 13 32 46" src="https://user-images.githubusercontent.com/1070794/47216052-f34f7180-d3a3-11e8-8ff1-eb047e06c940.png">

<img width="208" alt="captura de pantalla 2018-10-19 a las 13 32 30" src="https://user-images.githubusercontent.com/1070794/47216049-ef235400-d3a3-11e8-90fc-4de5a08aaf26.png">

<img width="338" alt="captura de pantalla 2018-10-19 a las 13 34 18" src="https://user-images.githubusercontent.com/1070794/47216060-fd717000-d3a3-11e8-9f3d-8f948592e10c.png">

Can we use the same style in both? I like the "whole button hover" intead of the "circle hover" better in this case.

When the video controls are visible I think it's ok to use the "circle hover" style:
<img width="289" alt="captura de pantalla 2018-10-19 a las 13 37 07" src="https://user-images.githubusercontent.com/1070794/47216096-1bd76b80-d3a4-11e8-9272-2caaf39b44c8.png">

**Comment by thenadj** [comment]
@MortimerGoro Thanks for catching the inconsistency here! @jenniferhoang I agree with the comment to use the pill style using straight hover color in bars that are just one icon high but using circles on hover for items that are in larger containers. Please update the UIS for this and upload to this issue when done. 

As for resize buttons, @jenniferhoang is in the process of updating that design. We talked about using a menu style UI that floats in front of the user, rather than having the resize icons attached to the bottom edge of the browser window. So that will change and be more consistent with the transport control UI.

**Comment by jenniferhoang** [comment]
@MortimerGoro thank you for catching these! 

UIS-41 Resize Mode has been updated
![screen shot 2018-10-19 at 1 45 19 pm](https://user-images.githubusercontent.com/41343760/47244114-319b5f80-d3a9-11e8-8adb-911786e3f398.png)

I also updated UIS-43 360 Movie Mode (scroll all the way to the bottom please!)
![screen shot 2018-10-19 at 2 13 25 pm](https://user-images.githubusercontent.com/41343760/47244119-395b0400-d3a9-11e8-85f8-a069a8b2ff05.png)

Please see attached documents for details and let me know if you have any questions!
[UIS-41 Resize Mode_002.pdf](https://github.com/MozillaReality/FirefoxReality/files/2497373/UIS-41.Resize.Mode_002.pdf)
[UIS-43 360 Movie Mode_004.pdf](https://github.com/MozillaReality/FirefoxReality/files/2497374/UIS-43.360.Movie.Mode_004.pdf)

**Comment by MortimerGoro** [comment]
@thenadj @jenniferhoang @cvan I find the current spec for the mute button confusing:
- If you click the volume button it shows the volume slider
- Then the same button used to open it becomes mute or unmute. This is not consistent with the others buttons, where clicking it again hides the opened menu (I think this wasn't specified in the spec but I'm doing it that way)
- How do you close the volume slider if the button becomes mute/umute

A solution could be include the mute/unmute in the slider UI itself, and use the pile menu button to show/hide the slider. What do you think?

**Comment by MortimerGoro** [comment]
@thenadj @jenniferhoang Another issue I found while implementing this is that the specified sizes in the specs are very hard to read in VR (I'm specially talking about the vertical menus to select brightness or video modes). I'm going to scale the size so they are easier to read. 

As they have to become bigger, putting them below the URL bar doesn't work anymore because they are too much at the bottom. I'm going to change them so they are above the URL bar. That fixes the problem. They hide part of the browser window when opened but after trying I don't think it's a problem. Oculus Browser also has that kind of menus (check the brightness selector while in their full screen video UI)

**Comment by thenadj** [comment]
@MortimerGoro Attached is a user flow that Jenni created to better help you understand the sequence of the volume control slider and the mute button. 
[UF-32 Volume Controls in Transport Controls_001.pdf](https://github.com/MozillaReality/FirefoxReality/files/2511820/UF-32.Volume.Controls.in.Transport.Controls_001.pdf)

**Comment by thenadj** [comment]
@MortimerGoro 
We discussed your concerns about the menu placement and size and will rethink the layout and create an updated version that works better for VR.

**Comment by MortimerGoro** [comment]
> @MortimerGoro Attached is a user flow that Jenni created to better help you understand the sequence of the volume control slider and the mute button.
> UF-32 Volume Controls in Transport Controls_001.pdf

@thenadj Thanks for the user flow, I understand it better now :)

**Comment by jenniferhoang** [comment]
@MortimerGoro The UF-32 flow is the same interaction as Youtube just in case you need extra reference! I added the screen recording in this file:

[UIS-43 Mute Icon & Youtube Screen Recording.zip](https://github.com/MozillaReality/FirefoxReality/files/2512482/UIS-43.Mute.Icon.Youtube.Screen.Recording.zip)

Please see updated UIS-43_005 for volume:
[UIS-43 360 Movie Mode_005.pdf](https://github.com/MozillaReality/FirefoxReality/files/2512500/UIS-43.360.Movie.Mode_005.pdf)

We made a few visual tweaks. Please note that there is a different icon for mute (attached in ZIP file above) and the alignment of the volume slider is aligned with the transport controls rather than the button.

![screen shot 2018-10-24 at 3 00 36 pm](https://user-images.githubusercontent.com/41343760/47464283-9980ea00-d79d-11e8-9062-7b5d1c1351ba.png)

**Comment by cvan** [comment]
![image](https://user-images.githubusercontent.com/203725/47946331-7e158d80-dec7-11e8-92a7-bc31bb1c977b.png)

I notice that the scrub backwards says `10` and the scrub forwards says `10`. should it be `10` in both spots?

**Comment by MortimerGoro** [comment]
Done

**Comment by avrignaud** [comment]
@MortimerGoro What exactly was done? We want to leave the media player with 10 second skip back, 30 second skip forward. Hoping that wasn't changed, and you're referring to something else? Thanks!

**Comment by cvan** [comment]
> @MortimerGoro What exactly was done? We want to leave the media player with 10 second skip back, 30 second skip forward. Hoping that wasn't changed, and you're referring to something else? Thanks!

@avrignaud: @MortimerGoro implemented it per your proposal and Nadja's design.

by `Done` he means that all of this Media Controls work has landed into `master` (since last week). @caseyyee and I have been rigorously testing it for bugs and to test the new YouTube videos in the Content Feed pipeline for 1.1.

the media controls seeking was something else. (I probably should've asked offline instead.)

**Comment by avrignaud** [comment]
Awesome, thanks for clarifying!
