### ISSUE TITLE
UR Finding: Users expect to be able to save bookmarks

### ISSUE THREAD

**Issue by avrignaud** [MozillaReality/FirefoxReality#347]
UR Finding: Users expect to be able to save bookmarks. Explore implementing Favorite/Bookmark support.

**Comment by fernandojsg** [comment]
I was discussing with @cvan about the idea on having bookmarks that will go directly to the content feed page. So for the MVP we won't need a specific UI for that, we could just add a new section on the content feed, and manage the interaction with them (like removing or even rename them) from the page it self instead of the FxR UI.
We will just need a button on the chrome to save these bookmarks to be shown on the CF. 
I feel the same for history. As after using it intensively lately I feel these two options are hugely needed, even more when you reset the page you were navigating when quitting the browser.
So the lowest hanging fruit for this could be CF and then explore other UI options in the future that I guess will require more work both on the UI/UX and on the engineering side.

**Comment by bluemarvin** [comment]
GeckoView has an API for restoring session state on restart, we just aren't using it yet (actually, the multiprocessor switch in the developer settings is using it 🙂 )

**Comment by fernandojsg** [comment]
yeah that could be handy, but still when testing content and knowing how hard is to type on VR, sometimes I want to visit my three daily pages like redit, twitter, news and I need to type them one by one. So if we could get them from the history and show on "recently" on the content feed, or adding to bookmarks using the api that gecko should have for that but just showing them on the new tab page instead of having a proper ui for that would be handy.
Actually it's how firefox desktop is working right now right? having the recently used pages or top sites there.

**Comment by bluemarvin** [comment]
I wasn't disagreeing with you other points, I was just stating we could save state between runs if we wanted to.

**Comment by fernandojsg** [comment]
Okok I just wanted to clarify, just in case 😄

**Comment by MortimerGoro** [comment]
I like this idea a lot. I'm missing this functionality or autocompletion a lot when using the browser.

It would be nice to have something minimal for V1. 

cc @bluemarvin does GV expose some function such as runJavaScript()? we could send some JSON that way

**Comment by bluemarvin** [comment]
Currently there is no way for a page to send any information back to GV. I think that is on the road map so that on-error pages and about: pages can be more interactive. I don't think there is a way to do JavaScript injection either at this time (which I think is what you are asking). But I don't think we need either for history or bookmark pages. I assume we could just generate the whole page each time and load it as data? Being able to remove/edit with out reloading the page would require a way for the page to communicated back to FxR.

**Comment by MortimerGoro** [comment]
Yes, I meant JavaScript injection.

With `load it as data` do you mean capture the URL content into a string, inject our JSON in a placeholder and use that instead of a live URL when calling session.loadURL()?

**Comment by bluemarvin** [comment]
I don't know we would have to try it. But we could also write the page out to the cache and load locally if `loadData()` doesn't work.

**Comment by fernandojsg** [comment]
I've opened an issue specifically for the content feed proposal: https://github.com/MozillaReality/FirefoxReality/issues/442 so we could leave this one as generic for the FxR chrome UI/UX

**Comment by cvan** [comment]
I had a little fun with this for an hour or so yesterday. a WIP branch with a Bookmark icon in the URL bar but still need to hook up to the bookmarks engine or reinvent a lightweight persistent data structure (`get`/`set`) keep a local storage using SQLite/whatever. (or send data to the Home frame): https://github.com/MozillaReality/FirefoxReality/compare/master...cvan:bookmarks

I responded to the ContentFeed issue #50:  https://github.com/MozillaReality/ContentFeed/issues/50#issuecomment-417101452

**Comment by cvan** [comment]
and see this possible approach: https://github.com/MozillaReality/FirefoxReality/issues/442#issuecomment-417102825

**Comment by cvan** [comment]
do we have a design spec for this? I can finish my branch (based on the WIP history branch), if we decide where to place the Bookmark icon (I borrowed the SVGs that Firefox puts in the desktop URL bar) and a spot to retrieve a list of Bookmarks.

see the prior art in Firefox, Oculus Browser,  Samsung Internet Browser, and even the latest Chrome for iOS.

**Comment by avrignaud** [comment]
Design is underway, but we need a meeting to discuss further. I also moved this to the Needs Design column for tracking.

**Comment by avrignaud** [comment]
@keianhzo Are bookmarks on track to be implemented for 1.1, or are we still waiting for anything? Just trying to understand current state.

**Comment by thenadj** [comment]
@avrignaud This issue is related and where most of the tabs/bookmarks conversation is happening.  https://github.com/MozillaReality/FirefoxReality/issues/635#issuecomment-430399960

Where should I post the updated design?

**Comment by avrignaud** [comment]
@thenadj Here is fine! Just tag the engineers as well please. :)

**Comment by keianhzo** [comment]
@avrignaud I'm working on it but we still need a final UI spec with styles, dimensions, etc

**Comment by avrignaud** [comment]
Believe @thenadj is doing a pass now after meeting yesterday, think it
should be here ASAP!
-- 
Andre Vrignaud — Head of Mixed Reality Platform Strategy | Emerging
Technologies | Mozilla
avrignaud@mozilla.com | +1 (206) 245-6067 <%2B1.206.245.6067> | Skype:
andrevrignaud

**Comment by thenadj** [comment]
Yes, we'll have a UI spec by eod today.

**Comment by cvan** [comment]
@thenadj UI spec by EOD sounds great - thank you!

if possible, it'd be super helpful for our v1.1 localisation (L10n) efforts, if you could double check that are aren't any text strings missing for Bookmarks in this list that you and Jenni think ought to be added.

here are all of the possible L10n strings that @keianhzo added for text that can appear in the UI (subject to change) for Bookmarks:

```xml
    <!-- This string is displayed as the title of the Bookmarks List, which contains the user's bookmarked websites. -->
    <string name="bookmarks_title">Bookmarks</string>

    <!-- This string is displayed in a tooltip that appears when a user hovers
         over an icon representing 'Remove Bookmark' for an individual bookmark
         item listed in the Bookmarks List. -->
    <string name="bookmarks_remove">Remove Bookmark</string>

    <!-- This string is displayed in a tooltip that appears when a user hovers
         over an icon representing 'Edit This Bookmark' for an individual bookmark
         item listed in the Bookmarks List. -->
    <string name="bookmarks_edit">Edit This Bookmark</string>

    <!-- This string is displayed as placeholder text in the search field in the Bookmarks List. -->
    <string name="bookmarks_search">Search Bookmarks</string>

    <!-- This string is displayed in a tooltip in the bookmark button in the URL bar. -->
    <string name="bookmarks_bookmark">Bookmark This Page</string>

    <!-- This string is displayed in the Bookmarks List for as the header of the most recently
         bookmarked items. -->
    <string name="bookmarks_recent">Recently Bookmarked</string>

    <!-- This string is displayed in the Bookmarks List as a tooltip of the button for showing
         all the bookmarks. -->
    <string name="bookmarks_show_all">Show All Bookmarks</string>

    <!-- This string is displayed as the title of the History List. -->
    <string name="history_title">History</string>

    <!-- This string is displayed in the History List as the header for the items visited today. -->
    <string name="history_today">Today</string>

    <!-- This string is displayed in the History List as the header for the items visited in the last week. -->
    <string name="history_week">Last 7 Days</string>

    <!-- This string is displayed in a tooltip that appears when a user hovers
         over an icon representing 'Remove From History' for an individual history
         item listed in the History List. -->
    <string name="history_remove">Remove From History</string>

    <!-- This string is displayed as placeholder text in the search field in the History List. -->
    <string name="history_search">Search History</string>

    <!-- This string is displayed in a context menu when long-pressing on a link in a website. -->
    <string name="bookmark_link">Bookmark This Link</string>

    <!-- This string is for items that were recently modified across the app (e.g., in History, Downloads, Bookmarks, etc.). -->
    <string name="recently_modified">Recently Modified</string>

    <!-- This string is for the table column name (in the browser's 'Bookmarks' list) for the 'Name' of the bookmarked website. -->
    <string name="col_name">Name</string>

    <!-- This string is for the table column name (in the browser's 'Bookmarks' list) for the 'Tags' of the bookmarked website. -->
    <string name="col_tags">Tags</string>

    <!-- This string is for the table column name (in the browser's 'Bookmarks' list) for the 'Location' (or 'URL' or 'Address') of the bookmarked website. -->
    <string name="col_url">Location</string>

    <!-- This string is for the table column name (in the browser's 'Bookmarks' list) for the date of when the bookmarked website was most recently visited. -->
    <string name="col_most_recent_visit">Most Recent Visit</string>

    <!-- This string is for the table column name (in the browser's 'Bookmarks' list) for the date of when the website was bookmarked. -->
    <string name="col_date_added">Added</string>

    <!-- This string is for the table column name (in the browser's 'Bookmarks' list) for the date of when the bookmarked website was last edited. -->
    <string name="col_date_last_modified">Last Modified</string>

  <!-- This string is for the tooltip that appears when the user hovers over the 'Bookmarks' icon in the
         browser's navigation bar. The button it labels, when pressed, opens a list view of the user's saved
         Bookmarks. -->
    <string name="bookmarks_tooltip">Bookmarks</string>
```

many thanks for all of your help!

**Comment by thenadj** [comment]
@keianhzo @cvan @avrignaud 
Attached is the updated User Flow Diagram for the Bookmarks. We kept the file name "bookmarks, tabs, downloads, history", as these items will be added shortly after v1.1, but removed everything other than bookmarks for the flow. Please take a look and send any last feedback so that we can finalize the UI specs today. 

[UF-31 Tabs, Bookmarks, History, Downloads_011.pdf](https://github.com/MozillaReality/FirefoxReality/files/2562671/UF-31.Tabs.Bookmarks.History.Downloads_011.pdf)

**Comment by caseyyee** [comment]
Looks good, though I would change the icon in the tray to something similar to what we have on desktop:

![image](https://user-images.githubusercontent.com/1560884/48217397-16829680-e33c-11e8-846c-d48d24e7d8c3.png)

The star already represents bookmark state in the URL bar where as the icon in tray is a user action that opens to the bookmark page/UI. They should not share the same icon, that would be confusing.

**Comment by cvan** [comment]
@caseyyee: good call

here are the SVG source files for those icons used in Firefox:

- https://dxr.mozilla.org/mozilla-central/source/browser/themes/shared/places/bookmarksToolbar.svg
- https://dxr.mozilla.org/mozilla-central/source/browser/themes/shared/places/bookmarksMenu.svg

**Comment by keianhzo** [comment]
@thenadj Whenever is ready please attach the final spec with icons, measures, buttons styles, colors, etc.

**Comment by thenadj** [comment]
Thanks for all the feedback. We'll update the icon and finalize the UI spec today. I'll upload it to this issue once it's ready.

**Comment by jenniferhoang** [comment]
@keianhzo Please see attached

Here are the Specs: 
[UIS-62 Bookmarks_001.pdf](https://github.com/MozillaReality/FirefoxReality/files/2564587/UIS-62.Bookmarks_001.pdf)

Here is the User Flow Diagram:
[UF-31 Tabs, Bookmarks, History, Downloads_012.pdf](https://github.com/MozillaReality/FirefoxReality/files/2564602/UF-31.Tabs.Bookmarks.History.Downloads_012.pdf)

Here are the assets:
[UIS-62_001 Assets.zip](https://github.com/MozillaReality/FirefoxReality/files/2564590/UIS-62_001.Assets.zip)

Please note that I've had to make a few changes other specs in order to implement this...

Added the Bookmark (star) icon into the URL bar (UIS-21)
[UIS-21 Window w Controls Below & Thumbnails_014.pdf](https://github.com/MozillaReality/FirefoxReality/files/2564594/UIS-21.Window.w.Controls.Below.Thumbnails_014.pdf)
<img width="498" alt="screen shot 2018-11-08 at 8 26 29 pm" src="https://user-images.githubusercontent.com/41343760/48243322-a0f6e480-e394-11e8-9aec-466ef65a68ba.png">

Changed the visual design of the tray and added a bookmarks icon. Please keep the same placement as before.
[UIS-26 Mini Tray_007.pdf](https://github.com/MozillaReality/FirefoxReality/files/2564598/UIS-26.Mini.Tray_007.pdf)
<img width="554" alt="screen shot 2018-11-08 at 8 28 14 pm" src="https://user-images.githubusercontent.com/41343760/48243360-d7346400-e394-11e8-939e-c7c94edba0ed.png">

Updated the tooltips for the tray.
[UIS-40 Tooltips_003.pdf](https://github.com/MozillaReality/FirefoxReality/files/2564600/UIS-40.Tooltips_003.pdf)
<img width="258" alt="screen shot 2018-11-08 at 8 29 26 pm" src="https://user-images.githubusercontent.com/41343760/48243385-04811200-e395-11e8-9a02-92783ab7b206.png">

Please let me know if you need anything else!

**Comment by cvan** [comment]
## UF-31.012

### 200, 300:
remove 200-300

### 400:
go from 100 -> 400. I like the tooltip notification.

### 600:
- can we add the hover/selected states to reflect those in UIS-62.001?
- can we remove the `Delete All` button, as it's error prone and likely rare use case. might make for a good addition to `Privacy & Security` later. (FWIW, Oculus Browser doesn't have a `Delete All Bookmarks` option.)
- keep trash icons (`Delete` buttons) for each row but show the trash icon only when the row is highlighted/hovered.
    ![image](https://user-images.githubusercontent.com/203725/48245253-cab50900-e39e-11e8-9a0b-4857608cac73.png)
- and can we move the URL to a separate line below the Name (similar to the style in the Search Suggestions)?
    ![image](https://user-images.githubusercontent.com/203725/48245306-fd5f0180-e39e-11e8-91e9-54eb65579e78.png)

### 1300:
technical note/question to confirm: when the user goes Back in History, they go to the page that was opened previously before the Bookmarks List was opened.

<hr>

## UIS-62

postpone/skip for now:
- `Edit Bookmark Dialog`
- `New Bookmark Dialog`

<hr>

I'll defer the rest of the technical feasibility to @keianhzo.

thanks for the awesome work here, @jenniferhoang and @thenadj!

**Comment by thenadj** [comment]
Ok, thanks @cvan for your feedback. Attached is the updated UF-31.013 incorporating all of your feedback. Hoping this is it. Please take another look at it and if everything is final @jenniferhoang will update final UIS-62 tomorrow. 

Hopefully this is close enough for @keianhzo to get started. 

[UF-31 Tabs, Bookmarks, History, Downloads_013.pdf](https://github.com/MozillaReality/FirefoxReality/files/2564857/UF-31.Tabs.Bookmarks.History.Downloads_013.pdf)

**Comment by cvan** [comment]
@jenniferhoang @thenadj very excellent. this looks fantastic for 1.1. thanks so much both of you for your quick turnaround and flexibility.

I'm excited to see the post-1.1 designs implemented when we get Tabs. soon! 🔜 😄

**Comment by thenadj** [comment]
Thx @cvan 
@jenniferhoang - The simplified UF-31.013 is ready as the base for one more round of updates to UIS-62. Shortly after we'll add tabs, history and downloads back, so none of the work leading up to this is wasted. :) Please add to this card when done. Thx much for all your hard work on this.

**Comment by jenniferhoang** [comment]
Ok Please see attached. I made a few visual changes and updated the UIS

Here are the Specs: 
[UIS-62 Bookmarks_002.pdf](https://github.com/MozillaReality/FirefoxReality/files/2567320/UIS-62.Bookmarks_002.pdf)

Here is the User Flow Diagram:
[UF-31 Tabs, Bookmarks, History, Downloads_013.pdf](https://github.com/MozillaReality/FirefoxReality/files/2567322/UF-31.Tabs.Bookmarks.History.Downloads_013.pdf)

Here are the assets:
[UIS-62_001 Assets.zip](https://github.com/MozillaReality/FirefoxReality/files/2564590/UIS-62_001.Assets.zip)

And other specs that have been updated in order to implement this feature...

Added the Bookmark (star) icon into the URL bar (UIS-21)
[UIS-21 Window w Controls Below & Thumbnails_014.pdf](https://github.com/MozillaReality/FirefoxReality/files/2564594/UIS-21.Window.w.Controls.Below.Thumbnails_014.pdf)

Changed the visual design of the tray and added a bookmarks icon. Please keep the same placement as before.
[UIS-26 Mini Tray_007.pdf](https://github.com/MozillaReality/FirefoxReality/files/2564598/UIS-26.Mini.Tray_007.pdf)

Updated the tooltips for the tray.
[UIS-40 Tooltips_003.pdf](https://github.com/MozillaReality/FirefoxReality/files/2564600/UIS-40.Tooltips_003.pdf)

I'll start working on the next iteration for v1.2.

**Comment by caseyyee** [comment]
Oh, one quick one: Probably swap the settings and bookmark icon positions in the tray.

Looks good otherwise!

**Comment by thenadj** [comment]
@caseyyee I agree, settings is traditionally to the right while PB and Bookmarks are related in terms of functionality (bringing up content in a new browser instance). No need to update the UI Spec. @keianhzo please note the new order of the tray icons: Help, PB, Bookmarks, Settings

**Comment by thenadj** [comment]
We are aware that @keianhzo is still working on some of the visuals in bookmarks like line spacing for titles/URL sections and hover over delete icon. In addition, here are a few more bugs that showed up for bookmarks. See attached document for details. 

[Bug-18 Bookmarks_001.pdf](https://github.com/MozillaReality/FirefoxReality/files/2591088/Bug-18.Bookmarks_001.pdf)
