### ISSUE TITLE
Hand Input in WebXR

### ISSUE THREAD

**Issue by daoshengmu** [MozillaReality/FirefoxReality#3488]
**Is your feature request related to a problem? Please describe.**
Oculus Browser are doing experiments for [Hand Input in WebXR](https://github.com/immersive-web/webxr-hands-input/blob/master/explainer.md). It is going to be a draft in spec.

**Describe the solution you'd like**
Adding this experimental optional feature in WebXR. We need to implement this new in Gecko and some engineering works in `OculusVRDelegate`. I think we also need to support #2505 as well, for the case users should activate hand tracking feature in Quest first.

**Comment by lordbron** [comment]
A quick question here. If I'm reading this correctly, the team is considering both the native Oculus VrApi for hands (possibly first since that API is baked and live) as well as separately supporting hands in WebXR (based on spec) to have parity with the Oculus browser? Would this wind up being two separate branches merged and released independently in different Reality versions?

**Comment by daoshengmu** [comment]
The link of webxr-hand-input spec draft, https://immersive-web.github.io/webxr-hand-input/

**Comment by daoshengmu** [comment]
> A quick question here. If I'm reading this correctly, the team is considering both the native Oculus VrApi for hands (possibly first since that API is baked and live) as well as separately supporting hands in WebXR (based on spec) to have parity with the Oculus browser? Would this wind up being two separate branches merged and released independently in different Reality versions?

@lordbron This issue will mainly focus on enabling hand input when using Firefox Reality to visit WebXR web content.
