### ISSUE TITLE
Remove service-telemetry

### ISSUE THREAD

**Issue by daoshengmu** [MozillaReality/FirefoxReality#3519]
**Is your feature request related to a problem? Please describe.**
We already migrated our existing telemetry to Glean (#2278), and service-telemetry is going to deprecated in Q2.

**Describe the solution you'd like**
Remove it in v.12

**Comment by daoshengmu** [comment]
@Dexterp37 I am curious if we still need to keep [LegacyTelemetry.INSTANCE.clientId().set](https://github.com/MozillaReality/FirefoxReality/blob/57b6b793b839f4ed0b533edf0e6f09e7568c5f30/app/src/common/shared/org/mozilla/vrbrowser/telemetry/GleanMetricsService.java#L75). Because `TelemetryHolder` is going to be deprecated, I would guess we would be no more chance to the client id from the `TelemetryHolder`.

**Comment by Dexterp37** [comment]
> 
> 
> @Dexterp37 I am curious if we still need to keep [LegacyTelemetry.INSTANCE.clientId().set](https://github.com/MozillaReality/FirefoxReality/blob/57b6b793b839f4ed0b533edf0e6f09e7568c5f30/app/src/common/shared/org/mozilla/vrbrowser/telemetry/GleanMetricsService.java#L75). Because `TelemetryHolder` is going to be deprecated, I would guess we would be no more chance to the client id from the `TelemetryHolder`.

This is a great question. This really depends on the intent here: when removing legacy telemetry, should we keep sending the legacy client id with Glean? That's a good question for data stewards/shredder project.

@chutten, what is the expectation here after we remove legacy telemetry from Firefox Reality? Should we keep sending that client id with the Glean deletion request?

Regardless of that, I believe we should be fine even if we deleted the [LegacyTelemetry.INSTANCE.clientId().set](https://github.com/MozillaReality/FirefoxReality/blob/57b6b793b839f4ed0b533edf0e6f09e7568c5f30/app/src/common/shared/org/mozilla/vrbrowser/telemetry/GleanMetricsService.java#L75) line, after it has run at least once: since the `legacy_telemetry.client_id` metric has a `ping` lifetime, it won't be cleared until the `deletion-request` is sent.

I would recommend to test this before deploying the new binary :)

**Comment by chutten** [comment]
When we asked things like this in the past the guidance was "No, you shouldn't hold on to more information to better serve deletion requests. The whole point is to hold on to _less_ data", but I'll ask about this specifically.

For now proceed with your deprecation on the assumption that you don't have to keep it around.

**Comment by chutten** [comment]
Yup! Confirmation from Trust that we should stop sending that client_id as soon as we don't need it for our own purposes. Keeping it for potential future deletion requests is not necessary and is kinda missing the point of deletion requests : )

**Comment by daoshengmu** [comment]
> Yup! Confirmation from Trust that we should stop sending that client_id as soon as we don't need it for our own purposes. Keeping it for potential future deletion requests is not necessary and is kinda missing the point of deletion requests : )

Thanks for sharing this information. :)
