### ISSUE TITLE
Use WebExtensionController.installBuiltIn() inplace of GeckoRuntime.registerWebExtension()

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#3547]
## Configuration

Firefox Reality version: df4c777c2b95dd34368d9cc56142939a5824e466

## Current Behavior

The PR #3498 regressed our usage of Web Extenstions API. We are now using the deprecated `GeckoRuntime.registerWebExtension()` when we were using `webExtensionController.installBuiltIn()`

## Expected Behavior

We should be using the new API.

**Comment by csadilek** [comment]
We're working on updating A-C to switch to `installBuiltIn`, which requires a few changes to both extensions and our components. I've summarized the steps here: https://github.com/mozilla-mobile/android-components/issues/6356

The branch is basically ready, but since `installBuiltIn` persists the extension now (unlike registerWebExtension which is transient), I am working on some gradle intregration to make sure the manifest version is updated with every change, otherwise the extension wouldn't be re-installed. We're planning on using `ensureBuiltIn` which installs conditionally, only if needed, to save the cost of installing on every startup.

**Comment by csadilek** [comment]
Just a quick update: A-C 51.0.0 is now using `installBuiltIn` (we're actually using `ensureBuiltIn` which re-installs if a new version is present). All our built-in extensions in A-C are now installed using the new API, and the deprecated `registerWebExtensions` is no longer used. So, you should be able to switch API calls whenever you're ready for the latest A-C version.

**Comment by keianhzo** [comment]
Thanks @csadilek We are currently add-ons support so v51 will land when that does. That will also include the `ensureBuiltIn` update.

**Comment by keianhzo** [comment]
This has been already fixed when adding add-ons support
