### ISSUE TITLE
The Spider-Man Web-VR content listed as a top site does not work.

### ISSUE THREAD

**Issue by plwt** [MozillaReality/FirefoxReality#3570]
## Configuration

Firefox Reality version: 10
Firefox Reality build ID: bda5ecfa

Hardware: Pico Neo 2

## Steps to Reproduce

1. Open Firefox Reality
2. Select the Spider-Man Web-VR content from the homescreen
3. Try to interact with the content.

## Current Behavior

You are standing at a crossroads and nothing happens - aside from an occasional vertical bounce (not linked to any action with the controllers).  There is no game or content to interact with.

## Expected Behavior

There is something vaguely Spider-Man like that happens.

## Possible Solution

If not possible to resolve, switch out the content with something else as this looks bad for Firefox at present.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by emstanley** [comment]
Reach out to Fernando to see if he can submit a PR that fixes this for PR.

**Comment by SeburoSUMO** [comment]
I am happy to where I can with this, and certainly able to help test.

**Comment by bluemarvin** [comment]
> I am happy to where I can with this, and certainly able to help test.

The problem is page does device sniffing and doesn't support pico. We previous submitted a PR to fix the page on the Quest.

**Comment by fernandojsg** [comment]
The problem is that the app is just adding control support for `vive`, `windows mr` and `oculus touch` controllers: https://github.com/talkol/spiderman/blob/master/hand.js#L238-L240

In order to add that support we need to add support on aframe as they currently lack support for htc focus, and pico devices. 
It's a bit tedious process as we should submit an implementation, for each controller, similar to for example the oculus touch controllers (See below), so it will take a while :\
https://github.com/aframevr/aframe/blob/master/src/components/oculus-touch-controls.js
https://github.com/aframevr/aframe/blob/master/docs/components/oculus-touch-controls.md
https://github.com/aframevr/aframe/blob/master/tests/components/oculus-touch-controls.test.js
