### ISSUE TITLE
[Babylon XR] Scenes move in the opposite direction of the headset movement in immersive mode

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#3578]
**[Affected Versions]:**
- Firefox Reality version 10.2 RC4 (6adc5cc8)
- Firefox Reality version 11-141782234 (34813811)
- Firefox Reality version 10.2 RC3 (7523a32d)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- HTC Vive Focus Plus - Android 7.1.2
- Pico G2 4K - Android 8.1.0
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Navigate to https://doc.babylonjs.com/how_to/webxr_demos_and_examples 
2. Scroll down to the “Babylon.js scenes with XR support” section.
3. Play a webxr example in immersive mode.
4. Move the headset up/down or right/left.
5. Observe the behavior.

**[Expected results]:**
- The scene is moving in the same direction as the headset movement.

**[Actual results]:**
- The scene is moving in the opposite direction of the headset movement.

**[Notes]:**
- The issue is also reproducible in the latest main and in v10.2 RC3.
- The issue is not reproducible on the oculus browser.
- The issue is not reproducible with examples from other sections.
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/18_WZ6BQ-Eh00KiMSDHcCQh-DE4Z_prAL/view?usp=sharing).

**Comment by daoshengmu** [comment]
It doesn't look like a regression. I have checked FxR 10.0 and 10.1. Both of them are the same with 10.2. I also reverted the change from [Bug 1641593](https://bugzilla.mozilla.org/show_bug.cgi?id=1641593) (it seems to be the only change is related to our view pose), but it still doesn't help. I would guess BabylonJS does some changes in their library. OB works well with BabylonJS though.

**Comment by daoshengmu** [comment]
We will be good if we mark [viewerOrientation.Invert();](https://searchfox.org/mozilla-central/rev/5a4aaccb28665807a6fd49cf48367d47fbb5a19a/dom/vr/XRFrame.cpp#78). But, it will make other WebXR samples do not work properly. We didn't add any special things here, we just return the headset sensor data here. It is hard to tell if we don't have their source code.

**Comment by MortimerGoro** [comment]
It seems that the Basic scene with XR support is failing too now

**Comment by fernandojsg** [comment]
It seems our code to decompose the transform view matrix is incorrect. WebXR samples and three.js examples are using directly the transform view matrix, while Babylon is composing the matrix themselves by using `pose.orientation and position`
I tried to decompose the transform matrix we return, and in fact it differs from the value we return in `orientation`.
I opened an issue Babylon to keep track of it too: https://github.com/BabylonJS/Babylon.js/issues/8469#issuecomment-653609802

**Comment by daoshengmu** [comment]
@fernandojsg Good catch! Gecko's decompose matrix do have a bug when returning an orientation. [1][2]  Can you help make sure if they are using `XRViewerPose.Transform.orientation` and `XRViewerPose.Transform.position` to get an orientation and a position? Or instead, they compose the orientation and position that were from `XRViewerPose.Transform` matrix, then decompose them again from a `DomMatrix` or something. I guess they are using later. Because I was thinking we also have a bug in `DomMatrix` when doing decompose.

If the decomposing matrix function is we expose from a WebAPI. That's a Gecko bug that I was investigating.

[1] https://searchfox.org/mozilla-central/rev/e11d919cdc8a909354eb2c3e19904d9229c55d88/dom/vr/XRRigidTransform.cpp#66
[2] https://searchfox.org/mozilla-central/rev/e11d919cdc8a909354eb2c3e19904d9229c55d88/dom/vr/XRRigidTransform.cpp#134

**Comment by fernandojsg** [comment]
They are using both, for the view matrix for each eye they use the `view.transform.orientation/position`: https://github.com/BabylonJS/Babylon.js/blob/master/src/XR/webXRCamera.ts#L184-L185
But they also use `pose.transform.orientation/position`, not sure why, maybe to update the "camera rig" object holding the two cameras (left/right): https://github.com/BabylonJS/Babylon.js/blob/master/src/XR/webXRCamera.ts#L130-L133

**Comment by daoshengmu** [comment]
I have filed a bug here (https://bugzilla.mozilla.org/show_bug.cgi?id=1650714). I rewrite our `decompose` and `SetRotationFromQuaternion` from Gecko and remove our existing `invert()` code. After that, Babylon.js can see the proper result. But, we still need to refine our ViewPose matrix a bit though.

**Comment by RaananW** [comment]
> They are using both, for the view matrix for each eye they use the `view.transform.orientation/position`: https://github.com/BabylonJS/Babylon.js/blob/master/src/XR/webXRCamera.ts#L184-L185
> But they also use `pose.transform.orientation/position`, not sure why, maybe to update the "camera rig" object holding the two cameras (left/right): https://github.com/BabylonJS/Babylon.js/blob/master/src/XR/webXRCamera.ts#L130-L133

The reason why is because we internally support both left and right systems, and we also do a few calculations regarding global position and direction during the view matrix calculation. I am working on separating those to save the few CPU cycles of calculating the view matrix ourselves, but in the meantime we use the position and orientation.

**Comment by bluemarvin** [comment]
Fix will be in v11 rc8

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue with Firefox Reality version 11 RC8 (076802af) installed on Oculus Go, HTC Vive Focus Plus, Pico Neo2 and Pico G2 4K headsets.
Now, scenes move in the correct direction of the headset movement in immersive mode.
