### ISSUE TITLE
[HTC Vive Focus Plus] WebXR content can not be recentered

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#3616]
**[Affected Versions]:**
- Firefox Reality version 11 RC3 (f6453025)

**[Affected Platforms]:**
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Play the "Hello WebXR" card from Interactive Experience.
2. Enter immersive mode and move the headset in a different position horizontally.
3. Press and hold the grip button on the controller to recenter the view.
4. Observe the behavior.

**[Expected results]:**
- The view is recentered.

**[Actual results]:**
- The view is not recentered.

**[Notes]:**
- The issue is not reproducible on the other devices.
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1d3YfY1WbAyz2nuJqrez_wNKIyrBXc5qC/view?usp=sharing).

**Comment by bluemarvin** [comment]
This is working as expected. Unfortunately the Focus Plus does not have a built-in way to recenter like the regular Focus where you can press and hold the home button. To work around this we added the press and hold grip button our selves. Unfortunately this only works in non-immersive mode because when in immersive mode, the grip button must be available to the page.

**Comment by emstanley** [comment]
Closing as working as expected.
