### ISSUE TITLE
Show number of tabs opened

### ISSUE THREAD

**Issue by feiss** [MozillaReality/FirefoxReality#3700]
**Is your feature request related to a problem? Please describe.**

Tab management is a bit clunky. User doesn't know how many tabs are opened unless he opens the tabs panel. New tabs are opened frequently without noticing (despite the notification in the tray)

**Describe alternatives you've considered**
- I'm late to the discussion, but why tabs are not shown in the classic way? (on top of the window). This could remove the need of the tabs panel.
- At least, we could show how many tabs are opened.

**Comment by MortimerGoro** [comment]
We did a implementation with the classic tabs and the main problem was that the design felt a copy of a desktop browser on VR.

+1 for adding the number of tabs opened. But the main reason why we didn't show the number is because tabs received via "send to device" are unkown until we open the tabs (push notifications are not supported in HMDs yet), so showing the number could confuse users that are waiting to receive a tab

**Comment by bluemarvin** [comment]
I think not showing pushed tabs until the tab panel is opened is fine. But I also think the tab panel is sort of clunky compared to how Oculus handles. it. The main problem I have with the Oculus implementation is the tabs seem to be bound to a window which I really don't like.

**Comment by feiss** [comment]
@MortimerGoro my naive feeling is that being a copy of the desktop would be better than implementing a worse solution.. at least it would be convenient, easy and intuitive to the user.

@bluemarvin 👍

**Comment by bluemarvin** [comment]
Yes, no one liked the traditional approach with tabs on top.
