### ISSUE TITLE
UR Finding: Users would like resize window options in default view

### ISSUE THREAD

**Issue by avrignaud** [MozillaReality/FirefoxReality#371]
## Hardware

All

## Steps to Reproduce

Option to resize window in default view missing.

## Current Behavior

Option to resize window in default view missing.

## Expected Behavior

Allow users to resize window in default view. @thenadj has design, will add ASAP.

## Possible Solution

Use existing resize functionality and implement in default mode.

```
```

</details>

**Comment by nancyhang** [comment]
@thenadj please attach the design

**Comment by keianhzo** [comment]
Waiting for @thenadj design

**Comment by thenadj** [comment]
UI Spec and User Flow Diagram are attached.
[UIS-41 Resize Mode_001.pdf](https://github.com/MozillaReality/FirefoxReality/files/2324381/UIS-41.Resize.Mode_001.pdf)
[UF-20 Resize Mode_002.pdf](https://github.com/MozillaReality/FirefoxReality/files/2324385/UF-20.Resize.Mode_002.pdf)

**Comment by cvan** [comment]
Design question for @thenadj: can we consider not persisting the state of Settings Remembered (per [UF-20.900](https://github.com/MozillaReality/FirefoxReality/issues/371#issuecomment-416257060))?

## Recommendation

Do not persist storing the browser window size from a Resize Mode sesion because FxR's Resize Mode allows for arbitrary zooming in addition to presets, whereas *only* presets are available in Oculus Browser and Samsung Browser.

## Context

In PR #463, @keianhzo has implemented the Settings Remembered persistence correctly, per [UF-20.900](https://github.com/MozillaReality/FirefoxReality/issues/371#issuecomment-416257060).

I tested that both the Oculus Browser and Samsung Browser remember Browser Width and Browser Zoom Level, respectively. So, it seems to be an expected browser behaviour of saving and restoring the browser dimensions (in VR at least).

Because the UIS-41 Resize Mode allows for arbitrary zooming, this means that the resized browser window dimensions might make sense for the current page or browser session, but once the user has left that page (e.g., Amazon), you would expect to not have to enter Resize mode to reset to `1x` (the default). Because these Resize Presets and the Drag Handles are visible only in the separate mode and not from a drop-down (Oculus Browser) or button-click (Samsung Browser), this could make for a confusing experience when a user ends their session and launches Firefox Reality to see the New-Tab page in the browser look like this:

![image](https://user-images.githubusercontent.com/203725/45124241-649dd280-b11e-11e8-866b-140050ee2676.png)

<hr>

### Samsung Browser
Zoom options:
- Zoom Level 1
- Zoom Level 2
- Zoom Level 3

![Animation of Samsung Browser's Zoom Levels](https://user-images.githubusercontent.com/203725/45125068-b09e4680-b121-11e8-8521-f1bd6bbcf59b.gif)

### Oculus Browser
Browser widths:
- Narrow browser
- Medium browser
- Wide browser

![Animation of Oculus Browser's Browser Widths](https://user-images.githubusercontent.com/203725/45125170-24d8ea00-b122-11e8-9129-a42f96b41833.gif)

**Comment by thenadj** [comment]
I am ok not doing this for v1 but would like to usability test this and make a decision based on user feedback for future builds. Some users might want to change their default setting to be different that what we offer and it might be annoying if it goes away each time they return. We are also looking into user accounts where a user can have a number of settings that will persist across sessions.

**Comment by cvan** [comment]
Sounds good. Thanks!

Related issue:
- https://github.com/MozillaReality/FirefoxReality/issues/375

Helpful comment on Reddit as part of a larger thread on resizing:
- https://www.reddit.com/r/OculusGo/comments/8zccmj/comment/e2hsj7k
