### ISSUE TITLE
[Pico] DelightVR framework doesn't display controller model and couldn't interact when controller is connected

### ISSUE THREAD

**Issue by picoxr** [MozillaReality/FirefoxReality#3760]
## Configuration

Firefox Reality version:  release/11.2-rc2
Firefox Reality build ID:  3c188cc

Hardware: Pico-Neo2, Pico-G2 4K

## Steps to Reproduce

1. Keep controller connected.
2. Open up a video using DelightVR video frame work.
3. Try to click on the buttons on the video control panel

## Current Behavior

 
Couldn't see controller model displayed and headset control doesn't work either

## Expected Behavior

Can see controller model of Pico displayed and the controller can interact with the buttons on the panel.

## Context

1. When using delightVR videos on Quest, it displays the Oculus Touch controller model and can interactive correctly.
2. When using headset control on Pico device, the buttons are interacable.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by picoxr** [comment]
Is that DelightVR who need to add controller model into their player?

**Comment by bluemarvin** [comment]
I would guess Delight has to explicitly add new controllers since it doesn't look like they have a working fallback default. It is able to read the trigger on the controller so even though the controllers are not shown, using the head tracked pointer and clicking on the controller does work. Contacting them directly might be the best way to resolve this issue.
