### ISSUE TITLE
[Pico] The network name is not displayed in the information bar Wi-Fi tooltip

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#3775]
**[Affected Versions]:**
- Firefox Reality version 12 RC1 (cc3eab03)

**[Affected Platforms]:**
- Pico G2 4K - Android 8.1.0
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Using the controller, hover the pointer over the Wi-Fi icon.
2. Observe the tooltip.

**[Expected results]:**
- The tooltip displays the name of the network the headset is connected to.

**[Actual results]:**
- The tooltip displayed is “<unknown ssid>”

**[Notes]:**
- The issue is not reproducible on other devices.
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1e2zrTWuwEGvq9saFYCOd_PhO9f7PaTjE/view?usp=sharing).

**Comment by keianhzo** [comment]
In Android > 8 we need to request a location permission to be able to access the SSID, that's why it works in Oculus/HTC (7) but it doesn't in Pico (8) unless you have granted the location permission. We don't really ask for permissions unless it's strictly necessary so it doesn't make sense to request it just for that. We should think about a workaround for this.
