### ISSUE TITLE
Expose history to the content feed

### ISSUE THREAD

**Issue by fernandojsg** [MozillaReality/FirefoxReality#443]
As proposed for the bookmarks (https://github.com/MozillaReality/FirefoxReality/issues/442), but for the history. 
The content feed should be able to remove content from the list. It doesn't necessarily need to be a two-ways api as we could just blacklist some urls when deleting them from the content feed on the localstorage.

**Comment by keianhzo** [comment]
GV is getting a History API https://bugzilla.mozilla.org/show_bug.cgi?id=1494713. When this is closed we should open a new issue to track that and update.

**Comment by philip-lamb** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1494713 is done.

**Comment by cvan** [comment]
See discussion from the original PR from prior to the implementation of the GeckoView History API: https://github.com/MozillaReality/FirefoxReality/pull/457#issuecomment-447424317

This bug needs attention re: Privacy, Security, and UX. We may be able to close this. But even if we conclude that the Content Feed should feature History (instead of accessible from `about:history`, à la `about:bookmarks` / the Bookmarks button in the Tray), the work needs to be done in #614 to first use the android-components code.

**Comment by jvonitter** [comment]
tracking this in #759
