### ISSUE TITLE
FxR gets stuck exiting immersive mode

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#515]
## Hardware

Go and Daydream

## Steps to Reproduce

1. Go to site with immersive content.
2. Enter immersive mode.
3. Exit immersive mode.
4. Go to 2.

## Current Behavior

Eventually FxR will fail to exit immersive mode and all that will be visible is the spinner rotating very slowly.

## Expected Behavior

FxR should continue to enter and exit immersive mode.

**Comment by bluemarvin** [comment]
I could reproduce this issue with mrnmnm.com very reliably.

**Comment by larsbergstrom** [comment]
cc @MortimerGoro for some help when he's back :-)

This will be a ship blocker; Oculus is (rightly) requiring this fixed for store release.

**Comment by daoshengmu** [comment]
I am also investigating this kind of issue at #374. It seems like we need to refine our FxR VR threading sync and the watchdog mechanism.

**Comment by MortimerGoro** [comment]
I took a look today and it seems the problem is that FxR was receiving a extra frame after requesting exit from WebVR to Gecko. As FxR was rendering the loading spinner scene we were not releasing SurfaceTextures in that situation, which causes a WebGL freeze in a future frame.

Pushed https://github.com/MozillaReality/FirefoxReality/pull/520 so SurfaceTextures are correctly released when not a in WebVR rendering state (e.g. loading, exiting from WebVR, etc)
