### ISSUE TITLE
Deploy on Steam

### ISSUE THREAD

**Issue by benbucksch** [MozillaReality/FirefoxReality#552]
## Hardware
Windows MixedReality - HP VR1000

## Steps to Reproduce
Search on Steam for Firefox by going to
https://store.steampowered.com/search/?term=firefox

## Current Behavior
Firefox Reality is not available on Steam

This causes the following problems as effects:
* I need to sign up to a new third party store just to download Firefox Reality. I will not do that. This is a significant hurdle in installing Firefox Reality.
* Firefox Reality is not available in the store for my headset.

-> Cannot install Firefox Reality.

## Expected Behavior
Firefox Reality is available on Steam store, as a free download.

## Possible Solution
Deploy on Steam

## Context
Almost all users with a VR headset will already have a Steam account.

## Error Logs and Stack Traces
<details open>

```
```

</details>

**Comment by larsbergstrom** [comment]
Yes, if we choose to support desktop in the future with Firefox Reality, I would anticipate being available on all platforms.

**Comment by 13rac1** [comment]
Desktop is now supported: https://blog.mozilla.org/blog/2019/01/08/mozilla-announces-deal-to-bring-firefox-reality-to-htc-vive-devices/ Will it be on Steam?

**Comment by benbucksch** [comment]
Yeah, if you want distribution, you need to be on Steam.

**Comment by larsbergstrom** [comment]
While we are announcing support for Viveport now, there is certainly nothing that would preclude us from supporting Steam in the future. Stay tuned!

**Comment by benbucksch** [comment]
@larsbergstrom : That's great to hear! Do you mind to re-open this ticket?

**Comment by extraymond** [comment]
Any chance firefox reality gets deployed to steam?
The blog posts said that it was planned to be release [during summer](https://blog.mozvr.com/firefox-reality-coming-to-steamvr/).

Although **winter is not coming** at any moment, are there any updates on the original plan?

**Comment by philip-lamb** [comment]
Thanks for asking :-) It's still on our roadmap, and we'll be sure to let the community know when we have more to announce.

**Comment by extraymond** [comment]
@philip-lamb 

That's nice to here.
Allow me to make a bold request, will it be able to support desktop linux? Either via native app in the steam store or run the windows version via **proton** would be nice.

Since I'm not really expecting webVR support for firefox on desktop linux to be finished in the near future. It would be super nice to have a heavily developed browser that supports webVR.

I would love to volunteer for testing if there's any chance a non-officially hackery is required to help that become reality.

**proton**: Valve maintained wine runtime that allows linux to run windows app, supports up to dx11/vulkan and openvr api. Most of the wine games on steam can be launched with proton without issues without a sweat, so it would be nice to be able to test and hope it just works.

**Comment by extraymond** [comment]
@philip-lamb  Greetings from another summer, is there any updates on this? If any, are there any blockers that need testers or libraries that needed more testing? Would love to help testing.

**Comment by philip-lamb** [comment]
We've now released on Viveport for PC-connected VR, and have plans to support Steam soon. https://blog.mozvr.com/introducing-firefox-reality-pc-preview/

**Comment by frostworx** [comment]
@philip-lamb Including linux support on launch?

**Comment by TheBricktop** [comment]
hello, is there any possibility to deploy firefox reality to steam?
or at least install it from anywhere else as a exe?
