### ISSUE TITLE
Add support for popup blocking UI

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#593]
## Hardware

All

## Current Behavior

All popups are blocked.
## Expected Behavior

user should be prompted if a popup should be blocked.
## Possible Solution

GeckoView added a popup request the dialog delegate. FxR should add support for this so users can decide if a popup should be blocked. This should allow users to log in with facebook on 3rd party websites.

**Comment by caseyyee** [comment]
Flagging for UX, we'll need to look at doorhanger UI behavior for blocked popups.

**Comment by philip-lamb** [comment]
Implement interface https://mozilla.github.io/geckoview/javadoc/mozilla-central/org/mozilla/geckoview/GeckoSession.PromptDelegate.html#onPopupRequest-org.mozilla.geckoview.GeckoSession-java.lang.String-

**Comment by philip-lamb** [comment]
Moving to 1.3 P1.

**Comment by jvonitter** [comment]
Flow is ready: https://trello.com/c/EFuMA67f/409-uf-75-pop-up-blocking-override
Waiting on UIS for final design

**Comment by jvonitter** [comment]
Final design is done: https://trello.com/c/LserbZRw/428-uis-86-pop-up-blocking-override

**Comment by jvonitter** [comment]
[UIS-86](https://trello.com/c/LserbZRw/428-uis-86-pop-up-blocking-override) has been updated

**Comment by jvonitter** [comment]
One minor change here - instead of a button saying "Exceptions", it should say "Settings".

When a user selects Settings, they should see a list of sites they've acted on in the past. They can Allow or Block each site individually from that page, similar to this - 
![image](https://user-images.githubusercontent.com/48839872/66944009-29e4ba00-f001-11e9-9f9c-9d7da22d2d4c.png)

We don't need a search box, but you can re-use the other text on that page ^^.
@thenadj we should update the spec to match but there's no rush.

**Comment by jvonitter** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UIS-86 Pop-up Blocking Override](https://trello.com/c/LserbZRw/428-uis-86-pop-up-blocking-override)

**Comment by keianhzo** [comment]
@jvonitter Latest APK with switches: https://send.firefox.com/download/b2f578f2d5451e52/#T1QllBrOUiNXOAqBoUjddw

**Comment by thenadj** [comment]
@keianhzo Just reviewed this and it looks good. One small change I discussed with Janice. Let's rename the 'Settings' button to 'Advanced' just to differentiate it a bit from the Settings dialog the user is already in.

**Comment by jvonitter** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UIS-86 Pop-up Blocking Override](https://trello.com/c/LserbZRw/428-uis-86-pop-up-blocking-override)

**Comment by jvonitter** [comment]
I did a bit of hallway user testing on this and found it didnt go over well. Reopening so we can make some changes. UIS-86 has been updated.

1) remove the toggle from the exceptions list. if it's in the list, it's an exception. you can remove it from the list (with the X interaction you have here) to change that. I think the list is then called "Exceptions" both on the button and in the title of the dialog.
And
2. Instead of popping up a popup because we blocked a popup, let's put an icon in the URL bar that signals that we've blocked something. Clicking it would _then_ trigger the popup. that gives users a path to add that site to the exceptions list without having to type the url and without having to be interrupted by the popup
