### ISSUE TITLE
Update permissions dialog UI design

### ISSUE THREAD

**Issue by keianhzo** [MozillaReality/FirefoxReality#612]
## Hardware
All

## Current Behavior
The current permissions dialog UI is quite old and not matching the current app theme.

![46768900-d083d580-cc9e-11e8-8086-e79037e1d326](https://user-images.githubusercontent.com/837184/46815991-5164cf00-cd7c-11e8-9946-9600e50fee3d.png)

## Expected Behavior
Update the permissions dialog UI to match the rest of the app UI. This includes:

1. New dialog Spec
2. Icon for file access permission. This is what Android system is currently using for file read access request:

![46769098-83ecca00-cc9f-11e8-972b-66ab698e84c9](https://user-images.githubusercontent.com/837184/46816078-7e18e680-cd7c-11e8-8a4a-02fe39bb249f.png)

## Error Logs and Stack Traces
<details open>

```
```

</details>

**Comment by MortimerGoro** [comment]
@thenadj If we are going to update the permission UI I have some feedback that I found while using the product:

When I visit some pages normally I don't care about the permissions (e.g. a lot of webs ask for a localization permission, but I'm not interested unless it's a map or something very specific). This causes that the modal permission dialog to interrupt the browsing experience. I compare it with a full-screen interstitial that I need to close to continue browsing when I'm not interested in the permissions. If you see the permission prompt in Oculus Go, it's just a small box that doesn't interrupt the browsing and I think that it even autohides if you don't click on it.

IMO doing something like that would be more practical

**Comment by keianhzo** [comment]
@MortimerGoro Agree with the above but what happens with app permissions like storage access? The user needs to grant/reject so the page can load/show error. At the moment we are blocking the page load until we get a response from the user.

**Comment by MortimerGoro** [comment]
@keianhzo that's an internal permission, not asked by the web, right? I guess we can treat that one in a different way

**Comment by keianhzo** [comment]
So web permissions in a non disruptive way and app permissions with a dialog, that could work.

**Comment by avrignaud** [comment]
@keianhzo @MortimerGoro @cvan Can you share a list of the common web page permissions we need to handle? Off the top of my head, I remember: location, microphone, video. Are there others? Also, be helpful to give a suggested page or two that fires off the web page permission ask so @thenadj can take a look at it in OB on the Go. I'd imagine the final permissions dialog might be pretty similar for both web pages and app permissions - but would need to make sure the distinction is clear. 

Also, I think this permissions model suggests that we might need a "remember this choice" option, so the user isn't bothered in future. And that, in turn, suggests we need yet another setting/pane where the user can manage those permissions later (since they won't be prompted by the page later, or they might want to change global status for device permission). Does that sound about right?

**Comment by keianhzo** [comment]
@avrignaud Current permissions are:
- Web
  - Camera
  - Microphone
  - CameraAndMicrophone
  - Location
  - Notification

- App
  - ReadExternalStorage

What @MortimerGoro was referring to as non-disrupting permissions dialog is what Oculus does:
![permission](https://user-images.githubusercontent.com/837184/47218183-424cd500-d3ab-11e8-9820-99ac227c54ea.png)

For app related permission showing a dialog like we have now I think it's fine.

**Comment by jenniferhoang** [comment]
@keianhzo please see attached!
[Permissions - External Storage Read Access.zip](https://github.com/MozillaReality/FirefoxReality/files/2497476/Permissions.-.External.Storage.Read.Access.zip)

**Comment by jenniferhoang** [comment]
@keianhzo @avrignaud Please see all attached UI Specs for updated UI design for dialogs.

____


Please note the button changes, we took out all of the outlines b/c they don't render well. We also updated the divider lines to Rhino @ 1pt.
[UIS-16 Settings_014.pdf](https://github.com/MozillaReality/FirefoxReality/files/2531994/UIS-16.Settings_014.pdf)
<img width="260" alt="screen shot 2018-10-30 at 4 08 25 pm" src="https://user-images.githubusercontent.com/41343760/47756129-245e5a80-dc5e-11e8-93f6-ce00888b1cd5.png"><img width="268" alt="screen shot 2018-10-30 at 4 08 10 pm" src="https://user-images.githubusercontent.com/41343760/47756563-dba7a100-dc5f-11e8-8845-948e389f6f54.png">
<img width="1040" alt="screen shot 2018-10-30 at 4 08 41 pm" src="https://user-images.githubusercontent.com/41343760/47756166-41932900-dc5e-11e8-9e04-375d41bcfa9b.png">


____


We updated the buttons. No more outlines. The suggested button will be bright blue colored (Azure). Please note the 20px rounded corner change!

[UIS-37 User Prompt for Crash Reporting_003.pdf](https://github.com/MozillaReality/FirefoxReality/files/2531997/UIS-37.User.Prompt.for.Crash.Reporting_003.pdf)
<img width="447" alt="screen shot 2018-10-30 at 4 10 47 pm" src="https://user-images.githubusercontent.com/41343760/47756238-8b7c0f00-dc5e-11e8-8476-1f9a419571cc.png">

[UIS-25-Permissions Dialogs 004.pdf](https://github.com/MozillaReality/FirefoxReality/files/2532004/UIS-25-Permissions.Dialogs.004.pdf)
<img width="352" alt="screen shot 2018-10-30 at 4 14 28 pm" src="https://user-images.githubusercontent.com/41343760/47756353-f3325a00-dc5e-11e8-8bf5-f697d46b3e28.png">

[UIS-60 Speech&Voice Input Permissions_002.pdf](https://github.com/MozillaReality/FirefoxReality/files/2532008/UIS-60.Speech.Voice.Input.Permissions_002.pdf)
<img width="841" alt="screen shot 2018-10-30 at 4 15 36 pm" src="https://user-images.githubusercontent.com/41343760/47756399-1f4ddb00-dc5f-11e8-8e0b-c7032a3aa169.png">



____


Please see changes to exit button. In order to have consistency with the Dialog Menu in Settings, we are changing the X to a <- button that lays inside of the box. Also please note the change to 20px rounded corners too!
[UIS-29 Voice Command_004.pdf](https://github.com/MozillaReality/FirefoxReality/files/2532011/UIS-29.Voice.Command_004.pdf)
<img width="244" alt="screen shot 2018-10-30 at 4 16 50 pm" src="https://user-images.githubusercontent.com/41343760/47756434-47d5d500-dc5f-11e8-9305-16faf6a1c2bf.png">


____


Below is the most up-to-date color palette. Please let me know if you have any questions!
![uis-7 color palette_009](https://user-images.githubusercontent.com/41343760/47756219-7dc68980-dc5e-11e8-82c1-1025ab71f89e.png)

**Comment by keianhzo** [comment]
Thanks @jenniferhoang! I'm also going to need all the new icons in the settings panel.

**Comment by jenniferhoang** [comment]
No problem @keianhzo! Please see attached.
[UIS-16 Settings_014 Assets.zip](https://github.com/MozillaReality/FirefoxReality/files/2535862/UIS-16.Settings_014.Assets.zip)
