### ISSUE TITLE
Migrate History/Bookmarks to Android components

### ISSUE THREAD

**Issue by keianhzo** [MozillaReality/FirefoxReality#614]
Just a placeholder for future A-C migrations of History/Bookmarks

## Hardware
All

## Current Behavior
As Android components for Bookmarks/History is not ready yet we are going to make a custom minimal implementation using the content feed and localstorage #443 #442

## Expected Behavior
Should migrate to android components when https://github.com/mozilla-mobile/android-components/issues/905 https://github.com/mozilla-mobile/android-components/issues/1025 lands.

## Error Logs and Stack Traces
<details open>

```
```

</details>

**Comment by grigoryk** [comment]
Hello! The android-components bits for this are almost ready to go - #1025 is ready to land, and #905 is getting there - but currently the storage implementation is local-only - it won't sync, and the storage implementation that will sync with our ecosystem will be entirely different.

(For GeckoView, this is also blocked on https://bugzilla.mozilla.org/show_bug.cgi?id=1494713).

Do you intend to integrate with the Sync ecosystem? If not, using the local-only storage backend is fine. Otherwise, you might start with that and migrate over to the syncable history storage backend once that's ready, but that will require a data migration step.

Either way, if you wanted to use android-components support for history tracking, it's provided via the `concept-engine` and its concrete implementation components (like `browser-engine-gecko`). If you're not currently using engine components, that's prerequisite work.

**Comment by keianhzo** [comment]
Thanks great news @grigoryk! Storing locally is ok ATMbut we are not using concept-engine and we'll need to study how easy it would be to migrate as FxR has some particularities in the way it integrates GV. Thanks for the heads up!

**Comment by grigoryk** [comment]
If you need to, it will be possible to use the storage components by themselves without the engine, you'll just need to implement the relevant history engine hooks yourself (once GV makes them available).

**Comment by cvan** [comment]
Per @philip-lamb in https://github.com/MozillaReality/FirefoxReality/issues/443#issuecomment-464958974:

> https://bugzilla.mozilla.org/show_bug.cgi?id=1494713 is done.

Good catch. Looks like the history bits landed a while ago.

Here are the useful changes I see in the [changeset](https://bugzilla.mozilla.org/show_bug.cgi?id=1494713#c24):

- [`HistoryDelegate` interface](https://hg.mozilla.org/try/rev/59cc7da18875fc4fa1fe6ec8189df5199a0ce13c#l5.171)
- [`GeckoViewHistory` component](https://hg.mozilla.org/mozilla-central/rev/a1fe5c7791a7#l6.38)
- [`GeckoSessionHandler<HistoryDelegate>` for events](https://hg.mozilla.org/mozilla-central/rev/900cd4bf995f#l5.30)

**Comment by cvan** [comment]
Also, relevant docs:

- https://github.com/mozilla-mobile/android-components/blob/master/docs/api/mozilla.components.concept.engine.history/-history-tracking-delegate/index.md
- https://github.com/mozilla-mobile/android-components/blob/master/docs/api/mozilla.components.concept.storage/-history-storage/index.md
- https://github.com/search?utf8=%E2%9C%93&q=history+repo%3Amozilla-mobile%2Fandroid-components+path%3A%2Fdocs%2F&type=Code&ref=advsearch&l=&l=
