### ISSUE TITLE
Keyboard should be more comfortable to use.

### ISSUE THREAD

**Issue by thenadj** [MozillaReality/FirefoxReality#636]
## Hardware
Oculus Go

## Current Behavior
Keyboard position is not optimal. 

##Recommend
Users should be able to reposition keyboard. Also look into smart positioning for text fields. 

See this issue for reference:
https://github.com/MozillaReality/FirefoxReality/issues/378

**Comment by gfodor** [comment]
nice! worth checking out altspace or windows mixed reality's keyboard -- they avoid the "user can't see what they are typing" problem due to visual separate between keyboard + text field by including a text field above the keyboard that shows the value of the currently selected field. this approach has the added benefit of normalizing the visual and UX for text entry across all pages, so if a web page (for example) has a very small, hard to read text field or a poorly rendered font the user will still have an accessible way to see the current value as they edit it.

**Comment by gfodor** [comment]
oh, I think steam's keyboard does this too in their steam VR web browser.

**Comment by gfodor** [comment]
(so, you can still move the keyboard to somewhere comfortable for the user, but it reduces the need to have the text field be in the near visual field of the keyboard at all times)

**Comment by cvan** [comment]
this was was filed as #415 and #378. we should forward-dupe one/both of them or close this issue as a dupe.

**Comment by cvan** [comment]
also, see the keyboard in the Oculus Browser:

![image](https://user-images.githubusercontent.com/203725/47052400-eee54780-d15c-11e8-9c2e-abf78b38df62.png)

**Comment by thenadj** [comment]
@gfodor Thanks for the feedback. We originally had a text field as part of the keyboard but were asked to remove it. Honestly can't remember the reason, maybe just scope to get to v1.0. We should definitely think about adding that back, it's a great idea for all the reasons you mentioned.

**Comment by avrignaud** [comment]
@cvan I asked Nadja to open this Design issue so we'd have a copy in the Design Columns of the new GH project board. I think the issues you refer to above are already "In Progress" from the engineering perspective? We should chew on whether we want to be crisp on moving issues out of engineering -> design (and only have one), or have a design and engineering issue, allowing them to be tracked as separate issues in parallel. @larsbergstrom have an opinion?

Also Cvan, can you give an example of how one would forward-dupe an issue? I'm not familiar with the term, like to understand better. Thanks!

**Comment by keianhzo** [comment]
I like the way Oculus does it, it center aligns the keyboard to the middle of the text field.

![inkedkeyboard1_li](https://user-images.githubusercontent.com/837184/47098748-1d822180-d234-11e8-9115-3f38efa39810.jpg)
![inkedkeyboard2_li](https://user-images.githubusercontent.com/837184/47098808-368ad280-d234-11e8-92f9-03f5d385208d.jpg)

In their case it also helps the cylindrical projection that makes the further keys easier to see (I think we might address that in #321.

As our URL bar is at the bottom and placing the keyboard below it that can cause wrist pain I'd place the keyboard above the URL just for that text field and below for the Browser input fields.

Also I would consider removing the current keyboard rotation.

**Comment by bluemarvin** [comment]
It isn't clear to me from this design how the keyboard is oriented. Also, putting the keyboard above the text means the user has the potential to obscure the text field with the controller and controller beam while they are typing.

**Comment by MortimerGoro** [comment]
- Regarding adding a textfield to the keyboard it may be interesting solution and I like the consistency but one of my concerns is that it may hide autocompletion on some webpages. E.g. searching for videos on youtube I'd like to see the suggestions, how does the extra textfield deal with that situation?
- I miss the bigger picture of the keyboard on the URL bar. How will it work with the URL placement and the potential search Suggestions UI? What happens when resizing a window and when the URL bar is too at the bottom that you have to bend the wrist a lot or if you move the keyboard you can't see what you are typing?
- May be worth it to allow some keyboard scaling along with the move UI? I'm thinking that different people may have different sensibilities for the size. Probably not a v1.1 thing but it can be interesting to consider it for the future.

**Comment by thenadj** [comment]
Attached are some design options for repositioning and resizing the browser window. This is ready for review. 
[DE-30 Browser Positioning_003.pdf](https://github.com/MozillaReality/FirefoxReality/files/2515865/DE-30.Browser.Positioning_003.pdf)

**Comment by thenadj** [comment]
Attached are some design options for resizing the keyboard. This is ready for review. 
[DE-28 Keyboard Positioning_001.pdf](https://github.com/MozillaReality/FirefoxReality/files/2515885/DE-28.Keyboard.Positioning_001.pdf)

**Comment by thenadj** [comment]
@bluemarvin @MortimerGoro @kearwood @avrignaud 

Some thoughts after today's design review meeting. See DE-28 attached above and DE-12 attached here. If Github is too hard to come to a decision we can schedule a breakout session to further discuss this next week when Andre is back in the office. 

[DE-12 Keyboard_008.pdf](https://github.com/MozillaReality/FirefoxReality/files/2516417/DE-12.Keyboard_008.pdf)

1. Keyboard is always positioned above text box. Page does not auto scroll. 
Pro: It will never obscure text box
Con: Keyboard might be positioned too high up and hard to interact with

2. Keyboard is positioned above or below text field depending on placement of text box. Page does not auto scroll. 
Pro: Textbox is never obscured
Con: Keyboard moves up and down on Y-axis and prevents user from using muscle memory for typing. 

3. Keyboard is always in front of user, centered on browser window and text will auto scroll above and below keyboard depending on position of textbox. 
Pro: Comfortable to interact with keyboard using controller
Con: Short pages can't scroll up/down and keyboard will obscure textboxes. 

So, what's the perfect positioning of the keyboard?

For Android, we can't do overscrolling like iOS does because Apple has a patent on that. 

SUGGESTION:
Use Keyboard with integrated text box for URL text input.
Use regular keyboard for in-page textbox input and position keyboard in front of user (see Option 3 of DE-28) and scroll webpage up/down to reveal text boxes while keyboard stays in same place... unless page is too short for scrolling, then apply Option 2 from DE-28 where keyboard is automatically repositioned above or below text field. Hopefully short pages are not the norm and this will only happen on rare occasions.

**Comment by MortimerGoro** [comment]
@thenadj For regular textboxes I like that solution: Use the Option 3 when possible and fallback to Option 2. Probably better to place the keyboard below textboxes instead of above for Option 2 (@bluemarvin had concerns that placing the keyboard above could make the controller obscure what you are typing in some situations). A textbox on the bottom of a webpage should not be very common scenario, so I think we are ok.

Regarding the Keyboard placement for the URL, that's tied to the awesome bar design :)

**Comment by thenadj** [comment]
@MortimerGoro Sounds good, we'll move forward with that. As for URL bar. In DE-12 (attached to this issue) we propose a text input field at the top of the keyboard. I assume the awesomebar will be part of that keyboard text input field, rather than in the browser itself. We definitely don't want to show two awesomebar dropdowns. Can you confirm? Also, is DE-12 feasible for v1.1? @avrignaud ?

**Comment by thenadj** [comment]
[UIS-51 Keyboard Positioning (Multi Axis)_001.pdf](https://github.com/MozillaReality/FirefoxReality/files/2535583/UIS-51.Keyboard.Positioning.Multi.Axis._001.pdf)
Adding this UIS just so we have everything in one issue. Still waiting to hear about final direction.

**Comment by avrignaud** [comment]
@MortimerGoro What's your current priority workwise right now? Is this keyboard work doable in next week or so? Don't want to detract from theater/video work, or the 2D perf improvements @kearwood is trying to land.

**Comment by thenadj** [comment]
[UF-29 Keyboard Positioning_001.pdf](https://github.com/MozillaReality/FirefoxReality/files/2536724/UF-29.Keyboard.Positioning_001.pdf)
Attached is a user flow diagram with a few different keyboard options so we can find the best possible direction to implement. 

Adding the suggestions bar (awesomebar) popup adds complexity to the keyboard interaction. We also talked about adding a text field to the keyboard for URL bar entry which adds further complexity to the arrangement of UI elements. 

We probably need a breakout session to further discuss this work but I'd like to send it around for feedback now to get the conversation started.

**Comment by MortimerGoro** [comment]
> @MortimerGoro What's your current priority workwise right now? Is this keyboard work doable in next week or so? Don't want to detract from theater/video work, or the 2D perf improvements @kearwood is trying to land.

@keianhzo already did some work on the keyboard. We need this fixed: https://github.com/MozillaReality/FirefoxReality/issues/699

After finishing video work (still some projections and websites to test) I could review/continue the layers work that @kearwood started (I think he is on vacation next week),  address the keyboard or tabs implementation. I'll sync with @keianhzo and @kearwood.

**Comment by avrignaud** [comment]
@MozillaReality/fxr-eng - could we get some feedback on the UF-29 Keyboard Positioning user flow above? I think this is a good candidate for a breakout session, but I suspect there is feedback we can capture now to make that breakout session more productive.

**Comment by MortimerGoro** [comment]
For the regular texboxes we agreed on this (If anyone has concerns please mention it): `Use the Option 3 when possible and fallback to Option 2. Probably better to place the keyboard below textboxes instead of above for Option 2 `. 

Regarding the keyboard for the Awesome Bar, I'd choose option 3 from the PDF, it seems the more comfortable one for the keyboard position, see what you are typing and a big area for awesome bar suggestions.

**Comment by keianhzo** [comment]
@MozillaReality/fxr-eng I've a branch with an initial implementation of this but we need #699 fixed to be able to get a more accurate position (@bluemarvin is taking that over in the GV team).

Regarding the options, I think when we have cursor anchor info we should be able to scroll the page so it's always above the browser-centered keyboard and falls back to option 2 if the page is not scrollable. I also prefer to place it always below the focused textfield. Personally I think it'd be more intuitive for me if the keyboard always follows the same placement rule instead of changing depending on the conditions but we can try both an see what's better.

Regarding Keyboard + Awesome/suggestions bar I think that if we just placed the URL on the top we would avoid most of the obscuring issues like Ocuclus Browser does but for now option UF-29c it's ok.

**Comment by thenadj** [comment]
Thanks @MortimerGoro and @keianhzo for your feedback. We'll update the UF and add back to this issue once it's done.

**Comment by thenadj** [comment]
@MozillaReality/fxr-eng
Attached is the updated and hopefully final user flow for the keyboard positioning incorporating all of the feedback. At the very end there is a version with the URL bar above the browser window. Our concern is that if a user resizes the window too large, there will be tremendous neck strain trying to look at the URL bar high up. Our recommendation is to stay with the URL bar below the browser window. 
@avrignaud Please let us know when this is ready to implement.

**Comment by cvan** [comment]
> Attached is the updated and hopefully final user flow for the keyboard positioning incorporating all of the feedback.

I think the attachment is missing. can you upload again?

**Comment by Manishearth** [comment]
@cvan asked me to post my experiences: The main issue I find is that the space below the browser is straining to point at (in an oculus, anyway). The Oculus' default keyboard is pretty nice: It has square keys (easier to hit), and it shows up in front of you, as discussed above. Something similar to that would be great!

**Comment by thenadj** [comment]
Thank you @Manishearth for your feedback! If you take a look at UF-29 attached to this issue you will see the new design of the keyboard positioning. The keyboard is now always centered in front of the browser window for comfortable access and no more wrist pain. We originally placed the keyboard below the URL bar as a short term solution short of doing all the dev work to build in logic to reposition text boxes. We haven't user tested this yet but based on our experience with the Oculus browser it seems a good placement for the keyboard.

**Comment by Manishearth** [comment]
It looks good -- bit concerned about being able to detect if a page can scroll or not (sometimes the scrolling behavior is controlled programmatically and hard to detect)

Regarding the URL bar up top: this does make sense to me. Worth pointing out that it's very easy to _read_ things that are near the bottom, it's just interacting that requires centering, so ideally the url bar is up top (and thus easier to point at)

**Comment by caseyyee** [comment]
Should track with https://github.com/MozillaReality/FirefoxReality/issues/480

**Comment by MortimerGoro** [comment]
@thenadj created some sketchbox prototypes:
[PRO-2_Keyboard_Positioning_001_jh.sbd.zip](https://github.com/MozillaReality/FirefoxReality/files/2889349/PRO-2_Keyboard_Positioning_001_jh.sbd.zip)

After seeing the prototypes & trying how Oculus browser handles different text input locations here are my thoughts:

- I like the consistency of always having any text input just above the keyboard. It's easy to read while typing and you don't occlude the input text with the controller or the beam. If the position is different between the URL bar (placed below the keyboard) and the web text inputs (placed above the keyboard) we break the consistency of always having the text input on top.
- As @Manishearth mentioned forcing a page scroll to reposition a textbox to a target position can be problematic, not possible due to web layouts, or cause webcompat issues on some pages. Another problem is that you can scroll the web with the trackpad anytime, so we'd need to block the scrolling to not break the forced reposition. Webs can also programmatically change the scroll via JavaScript anytime or if some content takes some delay to load and triggers a relayout.

So this is my proposal to try to help make a decision:

- Due to the mentioned potential scrolling problems, I think that for web based text inputs the safest solution for next version would be to always place the keyboard centered and below the text input with some gap distance:
    - Consistency. You always see what you are typing at the same distance
    - You can use the already working trackpad scroll to change the position of the textinput (if the web has scrolling margin). The keyboard automatically follows the current textbox scrolling position both if it's triggered by the user or by the Web/Relayout. If the textbox goes out of the window bounds it's dismissed so the keyboard is hidden automatically.
    - Part of web search suggestions may be hidden (e.g. Amazon search). At least you can see & click the list by hiding the keyboard. If the user wants to type and see the list at the same time another solution would be allowing to move the keyboard offset from the automatic placement. 
    - if a user resizes the window too large and the textbox is on top of the web, the keyboard would be placed above the center with this solution. For top placed textboxes there is no scroll margin with the trackpad and repositioning hack is not posible (In addition to potential tech problems @bluemarvin mentioned there is a patent from Apple forbidding us to do overscrolling). Anyway I don't think this situation is going to be a big deal, reading the top of a very large window is already annoying and normally users would use more normal window heights so they keyboard is going to be comfortable most of the time on any vertical textbox position. We could set a max automatic keyboard y position threshold if a very large window is a concern.
- For the URL bar & awesome bar placement I think the best solution would be to use a mirror input element as shown in the image
<img width="334" alt="mirror2" src="https://user-images.githubusercontent.com/1070794/53172756-68e37c80-35e6-11e9-9076-dd2420bcaaaa.png">
This way:
 - The keyboard & the awesome bar list is always placed at a comfortable position.
 - Consistency. User still sees what he is typing at the same distance thanks to the mirror
 - You can use both the original URL bar and the mirror. For example if you start dragging/selecting a portion on the original URL bar, you can still dong that there even if the mirror appears. Any input/selection change will be visible on both.
- It works well with the IME autocompletion UI on the keyboard, a user can see the IME, textbox and awesomebar in the same view. Otherwise having IME above the keyboard but URL input and awesome bar list below may be confusing or not possible to see both in the same view

**Comment by philip-lamb** [comment]
Just one correction: Apple's "overscroll" patent 1) is strictly limited to touchscreen devices 2) only covers the "bounce back" part of the overscroll feature (i.e. it's the bounce that matters, not the display of an area outside the page bounds).

**Comment by jvonitter** [comment]
Design has updated the intended keyboard position and placement as reflected here:
https://trello.com/c/ZCy2A0qs/294-pro-3-keyboard-refinements

The intent is that the keyboard appears consistently in this location and does not move in relation to text fields. As text is entered, the letters appear in the text field that was selected.  

We'd like to get as close as possible to this positioning and placement (take a look at the PDF and the video) before deciding to further refine. Once this is done, we'll do some quick testing to validate the design. Next step after that will be to give users the ability to move the keyboard arbitrarily (UX TBD). Movable keyboard is outside the scope of this ticket, but will be documented by https://github.com/MozillaReality/FirefoxReality/issues/480
(cc @thenadj)

**Comment by MortimerGoro** [comment]
![image](https://user-images.githubusercontent.com/1070794/57153447-a9295d00-6dd6-11e9-9b57-e9500e58cd93.png)

@jvonitter @thenadj I think there's a potential problem with getting that visual layout between the keyboard top and the URL bar bottom. That works from the user eye camera but the remote controller is placed further down (in the hand of the user), so the ray from the controller can be in a conflict between the keyboard top and the URL bar. We already had that problem here https://github.com/MozillaReality/FirefoxReality/issues/377 and that's why we had to move it a little lower.

Is it possible to add a remote controller raycast in Sketchbox? I think it would be very helpful for the prototyping work.

Other than that I already implemented the new 2D layouts here https://github.com/MozillaReality/FirefoxReality/pull/1155. Note: the spec doesn't show what happens when the autocompletion is expanded (e.g. chinese keyboard). I decided to expand it to the bottom from the same position and hide the qwerty keyboard (which looks cut if not hidden)

**Comment by jvonitter** [comment]
Need to get data on this before deciding how/where to move the keyboard.

**Comment by jvonitter** [comment]
Now we have a movable keyboard! @thenadj are you ok closing this now or do you want to get more data about the default position?

**Comment by thenadj** [comment]
@jvonitter It's done.
