### ISSUE TITLE
Hover colors: ease in/out

### ISSUE THREAD

**Issue by MortimerGoro** [MozillaReality/FirefoxReality#66]
Browser window: ease the colors in and out to make it look a bit smoother than just abrupt color change

**Comment by MortimerGoro** [comment]
The easing formula is easeInOutCubic, it's explained in the UI spec

**Comment by keianhzo** [comment]
@thenadj Same as #140

**Comment by thenadj** [comment]
This is not the same as 140. This issue here is about adding an easing effect to the buttons. Currently when hovering over a button below the browser window, the transition from normal to hover to select seems instant and abrupt. We are looking for an easing effect on transition to soften the interaction experience. If there currently is an easing, then it's too fast. Can we slow it down?

**Comment by keianhzo** [comment]
@thenadj Sorry, I meant that this is related to #67 #223

**Comment by thenadj** [comment]
@keianhzo 
See UIS-21 (I slacked it to you) for easing instructions.
