### ISSUE TITLE
Sketchfab controller issues

### ISSUE THREAD

**Issue by keianhzo** [MozillaReality/FirefoxReality#770]
## Hardware
Oculus Go

## Steps to Reproduce
1. Go to sketchfab.com
2. Open any low poly model
3. Enter inmersive mode

## Current Behavior
The pointer inside Sketchfab seems to be shifted and seems to come out from the head instead of the hand.

Also the trigger button doesn't work.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/837184/48643504-be2f4280-e994-11e8-8e06-61ab91f654c8.gif)

## Expected Behavior
The controller should be located at the hand position.

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/837184/48643598-fe8ec080-e994-11e8-9cbd-9127659c2ad5.gif)

## Error Logs and Stack Traces
<details open>

```
```

</details>

**Comment by cvan** [comment]
Related issue #374

**Comment by cvan** [comment]
This is a WebCompat issue, btw. I've been engaged in emails with Alban and his engineers from Sketchfab. I can follow up with you privately so we can reach out to them with a list of proposed fixes for Oculus.

As Casey reported in this thread, https://github.com/MozillaReality/ContentFeed/pull/291#issuecomment-470753694:

> Few issues I found:
> * Controller on the Go shows up way above my head.
> * "Game Environment", "Sci-fi room" is zoomed way out on the outside of the environment.  Teleporting to various locations doesn't seem to help this.
> * "Captains Cabin" is very choppy.  I don't think this one is viewable, but it is in the right scale to view in VR which is nice.

Lots of these are Sketchfab issues, but figured I'd point them out anywhere.

**Comment by caseyyee** [comment]
Also, keep in mind that `getStandingMatrix` is changed in XR spec for frame reference: https://immersive-web.github.io/webxr-reference/webxr-device-api/#frame-of-reference-types

Also see: https://github.com/mrdoob/three.js/blob/master/src/renderers/webvr/WebXRManager.js#L304

ok bye

**Comment by cvan** [comment]
:+1: Thank you, that's extremely helpful info. I've forwarded this onto the Sketchfab folks.

**Comment by Kuranes** [comment]
Hi, Lots of things there, so a quick recap
- Sketchfab doesn't support webxr, only webvr.
- Sketchfab do support standing/nonstanding controller correction (and it does work on all other browser)

About controller/standing/etc, I was wondering if Firefox Reality doesn't gives same info on gamepad and HMD id than the "Oculus Go Browser" ?  Sketchfab needs to be able to choose between oculus rift touch, oculus rift remote, oculus rift gamepad, oculus go remote, and many others. For us best each HW has the exact same ID (instead of per browser), otherwise it get lost on what controller and hw specific code to attach.
Once we can ensure a good mapping you should get at least same feature set.

**Comment by caseyyee** [comment]
FXR in a 3dof headset does not return a sitStand transform. Oculus Go browser does.  The issue is documented in this issue: https://github.com/MozillaReality/FirefoxReality/issues/616  This is likely part of the cause.

I do believe that the proper behavior here is a possible point of discussion, but seems well covered in the WebXR spec. But until that is implemented, there needs to be some workaround applied.

**Comment by MortimerGoro** [comment]
I tried to add a sitStand transform to FxR (The same one as Oculus browser) but it didn't have any impact on this issue.

I'll debug part of the code to see what's the difference between both browsers. The Controller ID seems to be the same.

**Comment by Kuranes** [comment]
if it helps, we use https://jsfiddle.net/sketchfab/czb9667j/ internally to check on VR info/id/etc. 
(might need to host it on some page yourself to bypass lack of "frame vr allow" on jsfiddle iframe)

**Comment by MortimerGoro** [comment]
Fix ready in this PR: https://github.com/MozillaReality/FirefoxReality/pull/1036

We need to return a not null position in 3DOF VRPose (with the values of the neck model). Also set a sitStandingTransform as @caseyyee mentioned
