### ISSUE TITLE
[l10n] Buttons don't accomodate for localizations

### ISSUE THREAD

**Issue by Delphine** [MozillaReality/FirefoxReality#772]
## Hardware
Android v9 device

Please see attached screenshots. None of the French translations fit in the buttons, which is reproducible in almost all locales (non-English words are usually at least 30% longer than English words). 
In the cases of buttons, there isn't much choice for using a shorter localization, unfortunately.
![screenshot_20181116-133155](https://user-images.githubusercontent.com/399020/48648778-7369f680-e9a5-11e8-93dc-26fe3d742318.png)
![screenshot_20181116-133729](https://user-images.githubusercontent.com/399020/48648779-74028d00-e9a5-11e8-9086-72e90606f524.png)
![screenshot_20181116-133833](https://user-images.githubusercontent.com/399020/48648780-74028d00-e9a5-11e8-8260-bbd79245398b.png)

**Comment by thenadj** [comment]
We are aware of these issues and will address them on Monday. 

This one is not an issue, because each item should be on a different line. 
![image](https://user-images.githubusercontent.com/13240857/48649779-9cd85180-e9a8-11e8-92eb-fd6a07ffdb96.png)

We'll create a design with a button that can contain much larger text strings:
![image](https://user-images.githubusercontent.com/13240857/48649806-bd081080-e9a8-11e8-9b82-573f175bfa8b.png)

More on Monday.

**Comment by Delphine** [comment]
The French words here are:
* Modifier
and
* Réinitialiser

Some of the languages we ship are even longer than that, it seems (English has the shortest words in general, as mentioned in comment 1).

**Comment by thenadj** [comment]
Feedback from @keianhzo via Slack:
in a regular android UI the layout can be setup to expand and take all the screen space but of course in VR there is no limited screen space so widgets are fixed size. For widgets like the Developer panel we need to provide a size that works for all the languages. Inside the panels/dialogs there is no problem in making widgets wrap, match parent or have a fixed per language size but not for the root widget.

So probably best solution is to provide per language sizes for all the widgets: dialogs, buttons, etc
