### ISSUE TITLE
Improve names of 'Video Projection' choices

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#792]
## Hardware
All

## Steps to Reproduce
1. Load a 2D _video with controls_, such as one from the `Media` section of https://mzl.la/2JSKHWC
2. Press the Fullscreen icon in the bottom of the native video controls.
3. Once in Fullscreen, press the `Projection Mode` button (the VR-goggles icon) to expose the list.

## Current Behavior
![screenshot of 'Video Projection' list](https://user-images.githubusercontent.com/203725/48545348-8f24ae00-e87a-11e8-9067-5c3620f51b3b.png)

These are the options (mostly borrowed from the options shown in Oculus Browser and Samsung Internet Browser):

- `3D Side by Side`
- `360`
- `360 Stereo`
- `180`
- `Stereo 180 Left/Right`
- `Stereo 180 Top/Bottom`

## Expected Behavior
From @caseyyee in https://github.com/MozillaReality/FirefoxReality/pull/746#discussion_r235134242:
> Usually referred to as "over-under".
> Also Left/Right is usually referred to "side-by-side" or SBS
> 
> We shouldn't refer to video as 3D. It's stereo 360 or stereo 180, both being typically SBS (mostly assumed).

To my knowledge, @avrignaud and @caseyyee, you two are the domain experts on video playback.

## Possible Solution
Rename them to more industry-standard terms — terms that cinephiles would understand.

I know the icons are consistent with the other VR browsers', but IMO the icons aren't super obvious in what they represent.

## Context
Related issues:
- #763: remove unnecessary scrollbar at top, truncation of `Stereo 180 Top to Bottom`
- #791: add SUMO documentation for the Media Controls (including the various `Video Projection`s)

**Comment by cvan** [comment]
example of 360 Over-Under: https://www.youtube.com/watch?v=fSo_BDant_s

**Comment by caseyyee** [comment]
For downloaders, Over-Under (OU) or Side-by-side (SBS) is standard terminology used to describe 3D stereo video content, but to the lay-person, that's not entirely clear and doesn't help users understand which mode to select when they encounter 3D video.  For that, Left/Right and Top/Bottom makes more sense.

**Comment by caseyyee** [comment]
Also, an additional note. We should also not expect users to know the difference between VR content and 360/Media formats.  From a UX perspective, we may need to "train" the user to understand some of the differences so that when they encounter format choice, they can make reasonable assumptions about how to get it to work.

**Comment by cvan** [comment]
@caseyyee related: see https://github.com/MozillaReality/ContentFeed/issues/169#issuecomment-437254513

**Comment by philip-lamb** [comment]
This gets complex really quickly because of the many factors that vary:
- Mono/Stereo
- FOV: 180°/360°/other
- For 180° formats front-dome vs overhead dome.
- Stereo frame arrangement (side-by-side, half side-by-side, over-under, over-under half-height plus full-field vs row interlace vs column interlace)
- Projection: perspective/equirectangular/stereographic/cubemap/others

I've tried many different immersive and stereo players over many different years, and the best generally offer presets for the most common formats combined with a reveal control which shows and allows the adjustment of the individual parameters, and saving as a preset.
