### ISSUE TITLE
Oculus Go's `Sharing > Record Video` stops recording (and `Cast`) when Firefox Reality opens

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#805]
## Hardware
Oculus Go
743a8df

## Steps to Reproduce
1. Go to the Oculus lobby.
2. Ensure that Oculus' Tray is opened. (Press the Oculus button on the controller to toggle the Tray.)
3. Press the `Sharing` tab, and then press on the `Record Video` button.

    ![image](https://user-images.githubusercontent.com/203725/48867445-2ec6cc80-eda4-11e8-8ad3-4cc6874cb79f.png)
4. Notice the • red-dot icon is shown, indicating it's actively recording.
5. Open Firefox Reality.
6. Notice the • red-dot icon disappears, indicating the recording has stopped.

## Current Behavior
The video stops recording once the Firefox Reality splash screen opens.

## Expected Behavior
The video continues recording once the Firefox Reality splash screen opens.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by caseyyee** [comment]
I previously had crashes when trying to cast, but this no longer seems to be happening for me.
Can you give it another go?

**Comment by cvan** [comment]
> Can you give it another test?

still nope 😭 

similar issue: 
- #373

**Comment by philip-lamb** [comment]
I've successfully cast including a launch of FxR, navigating a page, search, page load, and entry of and interaction in immersive mode.

FWIW I've found the Oculus casting to be super-unreliable, unrelated to FxR. Even just from the Oculus home screen crashes and aborted launch of the stream in 80% of attempts. I'm guessing the encoding is CPU-bound and just can't keep with even modest CPU load. Network congestion also seems to kill the stream. So I think this isn't a FxR issue.

Will close as invalid since it's not our bug.

**Comment by cvan** [comment]
Found this comment on Reddit, FYI: https://www.reddit.com/r/OculusGo/comments/am2v9j/oculus_go_casting_webvr_content/efnhp4m/
