### ISSUE TITLE
User-Agent mode should move to Developer options

### ISSUE THREAD

**Issue by caseyyee** [MozillaReality/FirefoxReality#872]
Not sure why it's under display.

**Comment by cvan** [comment]
It was changed per the IA changes described here: https://github.com/MozillaReality/FirefoxReality/issues/638#issuecomment-434772658

I accidentally click the wrong section in the Settings multiple times a day, but users might be fine with it. we're not measuring it so yeah. not sure.

realted: see issue #19, in particular my comment: https://github.com/MozillaReality/FirefoxReality/issues/19#issuecomment-422605838

**Comment by cvan** [comment]
can we reconsider this, given the comment above https://github.com/MozillaReality/FirefoxReality/issues/872#issuecomment-443043795?

if there are issues closed and marked with the label `wontfix`, can we begin to provide rationale? a sentence or two would help, especially as users come to re-report or comment on closed bugs and don't know why a decision was made. (it's typically Mozilla etiquette with both Bugzilla + GitHub issues.) thank you!

**Comment by philip-lamb** [comment]
Sure, happy to provide an explanation: per #19 this was designed as a user-facing setting and it was subsequently specified in UX output as a user-facing setting. Therefore, it should not be moved into a settings pane intended for developers (and which may at some point be hidden from the UI by default -- and there are other user-facing settings currently in the "Developer" pane which we also need to move out). It could be argued that we ought to have an "Advanced" settings grouping, but from now on, requests for UX rework will require a proper justification in terms of user flow and approval for design review, rather than just filing a bug with a one-liner as the OP did. Happy to discuss this process via pm or email. Cheers.

**Comment by cvan** [comment]
this is perfect. thank you for the explanation. this is an admittedly power-user feature. as our WebCompat game gets stronger, this should be less important if everything goes as planned. #962 (originally #19) should eliminate the pain point identified by @caseyyee in this issue. if we hear from users about reports, we can obviously discuss then. thank you again.

**Comment by philip-lamb** [comment]
Note also that I opened a new issue #962 for one-click access to this.

**Comment by caseyyee** [comment]
Ideally, the setting would be more accessible.  I have often wanted to get a desktop layout, and having to fish through any settings gets a bit annoying.
