### ISSUE TITLE
Investigate compatibility with YouTube TV

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#876]
## Hardware
Oculus Go

## Steps to Reproduce
1. Load https://www.youtube.com/tv

# Context
[`Will youtube TV work on Firefox realty?` – asked on Reddit](https://www.reddit.com/r/FirefoxReality/comments/a03lhm/will_youtube_tv_work_on_firefox_realty/)

**Comment by caseyyee** [comment]
Would be nice to use the login flow so users don't have to use full login credentials.

**Comment by cvan** [comment]
> Would be nice to use the login flow so users don't have to use full login credentials.

what do you mean by this?

**Comment by caseyyee** [comment]
Login is done through the use of a id# of QR code

![image](https://user-images.githubusercontent.com/1560884/49842259-a8345800-fd6f-11e8-84d1-5035e7d4abd1.png)

So rather than having to do it within the headset, you can do it by mobile or desktop where you already are logged in.  saves trying to copy passwords into the headset.

**Comment by cvan** [comment]
Per this [/r/OculusGo thread](https://www.reddit.com/r/OculusGo/comments/asegfn/oculus_browser_with_a_flat_screen_rather_than/):

> I like the functionality of the built in Oculus Browser but was wondering if there was a way to flatten the screen for it. I'm not a fan of the curved screen.
> 
> (I'd use Firefox Reality as an alternative since it does have a flat screen, but it doesn't work with YouTube TV, which is my main reason for using the browser.)

**Comment by philip-lamb** [comment]
Do we know if youtube TV is DRM-protected?
