### ISSUE TITLE
System lockup when accessing navigator.mediaDevices API on VIVE Focus

### ISSUE THREAD

**Issue by shang-huang** [MozillaReality/FirefoxReality#929]
## Hardware
HTC Vive Focus

## Steps to Reproduce

1. Turn on the camera permission for FxR manually in settings.   
2. Access web page with code below [(Reference):](https://developers.google.com/web/fundamentals/media/recording-video/#access_the_camera_interactively)
```
<video id="player" controls></video>
<script>
  var player = document.getElementById('player');

  var handleSuccess = function(stream) {
    player.srcObject = stream;
  };

  navigator.mediaDevices.getUserMedia({ audio: true, video: true })
      .then(handleSuccess)
</script>
```
## Current Behavior
Vive Focus pop information like "Can't track position" and whole system seems crashed.

## Expected Behavior
When test on Google Pixel with Vive Wave services installed, the camera view shows normal.

## Context
Version: FirefoxReality-1.1.2-30091627-wavevr-arm-release-signed-aligned.apk

## Error Logs and Stack Traces

<details open>

```
Crash (signature: `libc.so@0x3fcec`)
```

</details>

**Comment by cvan** [comment]
@shang-huang: Thank you taking the time to report this. This is important. We will investigate this crash and post updates in this issue. Stay tuned.

**Comment by cvan** [comment]
I found the crash report:

https://crash-stats.mozilla.com/signature/?product=FirefoxReality&signature=libc.so%400x3fcec&version=66.0a1&date=%3C2019-01-30T00%3A54%3A55%2B00%3A00&date=%3E%3D2019-01-23T00%3A54%3A55%2B00%3A00#summary

- Signature: `libc.so@0x3fcec`
- [List of all reported crashes with same signature](https://crash-stats.mozilla.com/signature/?product=FirefoxReality&version=66.0a1&signature=libc.so%400x3fcec&date=%3E%3D2019-01-22T16%3A54%3A55.000Z&date=%3C2019-01-29T16%3A54%3A55.000Z&_columns=date&_columns=product&_columns=version&_columns=build_id&_columns=platform&_columns=reason&_columns=address&_columns=install_time&_sort=-date&page=1#reports)

**Comment by philip-lamb** [comment]
Can we get a backtrace? Does that require minidump access permissions?

**Comment by cvan** [comment]
> Can we get a backtrace? Does that require minidump access permissions?

You can see the stack traces by clicking on the individual reports in [this list](https://crash-stats.mozilla.com/signature/?product=FirefoxReality&version=66.0a1&signature=libc.so%400x3fcec&date=%3E%3D2019-01-22T16%3A54%3A55.000Z&date=%3C2019-01-29T16%3A54%3A55.000Z&_columns=date&_columns=product&_columns=version&_columns=build_id&_columns=platform&_columns=reason&_columns=address&_columns=install_time&_sort=-date&page=1#reports).

If you launch the URL `about:crashparent`, you can simulate a crash.

I just now added some documentation to the Wiki that I hope curious folks will find useful: https://github.com/MozillaReality/FirefoxReality/wiki/Developer-Tools#crashes

Let me know if I correctly understood your question.

**Comment by philip-lamb** [comment]
The crash report is puzzling. I'll have a go at replicating.

**Comment by philip-lamb** [comment]
OK, I have partially replicated this.

Note that the step of manually enabling camera access in the System Preferences is required. Without this step, the page just shows a media control that does nothing (also no prompt to show media). But with the permission added, the reported behaviour (app locks up/disappears, system shows "Can't track position") is observed. The app does NOT however crash (process is still running) and no crash data appears in the event log -- so I expect that the crash message above is from a different cause.

In one way, we should question what the expected behaviour is here; accessing the camera is going to interrupt the system's use of the cameras for tracking, so having the report that tracking is lost is pretty natural. On the other hand, this shouldn't lock up the system. This might be a Wave system bug around shared access to the cameras.

I've attached a logcat across the event. Page containing the media controls loads around 2019-02-21 13:16:51.556 (you can see a JS message), and system puts up tracking lost notice at 2019-02-21 13:16:52.705 2098-2112. The Firefox Reality PID is 3214 in this log.
[logcat-929.txt](https://github.com/MozillaReality/FirefoxReality/files/2887143/logcat-929.txt)

**Comment by philip-lamb** [comment]
One additional note: I would assume that since the camera image is being requested by the web view, it's probably geckoview using the standard Android camera API. It'd be a useful test case to see what happens attempting camera access via the wavevr api.
