### ISSUE TITLE
GV preferences not applied on first launch

### ISSUE THREAD

**Issue by MortimerGoro** [MozillaReality/FirefoxReality#93]
e.g: Enabling WebVR preference and loading the WebVR sample gets the "page says WebVR found but no displays available." on the first launch.
On next launches it runs ok.

**Comment by bluemarvin** [comment]
This is due to the fact that PrefsHelper.setPref set the prefs after gfxPref are read. After the first run, the prefs are written to the user profile so that they are read correctly the next time FxR is run. The best solution until an new Prefs API is added to gecko is to write out a user.js with these prefs to the profile directory so they may be read before gfxPrefs are read.
